# Bipartite graph scratch

In [229]:
import numpy as np
import polars as pl
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import optuna
from sklearn.metrics import accuracy_score, f1_score
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.svm import SVC, LinearSVC

In [2]:
rna = pl.read_csv("xena_brca_data/TCGA.BRCA.sampleMap_HiSeqV2", separator="\t")

In [3]:
# split into training and testing sets

shape: (20_530, 1_219)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sample    ┆ TCGA-AR-A ┆ TCGA-D8-A ┆ TCGA-BH-A ┆ … ┆ TCGA-B6-A ┆ TCGA-BH-A ┆ TCGA-3C-A ┆ TCGA-B6- │
│ ---       ┆ 5QQ-01    ┆ 1JA-01    ┆ 0BQ-01    ┆   ┆ 0X7-01    ┆ 1EV-11    ┆ ALJ-01    ┆ A0X1-01  │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ ARHGEF10L ┆ 9.5074    ┆ 7.4346    ┆ 9.3216    ┆ … ┆ 10.5745   ┆ 9.4048    ┆ 10.9468   ┆ 10.3164  │
│ HIF3A     ┆ 1.5787    ┆ 3.6607    ┆ 2.7224    ┆ … ┆ 4.0696    ┆ 7.2537    ┆ 0.931     ┆ 2.4191   │
│ RNF17     ┆ 0.0       ┆ 0.6245    ┆ 0.5526    ┆ … ┆ 0.4258    ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ RNF10     ┆ 11.3676   ┆ 11.9181   ┆ 11.9665   ┆ … ┆ 11.8663   ┆ 11.546    ┆ 12.2616   ┆ 12.157   │
│ RNF11     ┆ 11.1292   ┆ 13.5273   ┆ 11.4105   ┆ … ┆ 10.7644   ┆ 11.8774   ┆ 10.7842   ┆ 11.242   │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ PTRF      ┆ 13.8808   ┆ 10.7066   ┆ 12.9973   ┆ … ┆ 12.7548   ┆ 13.1131   ┆ 12.5534   ┆ 9.5126   │
│ BCL6B     ┆ 7.383     ┆ 7.2467    ┆ 8.3374    ┆ … ┆ 9.0657    ┆ 8.7063    ┆ 8.7597    ┆ 6.1074   │
│ GSTK1     ┆ 11.4289   ┆ 9.1673    ┆ 11.34     ┆ … ┆ 11.1277   ┆ 10.9711   ┆ 12.0469   ┆ 11.5929  │
│ SELP      ┆ 7.8456    ┆ 0.0       ┆ 8.3765    ┆ … ┆ 8.6348    ┆ 9.4892    ┆ 5.6941    ┆ 1.6664   │
│ SELS      ┆ 10.7384   ┆ 10.1225   ┆ 9.9367    ┆ … ┆ 9.6448    ┆ 9.6596    ┆ 10.1682   ┆ 9.3894   │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [7]:
gene_names = rna[:,0]
rna = rna.drop("sample")

In [13]:
# load labels

clinicalMatrix = pl.read_csv("xena_brca_data/TCGA.BRCA.sampleMap_BRCA_clinicalMatrix", separator="\t", infer_schema_length=0)

cM = clinicalMatrix.filter(pl.col("PAM50_mRNA_nature2012") != "null")
cM

shape: (522, 194)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sampleID  ┆ AJCC_Stag ┆ Age_at_In ┆ CN_Cluste ┆ … ┆ _GENOMIC_ ┆ _GENOMIC_ ┆ _GENOMIC_ ┆ _GENOMIC │
│ ---       ┆ e_nature2 ┆ itial_Pat ┆ rs_nature ┆   ┆ ID_TCGA_B ┆ ID_TCGA_B ┆ ID_TCGA_B ┆ _ID_TCGA │
│ str       ┆ 012       ┆ hologic_D ┆ 2012      ┆   ┆ RCA_G4502 ┆ RCA_exp_H ┆ RCA_gisti ┆ _BRCA_PD │
│           ┆ ---       ┆ iagno…    ┆ ---       ┆   ┆ A_07_…    ┆ iSeqV…    ┆ c2        ┆ Marray   │
│           ┆ str       ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆           ┆   ┆ str       ┆ str       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ TCGA-A1-A ┆ Stage IIA ┆ 59        ┆ 2         ┆ … ┆ TCGA-A1-A ┆ 15bad71d- ┆ TCGA-A1-A ┆ TCGA-A1- │
│ 0SD-01    ┆           ┆           ┆           ┆   ┆ 0SD-01A-1 ┆ 3031-413b ┆ 0SD-01A-1 ┆ A0SD-01  │
│           ┆           ┆           ┆           ┆   ┆ 1R-A115-0 ┆ -9e8d-642 ┆ 1D-A111-0 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆ 6ae5d…    ┆ 1         ┆          │
│ TCGA-A1-A ┆ Stage I   ┆ 56        ┆ 2         ┆ … ┆ TCGA-A1-A ┆ a998e0ce- ┆ TCGA-A1-A ┆ TCGA-A1- │
│ 0SE-01    ┆           ┆           ┆           ┆   ┆ 0SE-01A-1 ┆ 9248-460f ┆ 0SE-01A-1 ┆ A0SE-01  │
│           ┆           ┆           ┆           ┆   ┆ 1R-A084-0 ┆ -aabc-2da ┆ 1D-A087-0 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆ d452a…    ┆ 1         ┆          │
│ TCGA-A1-A ┆ Stage IIA ┆ 39        ┆ 5         ┆ … ┆ TCGA-A1-A ┆ dce3de3e- ┆ TCGA-A1-A ┆ TCGA-A1- │
│ 0SH-01    ┆           ┆           ┆           ┆   ┆ 0SH-01A-1 ┆ f851-4859 ┆ 0SH-01A-1 ┆ A0SH-01  │
│           ┆           ┆           ┆           ┆   ┆ 1R-A084-0 ┆ -a208-72e ┆ 1D-A087-0 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆ 65d36…    ┆ 1         ┆          │
│ TCGA-A1-A ┆ Stage     ┆ 39        ┆ 3         ┆ … ┆ TCGA-A1-A ┆ 61017170- ┆ TCGA-A1-A ┆ TCGA-A1- │
│ 0SJ-01    ┆ IIIA      ┆           ┆           ┆   ┆ 0SJ-01A-1 ┆ a36a-4ce9 ┆ 0SJ-01A-1 ┆ A0SJ-01  │
│           ┆           ┆           ┆           ┆   ┆ 1R-A084-0 ┆ -9b8e-324 ┆ 1D-A087-0 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆ 755b8…    ┆ 1         ┆          │
│ TCGA-A1-A ┆ Stage IIA ┆ 54        ┆ 1         ┆ … ┆ TCGA-A1-A ┆ a63583ca- ┆ TCGA-A1-A ┆ TCGA-A1- │
│ 0SK-01    ┆           ┆           ┆           ┆   ┆ 0SK-01A-1 ┆ 0ef2-4417 ┆ 0SK-01A-1 ┆ A0SK-01  │
│           ┆           ┆           ┆           ┆   ┆ 2R-A084-0 ┆ -b435-5f3 ┆ 2D-A087-0 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆ a6951…    ┆ 1         ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ TCGA-E2-A ┆ Stage     ┆ 74        ┆ 2         ┆ … ┆ TCGA-E2-A ┆ 2d51ae30- ┆ TCGA-E2-A ┆ TCGA-E2- │
│ 1B4-01    ┆ IIIA      ┆           ┆           ┆   ┆ 1B4-01A-1 ┆ 4c8a-4c99 ┆ 1B4-01A-1 ┆ A1B4-01  │
│           ┆           ┆           ┆           ┆   ┆ 1R-A12P-0 ┆ -b216-fc4 ┆ 1D-A12N-0 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆ fbda0…    ┆ 1         ┆          │
│ TCGA-E2-A ┆ Stage IIA ┆ 46        ┆ 3         ┆ … ┆ TCGA-E2-A ┆ a2c80f8e- ┆ TCGA-E2-A ┆ TCGA-E2- │
│ 1B5-01    ┆           ┆           ┆           ┆   ┆ 1B5-01A-2 ┆ f08d-4574 ┆ 1B5-01A-2 ┆ A1B5-01  │
│           ┆           ┆           ┆           ┆   ┆ 1R-A12P-0 ┆ -90a0-f06 ┆ 1D-A12N-0 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆ 51c0a…    ┆ 1         ┆          │
│ TCGA-E2-A ┆ Stage IIA ┆ 44        ┆ 1         ┆ … ┆ TCGA-E2-A ┆ eb398b00- ┆ TCGA-E2-A ┆ TCGA-E2- │
│ 1B6-01    ┆           ┆           ┆           ┆   ┆ 1B6-01A-3 ┆ 8669-4c22 ┆ 1B6-01A-3 ┆ A1B6-01  │
│           ┆           ┆           ┆           ┆   ┆ 1R-A12P-0 ┆ -8285-03c ┆ 1D-A12N-0 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆ df764…    ┆ 1         ┆          │
│ TCGA-E2-A ┆ Stage IA  ┆ 63        ┆ 2         ┆ … ┆ TCGA-E2-A ┆ a2cf164c- ┆ TCGA-E2-A ┆ TCGA-E2- │
│ 1BC-01    ┆           ┆           ┆           ┆   ┆ 1BC-01A-1 ┆ 5b26-43eb ┆ 1BC-01A-1 ┆ A1BC-01  │
│           ┆           ┆           ┆           ┆   ┆ 1R-A12P-0 ┆ -9de9-d1d ┆ 1D-A12N-0 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆ 457a5…    ┆ 1         ┆          │
│ TCGA-E2-A ┆ Stage IIA ┆ 53        ┆ 2         ┆ … ┆ TCGA-E2-A ┆ fa1917b0- ┆ TCGA-E2-A ┆ TCGA-E2- │
│ 1BD-01    ┆           ┆           ┆           ┆   ┆ 1BD-01A-1 ┆ c3e1-412d ┆ 1BD-01A-1 ┆ A1BD-01  │
│           ┆           ┆           ┆           ┆   ┆ 1R-A12P-0 ┆ -b063-e74 ┆ 1D-A12N-0 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆ b5caf…    ┆ 1         ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [17]:
labels = cM.select(["sampleID","PAM50_mRNA_nature2012"])
labels = labels.filter(pl.col("PAM50_mRNA_nature2012") != "Normal-like")

In [33]:
y_all = labels["PAM50_mRNA_nature2012"].to_numpy()
y_all

array(['Luminal A', 'Luminal A', 'Luminal A', 'Luminal A', 'Basal-like',
       'Luminal B', 'Basal-like', 'Luminal A', 'Basal-like', 'Basal-like',
       'Luminal B', 'Basal-like', 'Basal-like', 'Luminal A',
       'HER2-enriched', 'HER2-enriched', 'Luminal A', 'HER2-enriched',
       'Basal-like', 'Luminal A', 'Luminal A', 'Luminal A', 'Luminal B',
       'Luminal A', 'Luminal A', 'Luminal B', 'HER2-enriched',
       'HER2-enriched', 'Luminal A', 'Basal-like', 'HER2-enriched',
       'Basal-like', 'Luminal A', 'Luminal B', 'Luminal A', 'Luminal A',
       'Luminal A', 'HER2-enriched', 'Luminal B', 'Luminal A',
       'Luminal A', 'Luminal A', 'Luminal A', 'Luminal A', 'Luminal A',
       'Luminal B', 'Basal-like', 'Luminal A', 'Luminal B', 'Luminal B',
       'Basal-like', 'Luminal A', 'Basal-like', 'HER2-enriched',
       'Basal-like', 'Luminal B', 'Luminal B', 'Luminal A', 'Luminal A',
       'Luminal A', 'Luminal A', 'Luminal A', 'Basal-like', 'Luminal A',
       'Luminal B', 'Luminal B', 'Luminal A', 'Basal-like', 'Luminal A',
       'Basal-like', 'Luminal A', 'Basal-like', 'Luminal A', 'Luminal A',
       'Luminal B', 'Luminal A', 'Basal-like', 'Luminal A', 'Basal-like',
       'Basal-like', 'Luminal B', 'Luminal B', 'Luminal B', 'Luminal A',
       'Luminal B', 'Luminal B', 'Luminal A', 'Luminal A', 'Luminal B',
       'Luminal A', 'Luminal B', 'HER2-enriched', 'HER2-enriched',
       'Luminal B', 'HER2-enriched', 'Basal-like', 'Luminal A',
       'Luminal A', 'Luminal A', 'HER2-enriched', 'Luminal A',
       'Luminal B', 'Basal-like', 'Luminal A', 'Basal-like', 'Luminal B',
       'Basal-like', 'Luminal B', 'Luminal B', 'HER2-enriched',
       'Luminal B', 'Luminal A', 'Luminal B', 'Luminal B', 'Luminal A',
       'Luminal A', 'HER2-enriched', 'Luminal A', 'Luminal B',
       'Luminal B', 'Basal-like', 'Luminal B', 'HER2-enriched',
       'HER2-enriched', 'Luminal A', 'Luminal B', 'Basal-like',
       'Luminal A', 'HER2-enriched', 'Luminal A', 'Luminal A',
       'Luminal A', 'HER2-enriched', 'Luminal A', 'HER2-enriched',
       'Luminal B', 'Luminal B', 'Luminal B', 'Luminal A', 'Luminal A',
       'Luminal A', 'Luminal B', 'Luminal B', 'HER2-enriched',
       'Luminal B', 'Luminal B', 'Luminal B', 'Luminal B', 'Luminal B',
       'Luminal A', 'Luminal A', 'Luminal B', 'HER2-enriched',
       'Luminal B', 'Luminal A', 'Luminal A', 'Luminal A', 'Luminal A',
       'HER2-enriched', 'Luminal B', 'Luminal B', 'Luminal A',
       'Luminal A', 'Luminal B', 'Luminal B', 'Luminal A', 'Luminal B',
       'Luminal A', 'HER2-enriched', 'Basal-like', 'Luminal B',
       'Luminal B', 'Basal-like', 'Luminal B', 'Basal-like', 'Luminal B',
       'Basal-like', 'Luminal A', 'Luminal B', 'Basal-like', 'Luminal B',
       'Basal-like', 'Luminal A', 'Luminal A', 'Luminal A',
       'HER2-enriched', 'Luminal A', 'Basal-like', 'Luminal B',
       'Luminal A', 'Basal-like', 'Luminal A', 'Luminal A', 'Luminal A',
       'Luminal A', 'Luminal B', 'Luminal A', 'Luminal A', 'Basal-like',
       'Luminal A', 'Luminal B', 'HER2-enriched', 'Luminal A',
       'HER2-enriched', 'Luminal B', 'Luminal B', 'Luminal A',
       'HER2-enriched', 'Luminal B', 'Basal-like', 'Basal-like',
       'Luminal B', 'Luminal A', 'Luminal A', 'Luminal A', 'Luminal B',
       'Luminal B', 'HER2-enriched', 'Luminal A', 'Luminal A',
       'Luminal B', 'Luminal A', 'Basal-like', 'Luminal B', 'Basal-like',
       'Luminal A', 'Luminal A', 'Basal-like', 'Basal-like', 'Luminal A',
       'Luminal B', 'Luminal A', 'HER2-enriched', 'Luminal A',
       'Basal-like', 'Luminal A', 'Luminal A', 'Luminal B', 'Basal-like',
       'Luminal A', 'Basal-like', 'Luminal B', 'Luminal A', 'Basal-like',
       'Luminal B', 'Basal-like', 'Luminal B', 'Luminal A',
       'HER2-enriched', 'Luminal B', 'Luminal B', 'Basal-like',
       'Basal-like', 'Luminal B', 'Luminal B', 'Basal-like', 'Basal-like',
       'Basal-like', 'Basal-like', 'Luminal A', 'Luminal A', 'Luminal A',
       'Luminal A', 'Basal-like', 'Basal-like', 'Luminal A',
       'HER2-enriched', 'Luminal A', 'Luminal B', 'Luminal A',
       'Luminal A', 'Basal-like', 'Basal-like', 'Luminal A', 'Basal-like',
       'Luminal A', 'HER2-enriched', 'Luminal A', 'Luminal B',
       'Luminal B', 'Luminal A', 'Luminal A', 'Basal-like',
       'HER2-enriched', 'Luminal B', 'Luminal A', 'Luminal A',
       'Luminal A', 'Basal-like', 'Basal-like', 'Luminal A',
       'HER2-enriched', 'Luminal A', 'Luminal B', 'Luminal A',
       'Luminal A', 'Luminal A', 'Luminal A', 'Luminal A',
       'HER2-enriched', 'Basal-like', 'Basal-like', 'Luminal A',
       'Luminal A', 'Luminal A', 'Luminal B', 'Luminal B', 'Basal-like',
       'Luminal A', 'Luminal A', 'Luminal A', 'Basal-like', 'Luminal A',
       'Luminal B', 'Luminal A', 'Luminal B', 'Basal-like',
       'HER2-enriched', 'Luminal B', 'Luminal A', 'Luminal A',
       'Luminal A', 'Basal-like', 'Luminal A', 'Luminal B',
       'HER2-enriched', 'Luminal A', 'Basal-like', 'Luminal A',
       'Luminal A', 'Luminal B', 'Luminal B', 'Basal-like', 'Luminal A',
       'Basal-like', 'Luminal A', 'Luminal A', 'Luminal A', 'Luminal A',
       'Luminal A', 'Luminal A', 'Luminal A', 'Luminal A', 'Basal-like',
       'Luminal B', 'Luminal B', 'Luminal A', 'Luminal B', 'Luminal B',
       'Luminal B', 'Luminal A', 'Luminal A', 'Luminal A', 'Luminal A',
       'Luminal A', 'Basal-like', 'Luminal A', 'Luminal A', 'Luminal A',
       'Luminal A', 'Luminal A', 'Luminal A', 'HER2-enriched',
       'Basal-like', 'Luminal A', 'Luminal A', 'Basal-like', 'Luminal A',
       'Luminal A', 'Luminal A', 'Luminal A', 'HER2-enriched',
       'Luminal A', 'Luminal A', 'Luminal A', 'Luminal B', 'Luminal A',
       'Luminal A', 'Luminal A', 'Luminal A', 'Luminal A', 'Luminal A',
       'Luminal A', 'Luminal A', 'Luminal A', 'Luminal A', 'Basal-like',
       'Basal-like', 'Luminal A', 'Luminal A', 'Luminal A', 'Luminal B',
       'Luminal B', 'Luminal A', 'HER2-enriched', 'Basal-like',
       'Luminal B', 'Luminal A', 'Luminal A', 'Luminal A', 'Basal-like',
       'Luminal B', 'Basal-like', 'Luminal A', 'Luminal A', 'Luminal B',
       'Basal-like', 'Luminal B', 'Luminal A', 'Luminal A',
       'HER2-enriched', 'Basal-like', 'HER2-enriched', 'Luminal A',
       'Luminal A', 'Luminal B', 'Basal-like', 'Luminal A', 'Luminal A',
       'Luminal A', 'Luminal A', 'HER2-enriched', 'Luminal B',
       'Basal-like', 'Basal-like', 'HER2-enriched', 'Luminal B',
       'Luminal A', 'Luminal A', 'HER2-enriched', 'HER2-enriched',
       'HER2-enriched', 'Luminal B', 'Basal-like', 'Luminal B',
       'Luminal B', 'Luminal A', 'HER2-enriched', 'HER2-enriched',
       'Basal-like', 'Luminal A', 'Luminal A', 'Basal-like',
       'HER2-enriched', 'HER2-enriched', 'HER2-enriched', 'HER2-enriched',
       'Luminal B', 'Luminal A', 'Luminal B', 'Luminal B', 'Luminal B',
       'Luminal B', 'HER2-enriched', 'Luminal B', 'Luminal A',
       'Basal-like', 'Basal-like', 'Luminal A', 'Basal-like', 'Luminal A',
       'Luminal A', 'Luminal B', 'Luminal B', 'Luminal B', 'Luminal A',
       'Luminal B', 'Luminal A', 'Luminal A', 'Basal-like', 'Luminal B',
       'HER2-enriched', 'Luminal A', 'Basal-like', 'Luminal B',
       'Luminal A', 'HER2-enriched', 'Luminal B', 'Basal-like',
       'Basal-like', 'Luminal A', 'Basal-like', 'HER2-enriched',
       'Luminal A', 'Luminal A', 'Luminal B', 'Luminal A', 'Basal-like',
       'Basal-like', 'Luminal B', 'Luminal A', 'Luminal A', 'Luminal A',
       'Luminal A', 'Luminal A', 'Luminal A', 'Luminal A', 'Luminal A',
       'Luminal B', 'Luminal B', 'Luminal B', 'Luminal A', 'Luminal A',
       'Luminal A', 'Luminal B', 'Luminal B', 'Basal-like',
       'HER2-enriched', 'Luminal A', 'Luminal A', 'Basal-like',
       'Luminal A', 'Luminal A', 'Luminal A'], dtype=object)

In [18]:
np.unique(labels["PAM50_mRNA_nature2012"].to_numpy(), return_counts=True)

(array(['Basal-like', 'HER2-enriched', 'Luminal A', 'Luminal B'],
       dtype=object),
 array([ 98,  58, 231, 127]))

In [23]:
rna = rna.select(labels["sampleID"].to_numpy())

In [24]:
rna

shape: (20_530, 514)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ TCGA-A1-A ┆ TCGA-A1-A ┆ TCGA-A1-A ┆ TCGA-A1-A ┆ … ┆ TCGA-E2-A ┆ TCGA-E2-A ┆ TCGA-E2-A ┆ TCGA-E2- │
│ 0SD-01    ┆ 0SE-01    ┆ 0SH-01    ┆ 0SJ-01    ┆   ┆ 1B5-01    ┆ 1B6-01    ┆ 1BC-01    ┆ A1BD-01  │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 9.1657    ┆ 9.7179    ┆ 8.8669    ┆ 9.7663    ┆ … ┆ 8.9027    ┆ 8.6965    ┆ 9.0303    ┆ 10.7991  │
│ 2.4935    ┆ 3.3983    ┆ 1.6631    ┆ 6.1765    ┆ … ┆ 4.8873    ┆ 4.6748    ┆ 6.9578    ┆ 2.1772   │
│ 0.0       ┆ 0.0       ┆ 0.4449    ┆ 0.0       ┆ … ┆ 0.0       ┆ 1.4776    ┆ 0.0       ┆ 0.8114   │
│ 11.7868   ┆ 11.3219   ┆ 11.8779   ┆ 11.502    ┆ … ┆ 12.6904   ┆ 12.3403   ┆ 11.8271   ┆ 12.2783  │
│ 11.0131   ┆ 11.2617   ┆ 11.8526   ┆ 11.4405   ┆ … ┆ 11.5409   ┆ 10.4812   ┆ 11.8211   ┆ 10.791   │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 12.6757   ┆ 12.6287   ┆ 13.9112   ┆ 12.3596   ┆ … ┆ 12.4708   ┆ 12.493    ┆ 12.9017   ┆ 12.2984  │
│ 8.9559    ┆ 8.053     ┆ 7.5385    ┆ 7.4431    ┆ … ┆ 9.481     ┆ 7.374     ┆ 8.7661    ┆ 8.3132   │
│ 10.7473   ┆ 11.0453   ┆ 11.3402   ┆ 10.7773   ┆ … ┆ 11.011    ┆ 12.6251   ┆ 9.9638    ┆ 12.172   │
│ 8.7529    ┆ 7.8723    ┆ 4.7356    ┆ 7.6359    ┆ … ┆ 9.7613    ┆ 7.4161    ┆ 7.1316    ┆ 6.9635   │
│ 10.5299   ┆ 9.8006    ┆ 9.6643    ┆ 10.6673   ┆ … ┆ 10.8004   ┆ 10.7302   ┆ 9.9003    ┆ 9.3752   │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [48]:
# labels and rna columns are aligned, do train, val, test split

# random split for train / test
train_temp_idx, test_idx = train_test_split(
    np.arange(rna.shape[1]),
    test_size=0.3,
    # stratify=y,
    random_state=4
)

In [57]:
train_idx, val_idx = train_test_split(
    train_temp_idx, 
    test_size=0.1, 
    stratify=y_all_e[train_temp_idx],                   
    random_state=4
)

In [34]:
label_encoder = LabelEncoder()
label_encoder.fit(y_all)
y_all_e = label_encoder.transform(y_all)

# add numberd labels to labels df
labels = labels.with_columns(y=y_all_e)

In [138]:
# split dataframes
train_df = rna[:, train_idx.tolist()]
train_labels = labels[train_idx]
val_df = rna[:, val_idx.tolist()]
val_labels = labels[val_idx]
test_df = rna[:, test_idx.tolist()]
test_labels = labels[test_idx]

In [147]:
# select features based on the training set
genes_class_mean = np.zeros((rna.shape[0], 4))

# separate training samples by class

for label in range(4):
    # select cols which are from this class
    label_samples = train_labels.filter(pl.col("y") == label)["sampleID"].to_numpy()
    label_train_df = train_df[label_samples].to_numpy()

    genes_class_mean[:, label] = label_train_df.mean(axis=1)

In [213]:
genes_class_variance = genes_class_mean.var(axis=1)

class_var_order = np.argsort(genes_class_variance)

# select the 500 genes with the largest variance
best_500 = class_var_order >= (genes_class_variance.shape[0] - 500)
best_500_idx = np.where(best_500)[0]

# selection itself
train_df = train_df[best_500_idx]
val_df = val_df[best_500_idx]
test_df = test_df[best_500_idx]

In [256]:
def min_max_scale(X):
    return (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))

In [259]:
X_train = train_df.to_numpy().T
y_train = train_labels["y"].to_numpy()
X_val = val_df.to_numpy().T
y_val = val_labels["y"].to_numpy()
X_test = test_df.to_numpy().T
y_test = test_labels["y"].to_numpy()

# scale everything to [0,1]
# X_train = min_max_scale(X_train)
# X_val = min_max_scale(X_val)
# X_test = min_max_scale(X_test)

In [260]:
# Example data
data = np.array(
    [[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]]
)

# Fit the scaler to the data and transform the data
scaled_data = (data - data.min(axis=0)) / (data.max(axis=0) - data.min(axis=0))

print("Original data:")
print(data)
print("\nScaled data:")
print(scaled_data)

Original data:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Scaled data:
[[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]

In [261]:
C_range: tuple = (1e-3, 1e3)
gamma_range: tuple = (1e-3, 1e3)

# eval on rbf svms
def objective(trial):

    svm = SVC(
        C=trial.suggest_float("C", C_range[0], C_range[1], log=True),
        gamma=trial.suggest_float(
            "gamma", gamma_range[0], gamma_range[1], log=True
        ),
        class_weight=trial.suggest_categorical("class_weight", ["balanced", None]),
        kernel="rbf",
    )

    svm.fit(X_train, y_train)
    
    y_pred = svm.predict(X_val)

    f1 = f1_score(y_val, y_pred, average="weighted")

    return f1

study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=200)

# print the mean f1 score for the best performing parameter
# print(
#     f"| RBF SVM | {best_results['acc']:.4f} +/- {best_results['acc_std']:.4f} | {best_results['f1_macro']:.4f} +/- {best_results['f1_macro_std']:.4f} | {best_results['f1_weighted']:.4f} +/- {best_results['f1_weighted_std']:.4f} |"
# )
print(f"study {study.best_value=}, {study.best_params=}")

[I 2024-03-14 02:06:08,381] A new study created in memory with name: no-name-bd4c351b-9478-4d09-b936-35bc0dca5928
[I 2024-03-14 02:06:08,418] Trial 0 finished with value: 0.2450980392156863 and parameters: {'C': 0.10927203746599043, 'gamma': 0.007756868910293816, 'class_weight': None}. Best is trial 0 with value: 0.2450980392156863.
[I 2024-03-14 02:06:08,444] Trial 1 finished with value: 0.2450980392156863 and parameters: {'C': 30.560501464987727, 'gamma': 0.3212980953801838, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.2450980392156863.
[I 2024-03-14 02:06:08,480] Trial 2 finished with value: 0.2450980392156863 and parameters: {'C': 25.157108697794, 'gamma': 285.62341300943655, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.2450980392156863.
[I 2024-03-14 02:06:08,504] Trial 3 finished with value: 0.2450980392156863 and parameters: {'C': 0.013582147420590333, 'gamma': 0.11336990558388652, 'class_weight': None}. Best is trial 0 with value: 0.2450980392156863.
[I 2024-03-14 02:06:08,529] Trial 4 finished with value: 0.2450980392156863 and parameters: {'C': 0.018410516421330347, 'gamma': 21.691309264429677, 'class_weight': None}. Best is trial 0 with value: 0.2450980392156863.
[I 2024-03-14 02:06:08,559] Trial 5 finished with value: 0.2450980392156863 and parameters: {'C': 15.91739593901471, 'gamma': 0.8164093892770174, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.2450980392156863.
[I 2024-03-14 02:06:08,586] Trial 6 finished with value: 0.2450980392156863 and parameters: {'C': 4.134952341703694, 'gamma': 48.87984453218208, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.2450980392156863.
[I 2024-03-14 02:06:08,611] Trial 7 finished with value: 0.1 and parameters: {'C': 0.40480447089292143, 'gamma': 416.0712059529905, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.2450980392156863.
[I 2024-03-14 02:06:08,633] Trial 8 finished with value: 0.2450980392156863 and parameters: {'C': 0.03209207906403592, 'gamma': 0.01339174681649804, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.2450980392156863.
[I 2024-03-14 02:06:08,654] Trial 9 finished with value: 0.2450980392156863 and parameters: {'C': 0.002765309777486203, 'gamma': 0.026212339597719334, 'class_weight': None}. Best is trial 0 with value: 0.2450980392156863.
[I 2024-03-14 02:06:08,685] Trial 10 finished with value: 0.8154605263157895 and parameters: {'C': 625.9627475532155, 'gamma': 0.0013015100299730257, 'class_weight': None}. Best is trial 10 with value: 0.8154605263157895.
[I 2024-03-14 02:06:08,714] Trial 11 finished with value: 0.855324074074074 and parameters: {'C': 717.4231527320792, 'gamma': 0.0011447301012535206, 'class_weight': None}. Best is trial 11 with value: 0.855324074074074.
[I 2024-03-14 02:06:08,742] Trial 12 finished with value: 0.855324074074074 and parameters: {'C': 789.237521220557, 'gamma': 0.0011440518277481724, 'class_weight': None}. Best is trial 11 with value: 0.855324074074074.
[I 2024-03-14 02:06:08,774] Trial 13 finished with value: 0.7868686868686869 and parameters: {'C': 580.6003938975067, 'gamma': 0.0021372850478757082, 'class_weight': None}. Best is trial 11 with value: 0.855324074074074.
[I 2024-03-14 02:06:08,809] Trial 14 finished with value: 0.2450980392156863 and parameters: {'C': 167.02490256943534, 'gamma': 5.042070405478401, 'class_weight': None}. Best is trial 11 with value: 0.855324074074074.
[I 2024-03-14 02:06:08,843] Trial 15 finished with value: 0.2450980392156863 and parameters: {'C': 110.70723190861699, 'gamma': 0.06319124850180195, 'class_weight': None}. Best is trial 11 with value: 0.855324074074074.
[I 2024-03-14 02:06:08,872] Trial 16 finished with value: 0.8568509086335911 and parameters: {'C': 1.7013529668600047, 'gamma': 0.0011496057125927113, 'class_weight': None}. Best is trial 16 with value: 0.8568509086335911.
[I 2024-03-14 02:06:08,905] Trial 17 finished with value: 0.6196581196581197 and parameters: {'C': 1.3851198902931978, 'gamma': 0.005252748434085284, 'class_weight': None}. Best is trial 16 with value: 0.8568509086335911.
[I 2024-03-14 02:06:08,939] Trial 18 finished with value: 0.2450980392156863 and parameters: {'C': 4.2034440185175646, 'gamma': 0.03401105889486884, 'class_weight': None}. Best is trial 16 with value: 0.8568509086335911.
[I 2024-03-14 02:06:08,973] Trial 19 finished with value: 0.2450980392156863 and parameters: {'C': 0.0010816082700207106, 'gamma': 3.924485348890317, 'class_weight': None}. Best is trial 16 with value: 0.8568509086335911.
[I 2024-03-14 02:06:09,006] Trial 20 finished with value: 0.2450980392156863 and parameters: {'C': 0.3069459808822873, 'gamma': 0.005132185177435806, 'class_weight': None}. Best is trial 16 with value: 0.8568509086335911.
[I 2024-03-14 02:06:09,038] Trial 21 finished with value: 0.7868686868686869 and parameters: {'C': 961.5769795678592, 'gamma': 0.002330096743065005, 'class_weight': None}. Best is trial 16 with value: 0.8568509086335911.
[I 2024-03-14 02:06:09,070] Trial 22 finished with value: 0.8154605263157895 and parameters: {'C': 106.01834147438674, 'gamma': 0.0013279390077860305, 'class_weight': None}. Best is trial 16 with value: 0.8568509086335911.
[I 2024-03-14 02:06:09,104] Trial 23 finished with value: 0.2450980392156863 and parameters: {'C': 228.5211926119083, 'gamma': 0.012042043311992583, 'class_weight': None}. Best is trial 16 with value: 0.8568509086335911.
[I 2024-03-14 02:06:09,134] Trial 24 finished with value: 0.855324074074074 and parameters: {'C': 5.502673463355647, 'gamma': 0.0011371240267940763, 'class_weight': None}. Best is trial 16 with value: 0.8568509086335911.
[I 2024-03-14 02:06:09,170] Trial 25 finished with value: 0.2450980392156863 and parameters: {'C': 60.04911393385711, 'gamma': 0.159665048569236, 'class_weight': None}. Best is trial 16 with value: 0.8568509086335911.
[I 2024-03-14 02:06:09,203] Trial 26 finished with value: 0.7015745692216281 and parameters: {'C': 335.78976027595155, 'gamma': 0.004137965262726057, 'class_weight': None}. Best is trial 16 with value: 0.8568509086335911.
[I 2024-03-14 02:06:09,238] Trial 27 finished with value: 0.2450980392156863 and parameters: {'C': 11.302061355204975, 'gamma': 0.025854839720811092, 'class_weight': None}. Best is trial 16 with value: 0.8568509086335911.
[I 2024-03-14 02:06:09,271] Trial 28 finished with value: 0.7868686868686869 and parameters: {'C': 51.62804203956492, 'gamma': 0.0028690041009551146, 'class_weight': None}. Best is trial 16 with value: 0.8568509086335911.
[I 2024-03-14 02:06:09,306] Trial 29 finished with value: 0.2450980392156863 and parameters: {'C': 1.493410753859329, 'gamma': 0.01073247931235992, 'class_weight': None}. Best is trial 16 with value: 0.8568509086335911.
[I 2024-03-14 02:06:09,340] Trial 30 finished with value: 0.2450980392156863 and parameters: {'C': 0.04808912526586481, 'gamma': 0.007775288836995814, 'class_weight': None}. Best is trial 16 with value: 0.8568509086335911.
[I 2024-03-14 02:06:09,372] Trial 31 finished with value: 0.8154605263157895 and parameters: {'C': 5.585459921411776, 'gamma': 0.0011970250515236003, 'class_weight': None}. Best is trial 16 with value: 0.8568509086335911.
[I 2024-03-14 02:06:09,401] Trial 32 finished with value: 0.8275462962962963 and parameters: {'C': 0.7214656443668286, 'gamma': 0.0010725908498672846, 'class_weight': None}. Best is trial 16 with value: 0.8568509086335911.
[I 2024-03-14 02:06:09,434] Trial 33 finished with value: 0.38162878787878785 and parameters: {'C': 0.18082573323733428, 'gamma': 0.003109685815820701, 'class_weight': None}. Best is trial 16 with value: 0.8568509086335911.
[I 2024-03-14 02:06:09,465] Trial 34 finished with value: 0.855324074074074 and parameters: {'C': 38.707527915169806, 'gamma': 0.0010337955770242523, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8568509086335911.
[I 2024-03-14 02:06:09,500] Trial 35 finished with value: 0.2450980392156863 and parameters: {'C': 9.436483009920156, 'gamma': 0.24411044737985557, 'class_weight': None}. Best is trial 16 with value: 0.8568509086335911.
[I 2024-03-14 02:06:09,534] Trial 36 finished with value: 0.2450980392156863 and parameters: {'C': 1.9670587321089148, 'gamma': 0.016313768543317095, 'class_weight': None}. Best is trial 16 with value: 0.8568509086335911.
[I 2024-03-14 02:06:09,568] Trial 37 finished with value: 0.2450980392156863 and parameters: {'C': 0.10148479627131889, 'gamma': 0.06241085894568421, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8568509086335911.
[I 2024-03-14 02:06:09,605] Trial 38 finished with value: 0.2450980392156863 and parameters: {'C': 266.544185382116, 'gamma': 938.5730530422319, 'class_weight': None}. Best is trial 16 with value: 0.8568509086335911.
[I 2024-03-14 02:06:09,639] Trial 39 finished with value: 0.5504810004810006 and parameters: {'C': 28.666124469850793, 'gamma': 0.005651925734658103, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8568509086335911.
[I 2024-03-14 02:06:09,677] Trial 40 finished with value: 0.2450980392156863 and parameters: {'C': 966.049592571249, 'gamma': 0.7382647184501654, 'class_weight': None}. Best is trial 16 with value: 0.8568509086335911.
[I 2024-03-14 02:06:09,708] Trial 41 finished with value: 0.855324074074074 and parameters: {'C': 19.63731381870299, 'gamma': 0.0010204398623899972, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8568509086335911.
[I 2024-03-14 02:06:09,741] Trial 42 finished with value: 0.7868686868686869 and parameters: {'C': 50.4954246311431, 'gamma': 0.0020750804849022065, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8568509086335911.
[I 2024-03-14 02:06:09,774] Trial 43 finished with value: 0.7868686868686869 and parameters: {'C': 2.6828337833427227, 'gamma': 0.0023276139698014016, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8568509086335911.
[I 2024-03-14 02:06:09,809] Trial 44 finished with value: 0.6789819376026274 and parameters: {'C': 0.71101549956402, 'gamma': 0.007003131208411899, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8568509086335911.
[I 2024-03-14 02:06:09,847] Trial 45 finished with value: 0.2450980392156863 and parameters: {'C': 409.4085710532065, 'gamma': 124.95333133932648, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8568509086335911.
[I 2024-03-14 02:06:09,880] Trial 46 finished with value: 0.7868686868686869 and parameters: {'C': 7.352708892232178, 'gamma': 0.001987719575073946, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8568509086335911.
[I 2024-03-14 02:06:09,915] Trial 47 finished with value: 0.7015745692216281 and parameters: {'C': 15.623722665336208, 'gamma': 0.004108304845727348, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8568509086335911.
[I 2024-03-14 02:06:09,952] Trial 48 finished with value: 0.2450980392156863 and parameters: {'C': 107.33815745970753, 'gamma': 15.729137743718344, 'class_weight': None}. Best is trial 16 with value: 0.8568509086335911.
[I 2024-03-14 02:06:09,982] Trial 49 finished with value: 0.855324074074074 and parameters: {'C': 3.5841490440854327, 'gamma': 0.0010422989451152067, 'class_weight': None}. Best is trial 16 with value: 0.8568509086335911.
[I 2024-03-14 02:06:10,018] Trial 50 finished with value: 0.2450980392156863 and parameters: {'C': 515.548623190574, 'gamma': 0.022737265986985885, 'class_weight': None}. Best is trial 16 with value: 0.8568509086335911.
[I 2024-03-14 02:06:10,049] Trial 51 finished with value: 0.855324074074074 and parameters: {'C': 30.405063439864062, 'gamma': 0.0010101583517818807, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8568509086335911.
[I 2024-03-14 02:06:10,082] Trial 52 finished with value: 0.7868686868686869 and parameters: {'C': 19.66653140267554, 'gamma': 0.0018016868771719504, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8568509086335911.
[I 2024-03-14 02:06:10,117] Trial 53 finished with value: 0.7868686868686869 and parameters: {'C': 57.75657444815284, 'gamma': 0.0032155999551219863, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8568509086335911.
[I 2024-03-14 02:06:10,152] Trial 54 finished with value: 0.2450980392156863 and parameters: {'C': 134.95085040593838, 'gamma': 0.0092505948245936, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8568509086335911.
[I 2024-03-14 02:06:10,183] Trial 55 finished with value: 0.8603357051632914 and parameters: {'C': 0.8326110670778948, 'gamma': 0.0016280891775566403, 'class_weight': 'balanced'}. Best is trial 55 with value: 0.8603357051632914.
[I 2024-03-14 02:06:10,218] Trial 56 finished with value: 0.2450980392156863 and parameters: {'C': 0.4597105705409837, 'gamma': 0.05383339411480748, 'class_weight': 'balanced'}. Best is trial 55 with value: 0.8603357051632914.
[I 2024-03-14 02:06:10,251] Trial 57 finished with value: 0.7868686868686869 and parameters: {'C': 2.9428768509029144, 'gamma': 0.001749113523683462, 'class_weight': None}. Best is trial 55 with value: 0.8603357051632914.
[I 2024-03-14 02:06:10,285] Trial 58 finished with value: 0.2450980392156863 and parameters: {'C': 0.2632465755517073, 'gamma': 0.004037811590984286, 'class_weight': None}. Best is trial 55 with value: 0.8603357051632914.
[I 2024-03-14 02:06:10,319] Trial 59 finished with value: 0.2993827160493827 and parameters: {'C': 0.9370237861191697, 'gamma': 0.006550810558318491, 'class_weight': None}. Best is trial 55 with value: 0.8603357051632914.
[I 2024-03-14 02:06:10,356] Trial 60 finished with value: 0.2450980392156863 and parameters: {'C': 5.814871085870737, 'gamma': 0.014760324292988878, 'class_weight': 'balanced'}. Best is trial 55 with value: 0.8603357051632914.
[I 2024-03-14 02:06:10,389] Trial 61 finished with value: 0.8154605263157895 and parameters: {'C': 1.721395561505615, 'gamma': 0.0017958415034839796, 'class_weight': 'balanced'}. Best is trial 55 with value: 0.8603357051632914.
[I 2024-03-14 02:06:10,423] Trial 62 finished with value: 0.8154605263157895 and parameters: {'C': 13.614738458368024, 'gamma': 0.001429199907697477, 'class_weight': 'balanced'}. Best is trial 55 with value: 0.8603357051632914.
[I 2024-03-14 02:06:10,458] Trial 63 finished with value: 0.7541889483065954 and parameters: {'C': 670.5692585797575, 'gamma': 0.003509804113568657, 'class_weight': 'balanced'}. Best is trial 55 with value: 0.8603357051632914.
[I 2024-03-14 02:06:10,491] Trial 64 finished with value: 0.855324074074074 and parameters: {'C': 4.519663020272127, 'gamma': 0.001028101643838896, 'class_weight': 'balanced'}. Best is trial 55 with value: 0.8603357051632914.
[I 2024-03-14 02:06:10,526] Trial 65 finished with value: 0.7868686868686869 and parameters: {'C': 178.90342049029292, 'gamma': 0.0027909217401202733, 'class_weight': None}. Best is trial 55 with value: 0.8603357051632914.
[I 2024-03-14 02:06:10,560] Trial 66 finished with value: 0.7868686868686869 and parameters: {'C': 71.49096368750754, 'gamma': 0.0017735393719881646, 'class_weight': None}. Best is trial 55 with value: 0.8603357051632914.
[I 2024-03-14 02:06:10,598] Trial 67 finished with value: 0.1 and parameters: {'C': 0.45705103206119385, 'gamma': 3.531679269275306, 'class_weight': 'balanced'}. Best is trial 55 with value: 0.8603357051632914.
[I 2024-03-14 02:06:10,633] Trial 68 finished with value: 0.5725548164572555 and parameters: {'C': 1.0177256350686499, 'gamma': 0.005070777811040993, 'class_weight': None}. Best is trial 55 with value: 0.8603357051632914.
[I 2024-03-14 02:06:10,667] Trial 69 finished with value: 0.7868686868686869 and parameters: {'C': 8.266170568136825, 'gamma': 0.0027203577546292173, 'class_weight': None}. Best is trial 55 with value: 0.8603357051632914.
[I 2024-03-14 02:06:10,700] Trial 70 finished with value: 0.8154605263157895 and parameters: {'C': 37.84278118184193, 'gamma': 0.0014106243561340626, 'class_weight': 'balanced'}. Best is trial 55 with value: 0.8603357051632914.
[I 2024-03-14 02:06:10,732] Trial 71 finished with value: 0.8154605263157895 and parameters: {'C': 2.9835288687790453, 'gamma': 0.0011215002674168234, 'class_weight': None}. Best is trial 55 with value: 0.8603357051632914.
[I 2024-03-14 02:06:10,764] Trial 72 finished with value: 0.8154605263157895 and parameters: {'C': 2.305664387684795, 'gamma': 0.001025474977374895, 'class_weight': None}. Best is trial 55 with value: 0.8603357051632914.
[I 2024-03-14 02:06:10,799] Trial 73 finished with value: 0.7868686868686869 and parameters: {'C': 21.055047544834313, 'gamma': 0.0027024102803460573, 'class_weight': None}. Best is trial 55 with value: 0.8603357051632914.
[I 2024-03-14 02:06:10,833] Trial 74 finished with value: 0.8154605263157895 and parameters: {'C': 4.073952674748078, 'gamma': 0.001493771695473892, 'class_weight': None}. Best is trial 55 with value: 0.8603357051632914.
[I 2024-03-14 02:06:10,866] Trial 75 finished with value: 0.2450980392156863 and parameters: {'C': 0.007798107501927845, 'gamma': 0.0046603466574923, 'class_weight': None}. Best is trial 55 with value: 0.8603357051632914.
[I 2024-03-14 02:06:10,902] Trial 76 finished with value: 0.2450980392156863 and parameters: {'C': 1.1845911313924, 'gamma': 0.007839052245495234, 'class_weight': None}. Best is trial 55 with value: 0.8603357051632914.
[I 2024-03-14 02:06:10,936] Trial 77 finished with value: 0.7868686868686869 and parameters: {'C': 306.4824866027806, 'gamma': 0.002178766534501561, 'class_weight': None}. Best is trial 55 with value: 0.8603357051632914.
[I 2024-03-14 02:06:10,970] Trial 78 finished with value: 0.8154605263157895 and parameters: {'C': 10.319555276261971, 'gamma': 0.0015158696666578864, 'class_weight': None}. Best is trial 55 with value: 0.8603357051632914.
[I 2024-03-14 02:06:11,005] Trial 79 finished with value: 0.9128808611567233 and parameters: {'C': 0.13263430174534643, 'gamma': 0.0010014274339660567, 'class_weight': 'balanced'}. Best is trial 79 with value: 0.9128808611567233.
[I 2024-03-14 02:06:11,043] Trial 80 finished with value: 0.2450980392156863 and parameters: {'C': 0.06515555011923517, 'gamma': 1.6956667694344139, 'class_weight': 'balanced'}. Best is trial 79 with value: 0.9128808611567233.
[I 2024-03-14 02:06:11,078] Trial 81 finished with value: 0.8623188405797102 and parameters: {'C': 0.1536278064334579, 'gamma': 0.0013816045468835472, 'class_weight': 'balanced'}. Best is trial 79 with value: 0.9128808611567233.
[I 2024-03-14 02:06:11,114] Trial 82 finished with value: 0.3993055555555556 and parameters: {'C': 0.15495484758314043, 'gamma': 0.0031434695570574022, 'class_weight': 'balanced'}. Best is trial 79 with value: 0.9128808611567233.
[I 2024-03-14 02:06:11,149] Trial 83 finished with value: 0.2450980392156863 and parameters: {'C': 0.018144993423414545, 'gamma': 0.0022499471073884813, 'class_weight': 'balanced'}. Best is trial 79 with value: 0.9128808611567233.
[I 2024-03-14 02:06:11,185] Trial 84 finished with value: 0.2450980392156863 and parameters: {'C': 0.03327736772974425, 'gamma': 0.0014808620329664851, 'class_weight': 'balanced'}. Best is trial 79 with value: 0.9128808611567233.
[I 2024-03-14 02:06:11,221] Trial 85 finished with value: 0.2450980392156863 and parameters: {'C': 0.08272635650204369, 'gamma': 0.005598857252772153, 'class_weight': 'balanced'}. Best is trial 79 with value: 0.9128808611567233.
[I 2024-03-14 02:06:11,257] Trial 86 finished with value: 0.29444444444444445 and parameters: {'C': 0.15384663025293305, 'gamma': 0.004089089632026021, 'class_weight': 'balanced'}. Best is trial 79 with value: 0.9128808611567233.
[I 2024-03-14 02:06:11,294] Trial 87 finished with value: 0.1 and parameters: {'C': 0.307309912588991, 'gamma': 0.5015974897283727, 'class_weight': 'balanced'}. Best is trial 79 with value: 0.9128808611567233.
[I 2024-03-14 02:06:11,329] Trial 88 finished with value: 0.8354129530600118 and parameters: {'C': 0.20888476482366475, 'gamma': 0.002085962173954905, 'class_weight': 'balanced'}. Best is trial 79 with value: 0.9128808611567233.

study study.best_value=0.9128808611567233, study.best_params={'C': 0.13263430174534643, 'gamma': 0.0010014274339660567, 'class_weight': 'balanced'}

In [268]:
# fit model with best params and test on test set
svm = SVC(
        C=0.13263430174534643,
        gamma=0.0010014274339660567,
        class_weight="balanced",
        kernel="rbf",
)

svm.fit(X_train, y_train)

y_pred = svm.predict(X_test)

f1 = f1_score(y_test, y_pred, average="weighted")

print(f1)

0.795370962228466

## SVMs with rbf kernel
- weighted f1 score with ~0.8 on test set

In [ ]:
# build mogonet style GNN with
# a. thresholded cosine similarity

In [269]:
def cosine_similarity_matrix(matrix):
    # Compute dot product between all pairs of vectors
    dot_products = np.dot(matrix, matrix.T)
    
    # Compute magnitudes of all vectors
    magnitudes = np.linalg.norm(matrix, axis=1)
    
    # Compute outer product of magnitudes to obtain matrix of magnitudes product
    magnitude_products = np.outer(magnitudes, magnitudes)
    
    # Compute cosine similarity matrix
    cosine_similarities = dot_products / magnitude_products
    
    return cosine_similarities

# Example matrix of vectors (rows represent vectors)
matrix = np.array([[1, 1, 1],
                   [2, 2, 2],
                   [1, -1, 1]])

# Compute cosine similarity between all vectors
cos_sim_matrix = cosine_similarity_matrix(matrix)

print("Cosine similarity matrix:")
print(cos_sim_matrix)

Cosine similarity matrix:
[[1.         1.         0.33333333]
 [1.         1.         0.33333333]
 [0.33333333 0.33333333 1.        ]]

In [ ]:
cosine_similarity_matrix()

In [ ]:
# b. moglam style cosine similarity + learned graph

In [ ]:
# build bipartite graph style GNN

In [ ]:
# a. w interactions

In [ ]:
# b. w/o interactions

In [ ]:
# eval mogonet style model

In [ ]:
# eval bipartite style model