# Bipartite graph scratch

In [3]:
import numpy as np
import polars as pl
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
import optuna
from sklearn.metrics import accuracy_score, f1_score
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.svm import SVC, LinearSVC
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt

In [7]:
rna = pl.read_csv("xena_brca_data/TCGA.BRCA.sampleMap_HiSeqV2", separator="\t")

In [8]:
gene_names = rna[:,0]
rna = rna.drop("sample")

In [9]:
# load labels

clinicalMatrix = pl.read_csv("xena_brca_data/TCGA.BRCA.sampleMap_BRCA_clinicalMatrix", separator="\t", infer_schema_length=0)

cM = clinicalMatrix.filter(pl.col("PAM50_mRNA_nature2012") != "null")
cM

shape: (522, 194)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sampleID  ┆ AJCC_Stag ┆ Age_at_In ┆ CN_Cluste ┆ … ┆ _GENOMIC_ ┆ _GENOMIC_ ┆ _GENOMIC_ ┆ _GENOMIC │
│ ---       ┆ e_nature2 ┆ itial_Pat ┆ rs_nature ┆   ┆ ID_TCGA_B ┆ ID_TCGA_B ┆ ID_TCGA_B ┆ _ID_TCGA │
│ str       ┆ 012       ┆ hologic_D ┆ 2012      ┆   ┆ RCA_G4502 ┆ RCA_exp_H ┆ RCA_gisti ┆ _BRCA_PD │
│           ┆ ---       ┆ iagno…    ┆ ---       ┆   ┆ A_07_…    ┆ iSeqV…    ┆ c2        ┆ Marray   │
│           ┆ str       ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆           ┆   ┆ str       ┆ str       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ TCGA-A1-A ┆ Stage IIA ┆ 59        ┆ 2         ┆ … ┆ TCGA-A1-A ┆ 15bad71d- ┆ TCGA-A1-A ┆ TCGA-A1- │
│ 0SD-01    ┆           ┆           ┆           ┆   ┆ 0SD-01A-1 ┆ 3031-413b ┆ 0SD-01A-1 ┆ A0SD-01  │
│           ┆           ┆           ┆           ┆   ┆ 1R-A115-0 ┆ -9e8d-642 ┆ 1D-A111-0 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆ 6ae5d…    ┆ 1         ┆          │
│ TCGA-A1-A ┆ Stage I   ┆ 56        ┆ 2         ┆ … ┆ TCGA-A1-A ┆ a998e0ce- ┆ TCGA-A1-A ┆ TCGA-A1- │
│ 0SE-01    ┆           ┆           ┆           ┆   ┆ 0SE-01A-1 ┆ 9248-460f ┆ 0SE-01A-1 ┆ A0SE-01  │
│           ┆           ┆           ┆           ┆   ┆ 1R-A084-0 ┆ -aabc-2da ┆ 1D-A087-0 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆ d452a…    ┆ 1         ┆          │
│ TCGA-A1-A ┆ Stage IIA ┆ 39        ┆ 5         ┆ … ┆ TCGA-A1-A ┆ dce3de3e- ┆ TCGA-A1-A ┆ TCGA-A1- │
│ 0SH-01    ┆           ┆           ┆           ┆   ┆ 0SH-01A-1 ┆ f851-4859 ┆ 0SH-01A-1 ┆ A0SH-01  │
│           ┆           ┆           ┆           ┆   ┆ 1R-A084-0 ┆ -a208-72e ┆ 1D-A087-0 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆ 65d36…    ┆ 1         ┆          │
│ TCGA-A1-A ┆ Stage     ┆ 39        ┆ 3         ┆ … ┆ TCGA-A1-A ┆ 61017170- ┆ TCGA-A1-A ┆ TCGA-A1- │
│ 0SJ-01    ┆ IIIA      ┆           ┆           ┆   ┆ 0SJ-01A-1 ┆ a36a-4ce9 ┆ 0SJ-01A-1 ┆ A0SJ-01  │
│           ┆           ┆           ┆           ┆   ┆ 1R-A084-0 ┆ -9b8e-324 ┆ 1D-A087-0 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆ 755b8…    ┆ 1         ┆          │
│ TCGA-A1-A ┆ Stage IIA ┆ 54        ┆ 1         ┆ … ┆ TCGA-A1-A ┆ a63583ca- ┆ TCGA-A1-A ┆ TCGA-A1- │
│ 0SK-01    ┆           ┆           ┆           ┆   ┆ 0SK-01A-1 ┆ 0ef2-4417 ┆ 0SK-01A-1 ┆ A0SK-01  │
│           ┆           ┆           ┆           ┆   ┆ 2R-A084-0 ┆ -b435-5f3 ┆ 2D-A087-0 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆ a6951…    ┆ 1         ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ TCGA-E2-A ┆ Stage     ┆ 74        ┆ 2         ┆ … ┆ TCGA-E2-A ┆ 2d51ae30- ┆ TCGA-E2-A ┆ TCGA-E2- │
│ 1B4-01    ┆ IIIA      ┆           ┆           ┆   ┆ 1B4-01A-1 ┆ 4c8a-4c99 ┆ 1B4-01A-1 ┆ A1B4-01  │
│           ┆           ┆           ┆           ┆   ┆ 1R-A12P-0 ┆ -b216-fc4 ┆ 1D-A12N-0 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆ fbda0…    ┆ 1         ┆          │
│ TCGA-E2-A ┆ Stage IIA ┆ 46        ┆ 3         ┆ … ┆ TCGA-E2-A ┆ a2c80f8e- ┆ TCGA-E2-A ┆ TCGA-E2- │
│ 1B5-01    ┆           ┆           ┆           ┆   ┆ 1B5-01A-2 ┆ f08d-4574 ┆ 1B5-01A-2 ┆ A1B5-01  │
│           ┆           ┆           ┆           ┆   ┆ 1R-A12P-0 ┆ -90a0-f06 ┆ 1D-A12N-0 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆ 51c0a…    ┆ 1         ┆          │
│ TCGA-E2-A ┆ Stage IIA ┆ 44        ┆ 1         ┆ … ┆ TCGA-E2-A ┆ eb398b00- ┆ TCGA-E2-A ┆ TCGA-E2- │
│ 1B6-01    ┆           ┆           ┆           ┆   ┆ 1B6-01A-3 ┆ 8669-4c22 ┆ 1B6-01A-3 ┆ A1B6-01  │
│           ┆           ┆           ┆           ┆   ┆ 1R-A12P-0 ┆ -8285-03c ┆ 1D-A12N-0 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆ df764…    ┆ 1         ┆          │
│ TCGA-E2-A ┆ Stage IA  ┆ 63        ┆ 2         ┆ … ┆ TCGA-E2-A ┆ a2cf164c- ┆ TCGA-E2-A ┆ TCGA-E2- │
│ 1BC-01    ┆           ┆           ┆           ┆   ┆ 1BC-01A-1 ┆ 5b26-43eb ┆ 1BC-01A-1 ┆ A1BC-01  │
│           ┆           ┆           ┆           ┆   ┆ 1R-A12P-0 ┆ -9de9-d1d ┆ 1D-A12N-0 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆ 457a5…    ┆ 1         ┆          │
│ TCGA-E2-A ┆ Stage IIA ┆ 53        ┆ 2         ┆ … ┆ TCGA-E2-A ┆ fa1917b0- ┆ TCGA-E2-A ┆ TCGA-E2- │
│ 1BD-01    ┆           ┆           ┆           ┆   ┆ 1BD-01A-1 ┆ c3e1-412d ┆ 1BD-01A-1 ┆ A1BD-01  │
│           ┆           ┆           ┆           ┆   ┆ 1R-A12P-0 ┆ -b063-e74 ┆ 1D-A12N-0 ┆          │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆ b5caf…    ┆ 1         ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [10]:
labels = cM.select(["sampleID","PAM50_mRNA_nature2012"])
labels = labels.filter(pl.col("PAM50_mRNA_nature2012") != "Normal-like")

In [11]:
y_all = labels["PAM50_mRNA_nature2012"].to_numpy()
y_all

array(['Luminal A', 'Luminal A', 'Luminal A', 'Luminal A', 'Basal-like',
       'Luminal B', 'Basal-like', 'Luminal A', 'Basal-like', 'Basal-like',
       'Luminal B', 'Basal-like', 'Basal-like', 'Luminal A',
       'HER2-enriched', 'HER2-enriched', 'Luminal A', 'HER2-enriched',
       'Basal-like', 'Luminal A', 'Luminal A', 'Luminal A', 'Luminal B',
       'Luminal A', 'Luminal A', 'Luminal B', 'HER2-enriched',
       'HER2-enriched', 'Luminal A', 'Basal-like', 'HER2-enriched',
       'Basal-like', 'Luminal A', 'Luminal B', 'Luminal A', 'Luminal A',
       'Luminal A', 'HER2-enriched', 'Luminal B', 'Luminal A',
       'Luminal A', 'Luminal A', 'Luminal A', 'Luminal A', 'Luminal A',
       'Luminal B', 'Basal-like', 'Luminal A', 'Luminal B', 'Luminal B',
       'Basal-like', 'Luminal A', 'Basal-like', 'HER2-enriched',
       'Basal-like', 'Luminal B', 'Luminal B', 'Luminal A', 'Luminal A',
       'Luminal A', 'Luminal A', 'Luminal A', 'Basal-like', 'Luminal A',
       'Luminal B', 'Luminal B', 'Luminal A', 'Basal-like', 'Luminal A',
       'Basal-like', 'Luminal A', 'Basal-like', 'Luminal A', 'Luminal A',
       'Luminal B', 'Luminal A', 'Basal-like', 'Luminal A', 'Basal-like',
       'Basal-like', 'Luminal B', 'Luminal B', 'Luminal B', 'Luminal A',
       'Luminal B', 'Luminal B', 'Luminal A', 'Luminal A', 'Luminal B',
       'Luminal A', 'Luminal B', 'HER2-enriched', 'HER2-enriched',
       'Luminal B', 'HER2-enriched', 'Basal-like', 'Luminal A',
       'Luminal A', 'Luminal A', 'HER2-enriched', 'Luminal A',
       'Luminal B', 'Basal-like', 'Luminal A', 'Basal-like', 'Luminal B',
       'Basal-like', 'Luminal B', 'Luminal B', 'HER2-enriched',
       'Luminal B', 'Luminal A', 'Luminal B', 'Luminal B', 'Luminal A',
       'Luminal A', 'HER2-enriched', 'Luminal A', 'Luminal B',
       'Luminal B', 'Basal-like', 'Luminal B', 'HER2-enriched',
       'HER2-enriched', 'Luminal A', 'Luminal B', 'Basal-like',
       'Luminal A', 'HER2-enriched', 'Luminal A', 'Luminal A',
       'Luminal A', 'HER2-enriched', 'Luminal A', 'HER2-enriched',
       'Luminal B', 'Luminal B', 'Luminal B', 'Luminal A', 'Luminal A',
       'Luminal A', 'Luminal B', 'Luminal B', 'HER2-enriched',
       'Luminal B', 'Luminal B', 'Luminal B', 'Luminal B', 'Luminal B',
       'Luminal A', 'Luminal A', 'Luminal B', 'HER2-enriched',
       'Luminal B', 'Luminal A', 'Luminal A', 'Luminal A', 'Luminal A',
       'HER2-enriched', 'Luminal B', 'Luminal B', 'Luminal A',
       'Luminal A', 'Luminal B', 'Luminal B', 'Luminal A', 'Luminal B',
       'Luminal A', 'HER2-enriched', 'Basal-like', 'Luminal B',
       'Luminal B', 'Basal-like', 'Luminal B', 'Basal-like', 'Luminal B',
       'Basal-like', 'Luminal A', 'Luminal B', 'Basal-like', 'Luminal B',
       'Basal-like', 'Luminal A', 'Luminal A', 'Luminal A',
       'HER2-enriched', 'Luminal A', 'Basal-like', 'Luminal B',
       'Luminal A', 'Basal-like', 'Luminal A', 'Luminal A', 'Luminal A',
       'Luminal A', 'Luminal B', 'Luminal A', 'Luminal A', 'Basal-like',
       'Luminal A', 'Luminal B', 'HER2-enriched', 'Luminal A',
       'HER2-enriched', 'Luminal B', 'Luminal B', 'Luminal A',
       'HER2-enriched', 'Luminal B', 'Basal-like', 'Basal-like',
       'Luminal B', 'Luminal A', 'Luminal A', 'Luminal A', 'Luminal B',
       'Luminal B', 'HER2-enriched', 'Luminal A', 'Luminal A',
       'Luminal B', 'Luminal A', 'Basal-like', 'Luminal B', 'Basal-like',
       'Luminal A', 'Luminal A', 'Basal-like', 'Basal-like', 'Luminal A',
       'Luminal B', 'Luminal A', 'HER2-enriched', 'Luminal A',
       'Basal-like', 'Luminal A', 'Luminal A', 'Luminal B', 'Basal-like',
       'Luminal A', 'Basal-like', 'Luminal B', 'Luminal A', 'Basal-like',
       'Luminal B', 'Basal-like', 'Luminal B', 'Luminal A',
       'HER2-enriched', 'Luminal B', 'Luminal B', 'Basal-like',
       'Basal-like', 'Luminal B', 'Luminal B', 'Basal-like', 'Basal-like',
       'Basal-like', 'Basal-like', 'Luminal A', 'Luminal A', 'Luminal A',
       'Luminal A', 'Basal-like', 'Basal-like', 'Luminal A',
       'HER2-enriched', 'Luminal A', 'Luminal B', 'Luminal A',
       'Luminal A', 'Basal-like', 'Basal-like', 'Luminal A', 'Basal-like',
       'Luminal A', 'HER2-enriched', 'Luminal A', 'Luminal B',
       'Luminal B', 'Luminal A', 'Luminal A', 'Basal-like',
       'HER2-enriched', 'Luminal B', 'Luminal A', 'Luminal A',
       'Luminal A', 'Basal-like', 'Basal-like', 'Luminal A',
       'HER2-enriched', 'Luminal A', 'Luminal B', 'Luminal A',
       'Luminal A', 'Luminal A', 'Luminal A', 'Luminal A',
       'HER2-enriched', 'Basal-like', 'Basal-like', 'Luminal A',
       'Luminal A', 'Luminal A', 'Luminal B', 'Luminal B', 'Basal-like',
       'Luminal A', 'Luminal A', 'Luminal A', 'Basal-like', 'Luminal A',
       'Luminal B', 'Luminal A', 'Luminal B', 'Basal-like',
       'HER2-enriched', 'Luminal B', 'Luminal A', 'Luminal A',
       'Luminal A', 'Basal-like', 'Luminal A', 'Luminal B',
       'HER2-enriched', 'Luminal A', 'Basal-like', 'Luminal A',
       'Luminal A', 'Luminal B', 'Luminal B', 'Basal-like', 'Luminal A',
       'Basal-like', 'Luminal A', 'Luminal A', 'Luminal A', 'Luminal A',
       'Luminal A', 'Luminal A', 'Luminal A', 'Luminal A', 'Basal-like',
       'Luminal B', 'Luminal B', 'Luminal A', 'Luminal B', 'Luminal B',
       'Luminal B', 'Luminal A', 'Luminal A', 'Luminal A', 'Luminal A',
       'Luminal A', 'Basal-like', 'Luminal A', 'Luminal A', 'Luminal A',
       'Luminal A', 'Luminal A', 'Luminal A', 'HER2-enriched',
       'Basal-like', 'Luminal A', 'Luminal A', 'Basal-like', 'Luminal A',
       'Luminal A', 'Luminal A', 'Luminal A', 'HER2-enriched',
       'Luminal A', 'Luminal A', 'Luminal A', 'Luminal B', 'Luminal A',
       'Luminal A', 'Luminal A', 'Luminal A', 'Luminal A', 'Luminal A',
       'Luminal A', 'Luminal A', 'Luminal A', 'Luminal A', 'Basal-like',
       'Basal-like', 'Luminal A', 'Luminal A', 'Luminal A', 'Luminal B',
       'Luminal B', 'Luminal A', 'HER2-enriched', 'Basal-like',
       'Luminal B', 'Luminal A', 'Luminal A', 'Luminal A', 'Basal-like',
       'Luminal B', 'Basal-like', 'Luminal A', 'Luminal A', 'Luminal B',
       'Basal-like', 'Luminal B', 'Luminal A', 'Luminal A',
       'HER2-enriched', 'Basal-like', 'HER2-enriched', 'Luminal A',
       'Luminal A', 'Luminal B', 'Basal-like', 'Luminal A', 'Luminal A',
       'Luminal A', 'Luminal A', 'HER2-enriched', 'Luminal B',
       'Basal-like', 'Basal-like', 'HER2-enriched', 'Luminal B',
       'Luminal A', 'Luminal A', 'HER2-enriched', 'HER2-enriched',
       'HER2-enriched', 'Luminal B', 'Basal-like', 'Luminal B',
       'Luminal B', 'Luminal A', 'HER2-enriched', 'HER2-enriched',
       'Basal-like', 'Luminal A', 'Luminal A', 'Basal-like',
       'HER2-enriched', 'HER2-enriched', 'HER2-enriched', 'HER2-enriched',
       'Luminal B', 'Luminal A', 'Luminal B', 'Luminal B', 'Luminal B',
       'Luminal B', 'HER2-enriched', 'Luminal B', 'Luminal A',
       'Basal-like', 'Basal-like', 'Luminal A', 'Basal-like', 'Luminal A',
       'Luminal A', 'Luminal B', 'Luminal B', 'Luminal B', 'Luminal A',
       'Luminal B', 'Luminal A', 'Luminal A', 'Basal-like', 'Luminal B',
       'HER2-enriched', 'Luminal A', 'Basal-like', 'Luminal B',
       'Luminal A', 'HER2-enriched', 'Luminal B', 'Basal-like',
       'Basal-like', 'Luminal A', 'Basal-like', 'HER2-enriched',
       'Luminal A', 'Luminal A', 'Luminal B', 'Luminal A', 'Basal-like',
       'Basal-like', 'Luminal B', 'Luminal A', 'Luminal A', 'Luminal A',
       'Luminal A', 'Luminal A', 'Luminal A', 'Luminal A', 'Luminal A',
       'Luminal B', 'Luminal B', 'Luminal B', 'Luminal A', 'Luminal A',
       'Luminal A', 'Luminal B', 'Luminal B', 'Basal-like',
       'HER2-enriched', 'Luminal A', 'Luminal A', 'Basal-like',
       'Luminal A', 'Luminal A', 'Luminal A'], dtype=object)

In [12]:
np.unique(labels["PAM50_mRNA_nature2012"].to_numpy(), return_counts=True)

(array(['Basal-like', 'HER2-enriched', 'Luminal A', 'Luminal B'],
       dtype=object),
 array([ 98,  58, 231, 127]))

In [13]:
rna = rna.select(labels["sampleID"].to_numpy())

In [14]:
rna

shape: (20_530, 514)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ TCGA-A1-A ┆ TCGA-A1-A ┆ TCGA-A1-A ┆ TCGA-A1-A ┆ … ┆ TCGA-E2-A ┆ TCGA-E2-A ┆ TCGA-E2-A ┆ TCGA-E2- │
│ 0SD-01    ┆ 0SE-01    ┆ 0SH-01    ┆ 0SJ-01    ┆   ┆ 1B5-01    ┆ 1B6-01    ┆ 1BC-01    ┆ A1BD-01  │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 9.1657    ┆ 9.7179    ┆ 8.8669    ┆ 9.7663    ┆ … ┆ 8.9027    ┆ 8.6965    ┆ 9.0303    ┆ 10.7991  │
│ 2.4935    ┆ 3.3983    ┆ 1.6631    ┆ 6.1765    ┆ … ┆ 4.8873    ┆ 4.6748    ┆ 6.9578    ┆ 2.1772   │
│ 0.0       ┆ 0.0       ┆ 0.4449    ┆ 0.0       ┆ … ┆ 0.0       ┆ 1.4776    ┆ 0.0       ┆ 0.8114   │
│ 11.7868   ┆ 11.3219   ┆ 11.8779   ┆ 11.502    ┆ … ┆ 12.6904   ┆ 12.3403   ┆ 11.8271   ┆ 12.2783  │
│ 11.0131   ┆ 11.2617   ┆ 11.8526   ┆ 11.4405   ┆ … ┆ 11.5409   ┆ 10.4812   ┆ 11.8211   ┆ 10.791   │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 12.6757   ┆ 12.6287   ┆ 13.9112   ┆ 12.3596   ┆ … ┆ 12.4708   ┆ 12.493    ┆ 12.9017   ┆ 12.2984  │
│ 8.9559    ┆ 8.053     ┆ 7.5385    ┆ 7.4431    ┆ … ┆ 9.481     ┆ 7.374     ┆ 8.7661    ┆ 8.3132   │
│ 10.7473   ┆ 11.0453   ┆ 11.3402   ┆ 10.7773   ┆ … ┆ 11.011    ┆ 12.6251   ┆ 9.9638    ┆ 12.172   │
│ 8.7529    ┆ 7.8723    ┆ 4.7356    ┆ 7.6359    ┆ … ┆ 9.7613    ┆ 7.4161    ┆ 7.1316    ┆ 6.9635   │
│ 10.5299   ┆ 9.8006    ┆ 9.6643    ┆ 10.6673   ┆ … ┆ 10.8004   ┆ 10.7302   ┆ 9.9003    ┆ 9.3752   │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [15]:
# filter low var rows
rna_mat = rna.to_numpy()
rna_vars = rna_mat.var(axis=1)
high_var_mask = rna_vars > 0.01

np.unique(high_var_mask, return_counts=True)

high_var_idx = np.where(high_var_mask)[0]

In [16]:
gene_names = gene_names[high_var_idx]
rna = rna[high_var_idx]

print(rna.shape, gene_names.shape)

(19767, 514) (19767,)

In [17]:
label_encoder = LabelEncoder()
label_encoder.fit(y_all)
y_all_e = label_encoder.transform(y_all)

# add numberd labels to labels df
labels = labels.with_columns(y=y_all_e)

In [18]:
# labels and rna columns are aligned, do train, val, test split

# random split for train / test
train_temp_idx, test_idx = train_test_split(
    np.arange(rna.shape[1]),
    test_size=0.3,
    # stratify=y,
    random_state=4
)

In [19]:
train_idx, val_idx = train_test_split(
    train_temp_idx, 
    test_size=0.1, 
    stratify=y_all_e[train_temp_idx],                   
    random_state=4
)

In [20]:
# split dataframes
train_df = rna[:, train_idx.tolist()]
train_labels = labels[train_idx]
val_df = rna[:, val_idx.tolist()]
val_labels = labels[val_idx]
test_df = rna[:, test_idx.tolist()]
test_labels = labels[test_idx]

In [21]:
# select features based on the training set
num_labels = len(np.unique(y_all_e))
genes_class_mean = np.zeros((rna.shape[0], num_labels))

# separate training samples by class
for label in range(num_labels):
    # select cols which are from this class
    label_samples = train_labels.filter(pl.col("y") == label)["sampleID"].to_numpy()
    label_train_df = train_df[label_samples].to_numpy()

    genes_class_mean[:, label] = label_train_df.mean(axis=1)

In [22]:
genes_class_variance = genes_class_mean.var(axis=1)

class_var_order = np.argsort(genes_class_variance)

# select the 500 genes with the largest variance
best_500 = class_var_order >= (genes_class_variance.shape[0] - 500)
best_500_idx = np.where(best_500)[0]

# selection itself
train_df = train_df[best_500_idx]
val_df = val_df[best_500_idx]
test_df = test_df[best_500_idx]

In [23]:
X_train = train_df.to_numpy().T
y_train = train_labels["y"].to_numpy()
X_val = val_df.to_numpy().T
y_val = val_labels["y"].to_numpy()
X_test = test_df.to_numpy().T
y_test = test_labels["y"].to_numpy()

# scale everything
std_scale = StandardScaler().fit(X_train)
X_train = std_scale.transform(X_train) 
X_val = std_scale.transform(X_val)
X_test = std_scale.transform(X_test)

In [25]:
# eval using knns
ks = (1, 30)

# eval on rbf svms
def objective_knn(trial):

    knn = KNeighborsClassifier(
        n_neighbors=trial.suggest_int("n_neighbors", ks[0], ks[1]),
        weights=trial.suggest_categorical("weights", ["uniform", "distance"]),
    )


    knn.fit(X_train, y_train)
    
    y_pred = knn.predict(X_val)

    f1 = f1_score(y_val, y_pred, average="weighted")

    return f1

study = optuna.create_study(direction="maximize")
study.optimize(objective_knn, n_trials=200)

# print the mean f1 score for the best performing parameter
# print(
#     f"| RBF SVM | {best_results['acc']:.4f} +/- {best_results['acc_std']:.4f} | {best_results['f1_macro']:.4f} +/- {best_results['f1_macro_std']:.4f} | {best_results['f1_weighted']:.4f} +/- {best_results['f1_weighted_std']:.4f} |"
# )
print(f"study {study.best_value=}, {study.best_params=}")

[I 2024-03-15 18:10:10,637] A new study created in memory with name: no-name-7ac9ad89-ef2e-40b8-bc6f-553df3fc9b4f
[I 2024-03-15 18:10:10,641] Trial 0 finished with value: 0.6196969696969696 and parameters: {'n_neighbors': 2, 'weights': 'distance'}. Best is trial 0 with value: 0.6196969696969696.
[I 2024-03-15 18:10:10,643] Trial 1 finished with value: 0.5642857142857144 and parameters: {'n_neighbors': 29, 'weights': 'uniform'}. Best is trial 0 with value: 0.6196969696969696.
[I 2024-03-15 18:10:10,646] Trial 2 finished with value: 0.6215447154471545 and parameters: {'n_neighbors': 18, 'weights': 'uniform'}. Best is trial 2 with value: 0.6215447154471545.
[I 2024-03-15 18:10:10,649] Trial 3 finished with value: 0.5642857142857144 and parameters: {'n_neighbors': 29, 'weights': 'distance'}. Best is trial 2 with value: 0.6215447154471545.
[I 2024-03-15 18:10:10,651] Trial 4 finished with value: 0.6180555555555556 and parameters: {'n_neighbors': 23, 'weights': 'uniform'}. Best is trial 2 with value: 0.6215447154471545.
[I 2024-03-15 18:10:10,654] Trial 5 finished with value: 0.6215447154471545 and parameters: {'n_neighbors': 15, 'weights': 'distance'}. Best is trial 2 with value: 0.6215447154471545.
[I 2024-03-15 18:10:10,657] Trial 6 finished with value: 0.6215447154471545 and parameters: {'n_neighbors': 18, 'weights': 'uniform'}. Best is trial 2 with value: 0.6215447154471545.
[I 2024-03-15 18:10:10,660] Trial 7 finished with value: 0.5642857142857144 and parameters: {'n_neighbors': 29, 'weights': 'uniform'}. Best is trial 2 with value: 0.6215447154471545.
[I 2024-03-15 18:10:10,663] Trial 8 finished with value: 0.5642857142857144 and parameters: {'n_neighbors': 29, 'weights': 'uniform'}. Best is trial 2 with value: 0.6215447154471545.
[I 2024-03-15 18:10:10,666] Trial 9 finished with value: 0.6215447154471545 and parameters: {'n_neighbors': 18, 'weights': 'distance'}. Best is trial 2 with value: 0.6215447154471545.
[I 2024-03-15 18:10:10,675] Trial 10 finished with value: 0.564137308039747 and parameters: {'n_neighbors': 8, 'weights': 'uniform'}. Best is trial 2 with value: 0.6215447154471545.
[I 2024-03-15 18:10:10,681] Trial 11 finished with value: 0.6215447154471545 and parameters: {'n_neighbors': 12, 'weights': 'distance'}. Best is trial 2 with value: 0.6215447154471545.
[I 2024-03-15 18:10:10,687] Trial 12 finished with value: 0.6700757575757577 and parameters: {'n_neighbors': 13, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,693] Trial 13 finished with value: 0.564137308039747 and parameters: {'n_neighbors': 9, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,699] Trial 14 finished with value: 0.6180555555555556 and parameters: {'n_neighbors': 23, 'weights': 'uniform'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,705] Trial 15 finished with value: 0.5725548164572555 and parameters: {'n_neighbors': 22, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,711] Trial 16 finished with value: 0.5955972132442721 and parameters: {'n_neighbors': 3, 'weights': 'uniform'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,716] Trial 17 finished with value: 0.6700757575757577 and parameters: {'n_neighbors': 13, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,721] Trial 18 finished with value: 0.6038591038591039 and parameters: {'n_neighbors': 6, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,727] Trial 19 finished with value: 0.6700757575757577 and parameters: {'n_neighbors': 13, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,733] Trial 20 finished with value: 0.564137308039747 and parameters: {'n_neighbors': 11, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,739] Trial 21 finished with value: 0.6215447154471545 and parameters: {'n_neighbors': 14, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,745] Trial 22 finished with value: 0.6215447154471545 and parameters: {'n_neighbors': 12, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,750] Trial 23 finished with value: 0.6038591038591039 and parameters: {'n_neighbors': 6, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,755] Trial 24 finished with value: 0.5642857142857144 and parameters: {'n_neighbors': 16, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,761] Trial 25 finished with value: 0.564137308039747 and parameters: {'n_neighbors': 9, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,766] Trial 26 finished with value: 0.6180555555555556 and parameters: {'n_neighbors': 21, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,771] Trial 27 finished with value: 0.6215447154471545 and parameters: {'n_neighbors': 14, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,777] Trial 28 finished with value: 0.564137308039747 and parameters: {'n_neighbors': 11, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,783] Trial 29 finished with value: 0.6318172568172568 and parameters: {'n_neighbors': 3, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,788] Trial 30 finished with value: 0.6180555555555556 and parameters: {'n_neighbors': 20, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,793] Trial 31 finished with value: 0.591938091938092 and parameters: {'n_neighbors': 4, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,799] Trial 32 finished with value: 0.564137308039747 and parameters: {'n_neighbors': 7, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,806] Trial 33 finished with value: 0.6180555555555556 and parameters: {'n_neighbors': 26, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,812] Trial 34 finished with value: 0.5642857142857144 and parameters: {'n_neighbors': 16, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,818] Trial 35 finished with value: 0.6196969696969696 and parameters: {'n_neighbors': 1, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,823] Trial 36 finished with value: 0.6700757575757577 and parameters: {'n_neighbors': 13, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,829] Trial 37 finished with value: 0.6700757575757577 and parameters: {'n_neighbors': 13, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,834] Trial 38 finished with value: 0.6215447154471545 and parameters: {'n_neighbors': 17, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,839] Trial 39 finished with value: 0.564137308039747 and parameters: {'n_neighbors': 10, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,845] Trial 40 finished with value: 0.6215447154471545 and parameters: {'n_neighbors': 14, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,851] Trial 41 finished with value: 0.6700757575757577 and parameters: {'n_neighbors': 13, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,856] Trial 42 finished with value: 0.6215447154471545 and parameters: {'n_neighbors': 15, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,862] Trial 43 finished with value: 0.6700757575757577 and parameters: {'n_neighbors': 19, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,868] Trial 44 finished with value: 0.6215447154471545 and parameters: {'n_neighbors': 12, 'weights': 'uniform'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,886] Trial 45 finished with value: 0.564137308039747 and parameters: {'n_neighbors': 10, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,894] Trial 46 finished with value: 0.6215447154471545 and parameters: {'n_neighbors': 17, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,901] Trial 47 finished with value: 0.6215447154471545 and parameters: {'n_neighbors': 13, 'weights': 'uniform'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,907] Trial 48 finished with value: 0.6700757575757577 and parameters: {'n_neighbors': 13, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,913] Trial 49 finished with value: 0.6215447154471545 and parameters: {'n_neighbors': 15, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,919] Trial 50 finished with value: 0.564137308039747 and parameters: {'n_neighbors': 8, 'weights': 'uniform'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,925] Trial 51 finished with value: 0.6700757575757577 and parameters: {'n_neighbors': 13, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,931] Trial 52 finished with value: 0.564137308039747 and parameters: {'n_neighbors': 11, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,937] Trial 53 finished with value: 0.6215447154471545 and parameters: {'n_neighbors': 17, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,944] Trial 54 finished with value: 0.564137308039747 and parameters: {'n_neighbors': 10, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,950] Trial 55 finished with value: 0.6215447154471545 and parameters: {'n_neighbors': 14, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,956] Trial 56 finished with value: 0.6215447154471545 and parameters: {'n_neighbors': 12, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,963] Trial 57 finished with value: 0.6215447154471545 and parameters: {'n_neighbors': 15, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,969] Trial 58 finished with value: 0.6700757575757577 and parameters: {'n_neighbors': 13, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,976] Trial 59 finished with value: 0.6215447154471545 and parameters: {'n_neighbors': 18, 'weights': 'uniform'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,982] Trial 60 finished with value: 0.564137308039747 and parameters: {'n_neighbors': 9, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,989] Trial 61 finished with value: 0.6215447154471545 and parameters: {'n_neighbors': 18, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:10,995] Trial 62 finished with value: 0.5642857142857144 and parameters: {'n_neighbors': 16, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:11,002] Trial 63 finished with value: 0.6180555555555556 and parameters: {'n_neighbors': 20, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:11,008] Trial 64 finished with value: 0.6700757575757577 and parameters: {'n_neighbors': 19, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:11,015] Trial 65 finished with value: 0.5725548164572555 and parameters: {'n_neighbors': 24, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:11,021] Trial 66 finished with value: 0.564137308039747 and parameters: {'n_neighbors': 11, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:11,028] Trial 67 finished with value: 0.6215447154471545 and parameters: {'n_neighbors': 14, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:11,034] Trial 68 finished with value: 0.6215447154471545 and parameters: {'n_neighbors': 12, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:11,041] Trial 69 finished with value: 0.6215447154471545 and parameters: {'n_neighbors': 15, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:11,047] Trial 70 finished with value: 0.6700757575757577 and parameters: {'n_neighbors': 13, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:11,054] Trial 71 finished with value: 0.6700757575757577 and parameters: {'n_neighbors': 13, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:11,060] Trial 72 finished with value: 0.564137308039747 and parameters: {'n_neighbors': 11, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:11,067] Trial 73 finished with value: 0.6215447154471545 and parameters: {'n_neighbors': 14, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:11,074] Trial 74 finished with value: 0.6215447154471545 and parameters: {'n_neighbors': 12, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:11,081] Trial 75 finished with value: 0.5642857142857144 and parameters: {'n_neighbors': 16, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:11,087] Trial 76 finished with value: 0.6700757575757577 and parameters: {'n_neighbors': 13, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:11,093] Trial 77 finished with value: 0.564137308039747 and parameters: {'n_neighbors': 10, 'weights': 'uniform'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:11,099] Trial 78 finished with value: 0.564137308039747 and parameters: {'n_neighbors': 8, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:11,105] Trial 79 finished with value: 0.6215447154471545 and parameters: {'n_neighbors': 15, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:11,112] Trial 80 finished with value: 0.6215447154471545 and parameters: {'n_neighbors': 17, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:11,117] Trial 81 finished with value: 0.6700757575757577 and parameters: {'n_neighbors': 13, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:11,124] Trial 82 finished with value: 0.6215447154471545 and parameters: {'n_neighbors': 12, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:11,131] Trial 83 finished with value: 0.6215447154471545 and parameters: {'n_neighbors': 14, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:11,137] Trial 84 finished with value: 0.564137308039747 and parameters: {'n_neighbors': 11, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:11,144] Trial 85 finished with value: 0.6215447154471545 and parameters: {'n_neighbors': 14, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:11,151] Trial 86 finished with value: 0.5642857142857144 and parameters: {'n_neighbors': 16, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:11,158] Trial 87 finished with value: 0.6700757575757577 and parameters: {'n_neighbors': 13, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:11,165] Trial 88 finished with value: 0.564137308039747 and parameters: {'n_neighbors': 10, 'weights': 'uniform'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:11,171] Trial 89 finished with value: 0.564137308039747 and parameters: {'n_neighbors': 9, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:11,178] Trial 90 finished with value: 0.6215447154471545 and parameters: {'n_neighbors': 12, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:11,184] Trial 91 finished with value: 0.6700757575757577 and parameters: {'n_neighbors': 13, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:11,191] Trial 92 finished with value: 0.6215447154471545 and parameters: {'n_neighbors': 15, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:11,198] Trial 93 finished with value: 0.6215447154471545 and parameters: {'n_neighbors': 12, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:11,205] Trial 94 finished with value: 0.564137308039747 and parameters: {'n_neighbors': 11, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:11,212] Trial 95 finished with value: 0.6215447154471545 and parameters: {'n_neighbors': 14, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:11,218] Trial 96 finished with value: 0.6700757575757577 and parameters: {'n_neighbors': 13, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:11,225] Trial 97 finished with value: 0.6215447154471545 and parameters: {'n_neighbors': 15, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:11,232] Trial 98 finished with value: 0.5642857142857144 and parameters: {'n_neighbors': 30, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:11,239] Trial 99 finished with value: 0.5725548164572555 and parameters: {'n_neighbors': 22, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:11,246] Trial 100 finished with value: 0.6215447154471545 and parameters: {'n_neighbors': 13, 'weights': 'uniform'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:11,253] Trial 101 finished with value: 0.6700757575757577 and parameters: {'n_neighbors': 19, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:11,260] Trial 102 finished with value: 0.6700757575757577 and parameters: {'n_neighbors': 19, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:11,267] Trial 103 finished with value: 0.6180555555555556 and parameters: {'n_neighbors': 21, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:11,274] Trial 104 finished with value: 0.6215447154471545 and parameters: {'n_neighbors': 18, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:11,281] Trial 105 finished with value: 0.6215447154471545 and parameters: {'n_neighbors': 17, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.
[I 2024-03-15 18:10:11,288] Trial 106 finished with value: 0.6215447154471545 and parameters: {'n_neighbors': 14, 'weights': 'distance'}. Best is trial 12 with value: 0.6700757575757577.

study study.best_value=0.6700757575757577, study.best_params={'n_neighbors': 13, 'weights': 'distance'}
knn f1:  0.5289480923909909

In [26]:
knn = KNeighborsClassifier(
    n_neighbors=study.best_params["n_neighbors"],
    weights=study.best_params["weights"]
)
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

f1 = f1_score(y_test, y_pred, average="weighted")

print("knn f1: ", f1)

knn f1:  0.5289480923909909

## KNNs
f1 score of ~0.53

In [141]:
C_range: tuple = (1e-3, 1e3)
gamma_range: tuple = (1e-3, 1e3)

# eval on rbf svms
def objective(trial):

    svm = SVC(
        C=trial.suggest_float("C", C_range[0], C_range[1], log=True),
        gamma=trial.suggest_float(
            "gamma", gamma_range[0], gamma_range[1], log=True
        ),
        class_weight=trial.suggest_categorical("class_weight", ["balanced", None]),
        kernel="rbf",
    )

    svm.fit(X_train, y_train)
    
    y_pred = svm.predict(X_val)

    f1 = f1_score(y_val, y_pred, average="weighted")

    return f1

study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=200)

# print the mean f1 score for the best performing parameter
# print(
#     f"| RBF SVM | {best_results['acc']:.4f} +/- {best_results['acc_std']:.4f} | {best_results['f1_macro']:.4f} +/- {best_results['f1_macro_std']:.4f} | {best_results['f1_weighted']:.4f} +/- {best_results['f1_weighted_std']:.4f} |"
# )
print(f"study {study.best_value=}, {study.best_params=}")

[I 2024-03-15 15:31:27,643] A new study created in memory with name: no-name-1a3cca76-b5c8-4a71-9ac7-b8566b38ac96
[I 2024-03-15 15:31:27,670] Trial 0 finished with value: 0.2450980392156863 and parameters: {'C': 2.5579742486510035, 'gamma': 328.8687228817511, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.2450980392156863.
[I 2024-03-15 15:31:27,695] Trial 1 finished with value: 0.2450980392156863 and parameters: {'C': 536.6683158456692, 'gamma': 19.2081274433793, 'class_weight': None}. Best is trial 0 with value: 0.2450980392156863.
[I 2024-03-15 15:31:27,718] Trial 2 finished with value: 0.2993827160493827 and parameters: {'C': 3.4224142963574273, 'gamma': 0.00784937662645934, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.2993827160493827.
[I 2024-03-15 15:31:27,743] Trial 3 finished with value: 0.2450980392156863 and parameters: {'C': 6.224230314635548, 'gamma': 233.36947616197656, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.2993827160493827.
[I 2024-03-15 15:31:27,764] Trial 4 finished with value: 0.2450980392156863 and parameters: {'C': 0.08921812696918932, 'gamma': 0.08258786097287209, 'class_weight': None}. Best is trial 2 with value: 0.2993827160493827.
[I 2024-03-15 15:31:27,789] Trial 5 finished with value: 0.2450980392156863 and parameters: {'C': 271.1129494806812, 'gamma': 108.65268768160227, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.2993827160493827.
[I 2024-03-15 15:31:27,815] Trial 6 finished with value: 0.2450980392156863 and parameters: {'C': 0.48609422881971365, 'gamma': 1.285370381550817, 'class_weight': None}. Best is trial 2 with value: 0.2993827160493827.
[I 2024-03-15 15:31:27,834] Trial 7 finished with value: 0.7987902763444558 and parameters: {'C': 9.170590962663722, 'gamma': 0.001364760676910328, 'class_weight': None}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:27,857] Trial 8 finished with value: 0.1 and parameters: {'C': 0.10903596357827726, 'gamma': 0.5409331986019676, 'class_weight': 'balanced'}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:27,881] Trial 9 finished with value: 0.2450980392156863 and parameters: {'C': 0.0204623310821527, 'gamma': 5.687310894264768, 'class_weight': None}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:27,910] Trial 10 finished with value: 0.2450980392156863 and parameters: {'C': 0.00148478951004098, 'gamma': 0.0012302756344031648, 'class_weight': None}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:27,942] Trial 11 finished with value: 0.7987902763444558 and parameters: {'C': 27.005931758711125, 'gamma': 0.002575805760745346, 'class_weight': 'balanced'}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:27,972] Trial 12 finished with value: 0.7987902763444558 and parameters: {'C': 44.03945755620534, 'gamma': 0.0012147397409835467, 'class_weight': None}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:28,006] Trial 13 finished with value: 0.2450980392156863 and parameters: {'C': 40.90473200234951, 'gamma': 0.030316792255190933, 'class_weight': 'balanced'}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:28,040] Trial 14 finished with value: 0.2450980392156863 and parameters: {'C': 60.198772079675265, 'gamma': 0.009267973280243626, 'class_weight': 'balanced'}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:28,074] Trial 15 finished with value: 0.2450980392156863 and parameters: {'C': 12.984281598697075, 'gamma': 0.0892907382016588, 'class_weight': None}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:28,106] Trial 16 finished with value: 0.7234427609427609 and parameters: {'C': 0.6502098902147084, 'gamma': 0.004076783517763056, 'class_weight': 'balanced'}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:28,140] Trial 17 finished with value: 0.2450980392156863 and parameters: {'C': 68.84426128341894, 'gamma': 0.24227012250348695, 'class_weight': None}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:28,174] Trial 18 finished with value: 0.2450980392156863 and parameters: {'C': 885.5016071903073, 'gamma': 0.024289641916041344, 'class_weight': None}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:28,207] Trial 19 finished with value: 0.7598039215686274 and parameters: {'C': 13.523414260648927, 'gamma': 0.003063967062060358, 'class_weight': 'balanced'}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:28,242] Trial 20 finished with value: 0.2450980392156863 and parameters: {'C': 221.12321703953643, 'gamma': 2.3978762473169817, 'class_weight': None}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:28,274] Trial 21 finished with value: 0.7987902763444558 and parameters: {'C': 23.097362926635622, 'gamma': 0.0013499144953286661, 'class_weight': None}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:28,304] Trial 22 finished with value: 0.7679876775271511 and parameters: {'C': 147.28775196055372, 'gamma': 0.0010032046724552024, 'class_weight': None}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:28,337] Trial 23 finished with value: 0.2450980392156863 and parameters: {'C': 1.0874852539867785, 'gamma': 0.016199158083515505, 'class_weight': None}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:28,370] Trial 24 finished with value: 0.7279345878136201 and parameters: {'C': 8.379821271916464, 'gamma': 0.00358142886444136, 'class_weight': None}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:28,402] Trial 25 finished with value: 0.7279345878136201 and parameters: {'C': 86.98328689323172, 'gamma': 0.0036104365060477084, 'class_weight': None}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:28,437] Trial 26 finished with value: 0.2450980392156863 and parameters: {'C': 25.264888483039776, 'gamma': 0.06247659451854369, 'class_weight': 'balanced'}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:28,470] Trial 27 finished with value: 0.2450980392156863 and parameters: {'C': 3.72107169257256, 'gamma': 0.008866203267006975, 'class_weight': None}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:28,504] Trial 28 finished with value: 0.2450980392156863 and parameters: {'C': 1.7616781410221096, 'gamma': 0.23995326153160865, 'class_weight': 'balanced'}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:28,537] Trial 29 finished with value: 0.6902158228245185 and parameters: {'C': 0.18536155337169313, 'gamma': 0.0023782263869896944, 'class_weight': 'balanced'}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:28,571] Trial 30 finished with value: 0.2450980392156863 and parameters: {'C': 26.949339707318273, 'gamma': 0.02703426886903844, 'class_weight': None}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:28,603] Trial 31 finished with value: 0.7987902763444558 and parameters: {'C': 20.595386136637387, 'gamma': 0.0010490731685714894, 'class_weight': None}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:28,636] Trial 32 finished with value: 0.7987902763444558 and parameters: {'C': 7.043079713570213, 'gamma': 0.0019412999282084845, 'class_weight': None}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:28,670] Trial 33 finished with value: 0.4426793013749536 and parameters: {'C': 434.26750961988193, 'gamma': 0.007048477696946924, 'class_weight': None}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:28,708] Trial 34 finished with value: 0.2450980392156863 and parameters: {'C': 2.92437809927017, 'gamma': 33.48381209756962, 'class_weight': None}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:28,742] Trial 35 finished with value: 0.4426793013749536 and parameters: {'C': 118.91777328707641, 'gamma': 0.007047360061011578, 'class_weight': None}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:28,775] Trial 36 finished with value: 0.7987902763444558 and parameters: {'C': 5.511644712654331, 'gamma': 0.0020168321853905056, 'class_weight': 'balanced'}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:28,806] Trial 37 finished with value: 0.7679876775271511 and parameters: {'C': 40.28451787247568, 'gamma': 0.0010178002615525703, 'class_weight': None}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:28,842] Trial 38 finished with value: 0.2450980392156863 and parameters: {'C': 12.825267699516587, 'gamma': 665.1428444237844, 'class_weight': None}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:28,877] Trial 39 finished with value: 0.2450980392156863 and parameters: {'C': 1.4417722660130516, 'gamma': 0.01437207601319114, 'class_weight': 'balanced'}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:28,912] Trial 40 finished with value: 0.5698412698412699 and parameters: {'C': 392.56423477007223, 'gamma': 0.006686592203447965, 'class_weight': None}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:28,944] Trial 41 finished with value: 0.7987902763444558 and parameters: {'C': 20.895804890840477, 'gamma': 0.001744336050768329, 'class_weight': None}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:28,975] Trial 42 finished with value: 0.7987902763444558 and parameters: {'C': 38.66220559354871, 'gamma': 0.0010698061306712693, 'class_weight': None}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:29,009] Trial 43 finished with value: 0.6742989668985875 and parameters: {'C': 4.43572546598663, 'gamma': 0.0048058606488008675, 'class_weight': None}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:29,041] Trial 44 finished with value: 0.7987902763444558 and parameters: {'C': 182.8870403680126, 'gamma': 0.0020543354320534295, 'class_weight': None}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:29,075] Trial 45 finished with value: 0.7575119011951129 and parameters: {'C': 17.16625830175275, 'gamma': 0.003271408408374377, 'class_weight': None}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:29,110] Trial 46 finished with value: 0.1 and parameters: {'C': 0.012706763970879408, 'gamma': 0.06195297409170116, 'class_weight': 'balanced'}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:29,145] Trial 47 finished with value: 0.2450980392156863 and parameters: {'C': 72.92781653597876, 'gamma': 0.012983172011964661, 'class_weight': None}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:29,177] Trial 48 finished with value: 0.7987902763444558 and parameters: {'C': 8.81418691526687, 'gamma': 0.0015615859781714682, 'class_weight': 'balanced'}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:29,213] Trial 49 finished with value: 0.2450980392156863 and parameters: {'C': 2.181913579919775, 'gamma': 65.46069149442415, 'class_weight': None}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:29,247] Trial 50 finished with value: 0.4426793013749536 and parameters: {'C': 0.4926022441226259, 'gamma': 0.00513096030480411, 'class_weight': None}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:29,280] Trial 51 finished with value: 0.7987902763444558 and parameters: {'C': 6.934837187548113, 'gamma': 0.001766071185990641, 'class_weight': None}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:29,314] Trial 52 finished with value: 0.7871345029239767 and parameters: {'C': 40.5009365794995, 'gamma': 0.003106703674977687, 'class_weight': None}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:29,352] Trial 53 finished with value: 0.2450980392156863 and parameters: {'C': 11.149914568862746, 'gamma': 8.564299534721366, 'class_weight': None}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:29,383] Trial 54 finished with value: 0.7987902763444558 and parameters: {'C': 23.036450618284302, 'gamma': 0.0010814748339107443, 'class_weight': None}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:29,416] Trial 55 finished with value: 0.7987902763444558 and parameters: {'C': 87.988048680733, 'gamma': 0.002483684436998433, 'class_weight': None}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:29,452] Trial 56 finished with value: 0.2450980392156863 and parameters: {'C': 50.113556592449136, 'gamma': 0.011443723866733585, 'class_weight': 'balanced'}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:29,486] Trial 57 finished with value: 0.6742989668985875 and parameters: {'C': 4.833838470916305, 'gamma': 0.005055413782496588, 'class_weight': None}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:29,521] Trial 58 finished with value: 0.2450980392156863 and parameters: {'C': 815.9228259684318, 'gamma': 0.020332728350845396, 'class_weight': None}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:29,552] Trial 59 finished with value: 0.7987902763444558 and parameters: {'C': 15.704822363747063, 'gamma': 0.0014635497291756912, 'class_weight': 'balanced'}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:29,587] Trial 60 finished with value: 0.2450980392156863 and parameters: {'C': 274.2367366080233, 'gamma': 0.03308812977480284, 'class_weight': None}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:29,624] Trial 61 finished with value: 0.7987902763444558 and parameters: {'C': 6.2121669390828345, 'gamma': 0.0021470034996017395, 'class_weight': 'balanced'}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:29,660] Trial 62 finished with value: 0.7987902763444558 and parameters: {'C': 28.69994597990043, 'gamma': 0.0026183966975318177, 'class_weight': 'balanced'}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:29,693] Trial 63 finished with value: 0.7987902763444558 and parameters: {'C': 2.8082307355274807, 'gamma': 0.0015271328481390428, 'class_weight': 'balanced'}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:29,727] Trial 64 finished with value: 0.7518518518518519 and parameters: {'C': 0.7163291471033366, 'gamma': 0.0034152365093008587, 'class_weight': 'balanced'}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:29,763] Trial 65 finished with value: 0.2450980392156863 and parameters: {'C': 7.694718882488332, 'gamma': 0.008705997029233052, 'class_weight': 'balanced'}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:29,803] Trial 66 finished with value: 0.2450980392156863 and parameters: {'C': 126.41172821401953, 'gamma': 0.7853105740574643, 'class_weight': 'balanced'}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:29,838] Trial 67 finished with value: 0.6725694444444444 and parameters: {'C': 3.7179741304255516, 'gamma': 0.005237294587023, 'class_weight': None}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:29,872] Trial 68 finished with value: 0.2450980392156863 and parameters: {'C': 0.2768013888679172, 'gamma': 0.2310951431163111, 'class_weight': None}. Best is trial 7 with value: 0.7987902763444558.
[I 2024-03-15 15:31:29,903] Trial 69 finished with value: 0.8292162398332997 and parameters: {'C': 1.080809958568503, 'gamma': 0.0014753995785367125, 'class_weight': 'balanced'}. Best is trial 69 with value: 0.8292162398332997.
[I 2024-03-15 15:31:29,934] Trial 70 finished with value: 0.7987902763444558 and parameters: {'C': 1.5531703270262167, 'gamma': 0.001014867990927138, 'class_weight': None}. Best is trial 69 with value: 0.8292162398332997.
[I 2024-03-15 15:31:29,969] Trial 71 finished with value: 0.7987902763444558 and parameters: {'C': 10.504596798484405, 'gamma': 0.0020724552584693097, 'class_weight': 'balanced'}. Best is trial 69 with value: 0.8292162398332997.
[I 2024-03-15 15:31:30,000] Trial 72 finished with value: 0.7987902763444558 and parameters: {'C': 1.150952767177923, 'gamma': 0.0015108493862778002, 'class_weight': 'balanced'}. Best is trial 69 with value: 0.8292162398332997.
[I 2024-03-15 15:31:30,036] Trial 73 finished with value: 0.6742989668985875 and parameters: {'C': 5.377436584949769, 'gamma': 0.004131438197342602, 'class_weight': 'balanced'}. Best is trial 69 with value: 0.8292162398332997.
[I 2024-03-15 15:31:30,071] Trial 74 finished with value: 0.34399092970521544 and parameters: {'C': 0.05670812263451167, 'gamma': 0.002580164600080784, 'class_weight': 'balanced'}. Best is trial 69 with value: 0.8292162398332997.
[I 2024-03-15 15:31:30,104] Trial 75 finished with value: 0.7987902763444558 and parameters: {'C': 17.275833297186242, 'gamma': 0.0013164501630450595, 'class_weight': 'balanced'}. Best is trial 69 with value: 0.8292162398332997.
[I 2024-03-15 15:31:30,140] Trial 76 finished with value: 0.5698412698412699 and parameters: {'C': 27.037312714904303, 'gamma': 0.006738276403542592, 'class_weight': None}. Best is trial 69 with value: 0.8292162398332997.
[I 2024-03-15 15:31:30,173] Trial 77 finished with value: 0.7987902763444558 and parameters: {'C': 53.09450986776782, 'gamma': 0.001877626961061138, 'class_weight': 'balanced'}. Best is trial 69 with value: 0.8292162398332997.
[I 2024-03-15 15:31:30,211] Trial 78 finished with value: 0.2450980392156863 and parameters: {'C': 2.5805151418267678, 'gamma': 3.11669878914346, 'class_weight': None}. Best is trial 69 with value: 0.8292162398332997.
[I 2024-03-15 15:31:30,246] Trial 79 finished with value: 0.7279345878136201 and parameters: {'C': 30.355019101162647, 'gamma': 0.003642017527268935, 'class_weight': None}. Best is trial 69 with value: 0.8292162398332997.
[I 2024-03-15 15:31:30,279] Trial 80 finished with value: 0.7679876775271511 and parameters: {'C': 9.939791591102408, 'gamma': 0.0010095655974702675, 'class_weight': 'balanced'}. Best is trial 69 with value: 0.8292162398332997.
[I 2024-03-15 15:31:30,313] Trial 81 finished with value: 0.7987902763444558 and parameters: {'C': 18.06610759028497, 'gamma': 0.0017719457431990579, 'class_weight': None}. Best is trial 69 with value: 0.8292162398332997.
[I 2024-03-15 15:31:30,348] Trial 82 finished with value: 0.7987902763444558 and parameters: {'C': 73.6262151199298, 'gamma': 0.0028233687743031938, 'class_weight': None}. Best is trial 69 with value: 0.8292162398332997.
[I 2024-03-15 15:31:30,381] Trial 83 finished with value: 0.7987902763444558 and parameters: {'C': 18.069861666339396, 'gamma': 0.0014273723202550168, 'class_weight': None}. Best is trial 69 with value: 0.8292162398332997.
[I 2024-03-15 15:31:30,417] Trial 84 finished with value: 0.6393939393939394 and parameters: {'C': 35.29814206072149, 'gamma': 0.005525873355754111, 'class_weight': None}. Best is trial 69 with value: 0.8292162398332997.
[I 2024-03-15 15:31:30,451] Trial 85 finished with value: 0.7987902763444558 and parameters: {'C': 105.46509822824514, 'gamma': 0.0023945538608128843, 'class_weight': None}. Best is trial 69 with value: 0.8292162398332997.
[I 2024-03-15 15:31:30,487] Trial 86 finished with value: 0.2450980392156863 and parameters: {'C': 22.94307135944252, 'gamma': 0.009784394452682425, 'class_weight': None}. Best is trial 69 with value: 0.8292162398332997.
[I 2024-03-15 15:31:30,522] Trial 87 finished with value: 0.6742989668985875 and parameters: {'C': 13.288449595523003, 'gamma': 0.004060967358160568, 'class_weight': None}. Best is trial 69 with value: 0.8292162398332997.
[I 2024-03-15 15:31:30,555] Trial 88 finished with value: 0.7987902763444558 and parameters: {'C': 50.873780417064594, 'gamma': 0.0013508185574750565, 'class_weight': None}. Best is trial 69 with value: 0.8292162398332997.

study study.best_value=0.8586396546922862, study.best_params={'C': 0.8388442250794123, 'gamma': 0.0024090226780970093, 'class_weight': 'balanced'}

In [142]:
# fit model with best params and test on test set
svm = SVC(
        C=study.best_params["C"],
        gamma=study.best_params["gamma"],
        class_weight=study.best_params["class_weight"],
        kernel="rbf",
)

svm.fit(X_train, y_train)

y_pred = svm.predict(X_test)

f1 = f1_score(y_test, y_pred, average="weighted")

print("svm f1: ", f1)

0.8321924076448073

## SVMs with rbf kernel
- weighted f1 score with ~0.8 on test set
- with normalization wf1 score ~0.83 on test set

In [ ]:
# build mogonet style GNN with
# a. thresholded cosine similarity

In [128]:
def cosine_similarity_matrix(matrix):
    """
    given a matrix of (n_samples, n_features) compute the cosine similarities, between the samples
    """
    # Compute dot product between all pairs of vectors
    dot_products = np.dot(matrix, matrix.T)
    
    # Compute magnitudes of all vectors
    magnitudes = np.linalg.norm(matrix, axis=1)
    
    # Compute outer product of magnitudes to obtain matrix of magnitudes product
    magnitude_products = np.outer(magnitudes, magnitudes)
    
    # Compute cosine similarity matrix
    cosine_similarities = dot_products / magnitude_products
    
    return cosine_similarities

# Example matrix of vectors (rows represent vectors)
matrix = np.array([[1, 1, 1],
                   [2, 2, 2],
                   [1, -1, 1]])

# Compute cosine similarity between all vectors
cos_sim_matrix = cosine_similarity_matrix(matrix)

print("Cosine similarity matrix:")
print(cos_sim_matrix)

Cosine similarity matrix:
[[1.         1.         0.33333333]
 [1.         1.         0.33333333]
 [0.33333333 0.33333333 1.        ]]

In [ ]:
A = cosine_similarity_matrix(X_train)

In [ ]:
# b. moglam style cosine similarity + learned graph

In [ ]:
# build bipartite graph style GNN

In [ ]:
# a. w interactions

In [ ]:
# b. w/o interactions

In [ ]:
# eval mogonet style model

In [ ]:
# eval bipartite style model