# Most recent benchmarks for BRCA dataset

In [2]:
%load_ext autoreload
%autoreload 2

import os
import numpy as np
import polars as pl
import torch
import torch_geometric as pyg
from sklearn.preprocessing import LabelEncoder, StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split, StratifiedKFold

from bipartite_gnn.graph_visualizatons import visualize_graph, visualize_embeddings
from baseline_evals.feature_selection import variance_filtering, class_variational_selection
from bipartite_gnn.preprocessing import mrmr_selection
from baseline_evals.knn_eval import knn_eval
from baseline_evals.svm_eval import svm_eval
from baseline_evals.xgboost_eval import xgboost_eval
from baseline_evals.mlp_eval import mlp_eval
from bipartite_gnn.graph_building import cosine_similarity_matrix, keep_n_neighbours, dense_to_coo
from bipartite_gnn.train_test import GNNTrainer
from gnn_experiments.mogonet_eval import mogonet_eval

### Load data and make sure that everything is aligned

In [3]:
null_vals = ["NA"]

mrna = pl.read_csv("BRCA_PROCESSED_DATA/mrna.tsv", separator="\t", null_values=null_vals)
meth = pl.read_csv("BRCA_PROCESSED_DATA/meth.tsv", separator="\t", null_values=null_vals)
mirna = pl.read_csv("BRCA_PROCESSED_DATA/mirna.tsv", separator="\t", null_values=null_vals)
cnv = pl.read_csv("BRCA_PROCESSED_DATA/cnvth.tsv", separator="\t", null_values=null_vals)

labels = pl.read_csv("BRCA_PROCESSED_DATA/labels.tsv", separator="\t")
le = LabelEncoder()
le.fit(labels["PAM50_mRNA_nature2012"].to_list())
y = le.transform(labels["PAM50_mRNA_nature2012"].to_list())

assert mrna.columns[1:] == meth.columns[1:] == cnv.columns[1:] == mirna.columns[1:] == labels["sampleID"].to_list()

In [3]:
# concat all data into one dataframe
mrna_X = mrna[:, 1:].to_numpy().T
meth_X = meth[:, 1:].to_numpy().T
mirna_X = mirna[:, 1:].to_numpy().T
cnv_X = cnv[:, 1:].to_numpy().T

print(mrna_X.shape, meth_X.shape, mirna_X.shape, cnv_X.shape)

# concat after preprocessing
X_list = [mrna_X, meth_X, mirna_X]

# concat before preprocessing
X = np.hstack(X_list)

(483, 18975) (483, 9317) (483, 231) (483, 24776)

In [82]:
knn_eval(X, y, select_n_features=True)

500
| KNN | 0.79 +/- 0.02 | 0.78 +/- 0.03 | 0.77 +/- 0.03 |
study.best_value=0.7731821746220054, study.best_params={'n_neighbors': 6, 'n_features': 3755}

## concat before

| Model | ACC | F1 macro | F1 weighted |
| --- | --- | --- | --- | 
| KNN (mrna) | 0.84 +/- 0.02 | 0.83 +/- 0.02 | 0.83 +/- 0.02 |
| KNN (mrna, mirna) | 0.84 +/- 0.02 | 0.83 +/- 0.03 | 0.84 +/- 0.02 |
| KNN (mrna, mirna, meth) | 0.80 +/- 0.04 | 0.78 +/- 0.06 | 0.79 +/- 0.05 |
| KNN (mrna, mirna, meth, cnv) | 0.80 +/- 0.04 | 0.78 +/- 0.05 | 0.79 +/- 0.05 |

## concat after (KNN)

| subset | weighted f1 |
| --- | --- |
| mrna | 0.83 +/- 0.01 |
| mirna | 0.68 +/- 0.04 |
| meth | 0.61 +/- 0.07 |
| cnv | 0.55 +/- 0.03 |
| mrna, mirna | 0.82 +/- 0.03 |
| mrna, mirna, meth | 0.78 +/- 0.03 |
| mrna, mirna, meth, cnv | 0.72 +/- 0.03 |

In [83]:
svm_eval(X, y, select_n_features=True, n_trials=20, n_features_preselect=10000)

Trial 1 / 20
| SVM | 0.83 +/- 0.01 | 0.83 +/- 0.02 | 0.83 +/- 0.01 |
Trial 2 / 20
Trial 3 / 20
Pruning trial
Trial 4 / 20
Pruning trial
Trial 5 / 20

KeyboardInterrupt:

In [ ]:
| LIN SVM (mrna) | 0.83 +/- 0.01 | 0.83 +/- 0.01 | 0.83 +/- 0.01 |
| LIN SVM (all) | 0.83 +/- 0.01 | 0.83 +/- 0.02 | 0.83 +/- 0.01 |

In [84]:
xgboost_eval(X, y, n_trials=20)

0 / 20
ACC: [0.81443299 0.75257732 0.77319588 0.79166667 0.79166667]
F1M: [0.75649166 0.7171824  0.73991438 0.78683275 0.77552635]
F1W: [0.81636058 0.74620681 0.76904404 0.79061621 0.79111649]
 XGBoost val | 0.78 +/- 0.02 | 0.72 +/- 0.05 | 0.78 +/- 0.03 |
| XGBoost | 0.78 +/- 0.02 | 0.76 +/- 0.02 | 0.78 +/- 0.02 |
1 / 20
ACC: [0.75257732 0.8556701  0.7628866  0.79166667 0.78125   ]
F1M: [0.73299234 0.86114947 0.76676267 0.76812008 0.7829877 ]
F1W: [0.75819309 0.85681546 0.7537579  0.78380265 0.78443131]
 XGBoost val | 0.79 +/- 0.02 | 0.76 +/- 0.05 | 0.79 +/- 0.03 |
| XGBoost | 0.79 +/- 0.04 | 0.78 +/- 0.04 | 0.79 +/- 0.04 |
2 / 20
ACC: [0.8556701  0.8556701  0.86597938 0.875      0.8125    ]
F1M: [0.83637566 0.85521223 0.85638371 0.87290121 0.8058126 ]
F1W: [0.85863198 0.85355805 0.86391041 0.87154538 0.81443624]
 XGBoost val | 0.85 +/- 0.05 | 0.84 +/- 0.03 | 0.85 +/- 0.05 |
| XGBoost | 0.85 +/- 0.02 | 0.85 +/- 0.02 | 0.85 +/- 0.02 |
3 / 20
Pruning trial
4 / 20
ACC: [0.81443299 0.89690722 0.84536082 0.86458333 0.86458333]
F1M: [0.78959474 0.90148423 0.83195554 0.87210296 0.86128907]
F1W: [0.81804632 0.89770671 0.84151982 0.86134923 0.86519851]
 XGBoost val | 0.88 +/- 0.03 | 0.86 +/- 0.04 | 0.88 +/- 0.03 |
| XGBoost | 0.86 +/- 0.03 | 0.85 +/- 0.04 | 0.86 +/- 0.03 |
5 / 20
ACC: [0.83505155 0.87628866 0.86597938 0.85416667 0.875     ]
F1M: [0.82116402 0.88278321 0.86108457 0.86997393 0.87963752]
F1W: [0.83866798 0.87848435 0.86448692 0.85003696 0.87572497]
 XGBoost val | 0.87 +/- 0.03 | 0.85 +/- 0.03 | 0.87 +/- 0.03 |
| XGBoost | 0.86 +/- 0.02 | 0.86 +/- 0.02 | 0.86 +/- 0.02 |
6 / 20
Pruning trial
7 / 20
ACC: [0.8556701  0.89690722 0.89690722 0.90625    0.86458333]
F1M: [0.84855294 0.89679169 0.89661391 0.91999312 0.86128907]
F1W: [0.85966645 0.8965925  0.89507918 0.90481356 0.86519851]
 XGBoost val | 0.89 +/- 0.02 | 0.88 +/- 0.02 | 0.89 +/- 0.02 |
| XGBoost | 0.88 +/- 0.02 | 0.88 +/- 0.03 | 0.88 +/- 0.02 |
8 / 20
Pruning trial
9 / 20
Pruning trial
10 / 20
Pruning trial
11 / 20
12 / 20
Pruning trial
13 / 20
14 / 20

KeyboardInterrupt:

| XGBoost (default) | 0.80 +/- 0.02 | 0.80 +/- 0.04 | 0.80 +/- 0.03 |  
| XGBoost (tuned, mrna only) | 0.88 +/- 0.02 | 0.88 +/- 0.03 | 0.88 +/- 0.02 |  
| XGBoost (tuned, all) | 0.88 +/- 0.03 | 0.87 +/- 0.04 | 0.88 +/- 0.03 |

In [85]:
mlp_eval(X, y, reg_type=None, n_trials=15)

Trial 0 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.79591835 0.83673471 0.77551019 0.85416669 0.79166669]
[0.77526596 0.85965198 0.78898936 0.86764706 0.77646025]
[0.79027356 0.84042536 0.77389926 0.84272876 0.79224308]
{'acc': 0.8107993245124817, 'f1_macro': 0.8136029217249272, 'f1_weighted': 0.8079140029225609, 'acc_std': 0.0296182263899997, 'f1_macro_std': 0.04122235322546163, 'f1_weighted_std': 0.028223468685685985}
Trial 1 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.79591835 0.89795917 0.73469388 0.85416669 0.79166669]
[0.75640732 0.90118577 0.72564103 0.86150794 0.77787264]
[0.78696119 0.89658788 0.69911041 0.84794974 0.79150065]
Trial 2 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Pruning trial after 3 evals, cause 0.32279998122428116 < 0.8079140029225609
[0.2857143  0.44897959 0.40816328 0.         0.        ]
[0.20712582 0.26785714 0.22222222 0.         0.        ]
[0.26659122 0.37900875 0.33786848 0.         0.        ]
Trial 3 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.83673471 0.83673471 0.77551019 0.89583331 0.8125    ]
[0.81616833 0.85505051 0.76675725 0.90870032 0.82409812]
[0.8370059  0.83739435 0.76863354 0.88744182 0.81156205]
{'acc': 0.8314625859260559, 'f1_macro': 0.8341549051111663, 'f1_weighted': 0.8284075317305157, 'acc_std': 0.039215892833136784, 'f1_macro_std': 0.046820391970995696, 'f1_weighted_std': 0.03872064625051936}
Trial 4 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.85714287 0.81632656 0.77551019 0.89583331 0.8125    ]
[0.83909091 0.84018922 0.78125    0.90870032 0.82409812]
[0.85721707 0.82107808 0.77040816 0.88744182 0.81156205]
{'acc': 0.8314625859260559, 'f1_macro': 0.8386657155930706, 'f1_weighted': 0.829541436277615, 'acc_std': 0.04128538897680321, 'f1_macro_std': 0.041027130314791056, 'f1_weighted_std': 0.04002505625605267}
Trial 5 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.83673471 0.83673471 0.73469388 0.85416669 0.8125    ]
[0.81616833 0.85505051 0.75160825 0.85741314 0.82409812]
[0.8370059  0.83739435 0.72848722 0.84869854 0.81156205]
Trial 6 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Pruning trial after 3 evals, cause 0.6952239329840646 < 0.829541436277615
[0.63265306 0.75510204 0.71428573 0.         0.        ]
[0.63317118 0.75380314 0.71571429 0.         0.        ]
[0.63238004 0.75806782 0.70130224 0.         0.        ]
Trial 7 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.79591835 0.81632656 0.83673471 0.85416669 0.85416669]
[0.76659012 0.84181818 0.85641026 0.87716813 0.85600289]
[0.80212421 0.81907236 0.83718821 0.85395226 0.85338745]
{'acc': 0.8314625978469848, 'f1_macro': 0.83959791455821, 'f1_weighted': 0.8331448961171756, 'acc_std': 0.022588669894438192, 'f1_macro_std': 0.03820567282222563, 'f1_weighted_std': 0.020096642553496517}
Trial 8 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Pruning trial after 3 evals, cause 0.6900178934544463 < 0.8331448961171756
[0.69387758 0.71428573 0.71428573 0.         0.        ]
[0.60841609 0.72815724 0.68330549 0.         0.        ]
[0.65985355 0.72018224 0.68626782 0.         0.        ]
Trial 9 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.83673471 0.81632656 0.75510204 0.89583331 0.8125    ]
[0.80034965 0.83575525 0.76386364 0.91388045 0.82409812]
[0.83485086 0.81834789 0.746141   0.89171733 0.81156205]
Trial 10 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Pruning trial after 4 evals, cause 0.7821437452576866 < 0.8331448961171756
[0.81632656 0.77551019 0.75510204 0.89583331 0.        ]
[0.77922078 0.78946078 0.790157   0.90752551 0.        ]
[0.81994876 0.77695078 0.7495317  0.89407951 0.        ]
Trial 11 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.81632656 0.83673471 0.79591835 0.89583331 0.8125    ]
[0.7875969  0.83481555 0.8223128  0.90978391 0.82409812]
[0.81718083 0.83197548 0.79130928 0.89220188 0.81156205]
Trial 12 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.85714287 0.85714287 0.81632656 0.89583331 0.8125    ]
[0.82922481 0.86745815 0.83874396 0.90870032 0.82409812]
[0.85928809 0.85827691 0.81506852 0.88744182 0.81156205]
{'acc': 0.8477891206741333, 'f1_macro': 0.85364507263082, 'f1_weighted': 0.8463274765970945, 'acc_std': 0.03071951953475861, 'f1_macro_std': 0.03134739635904108, 'f1_weighted_std': 0.028937563057151734}
Trial 13 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Pruning trial after 4 evals, cause 0.7686571166657155 < 0.8463274765970945
[0.79591835 0.85714287 0.67346936 0.77083331 0.        ]
[0.79496666 0.86313503 0.6175     0.77390686 0.        ]
[0.7993236  0.85515115 0.6514966  0.76472871 0.        ]
Trial 14 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.81632656 0.85714287 0.81632656 0.91666669 0.8125    ]
[0.7875969  0.86745815 0.84343434 0.92916667 0.82409812]
[0.81718083 0.85827691 0.8185941  0.91180556 0.81156205]
study.best_value=2.547761669902048, study.best_params={'lr': 0.000273735612070389, 'l1_lambda': 0.008626656794915342, 'l2_lambda': 2.425254143849236e-05, 'proj_dim': 254, 'hidden_channels': 89, 'n_features': 2390}
| MLP regularization : None | 0.85 +/- 0.03 | 0.85 +/- 0.03 | 0.85 +/- 0.03 |

| MLP no reg | 0.86 +/- 0.06 | 0.83 +/- 0.09 | 0.86 +/- 0.05 |  
| MLP no reg (mRNA only) | 0.87 +/- 0.04 | 0.85 +/- 0.05 | 0.87 +/- 0.04 |  
| MLP no reg (mRNA only) | 0.87 +/- 0.04 | 0.87 +/- 0.06 | 0.87 +/- 0.04 |

In [86]:
mlp_eval(X, y, reg_type="l1", n_trials=15)

Trial 0 / 15
Eval 1 / 5
torch.Size([386, 1356])
torch.Size([48, 1356])
torch.Size([49, 1356])
Eval 2 / 5
torch.Size([386, 1356])
torch.Size([48, 1356])
torch.Size([49, 1356])
Eval 3 / 5
torch.Size([386, 1356])
torch.Size([48, 1356])
torch.Size([49, 1356])
Eval 4 / 5
torch.Size([387, 1356])
torch.Size([48, 1356])
torch.Size([48, 1356])
Eval 5 / 5
torch.Size([387, 1356])
torch.Size([48, 1356])
torch.Size([48, 1356])
[0.46938777 0.71428573 0.65306121 0.60416669 0.52083331]
[0.47993159 0.75023034 0.67177889 0.54740575 0.52323718]
[0.47600338 0.71219225 0.64396686 0.58800703 0.53427707]
{'acc': 0.5923469424247741, 'f1_macro': 0.5945167513955909, 'f1_weighted': 0.5908893179886208, 'acc_std': 0.08823622191961213, 'f1_macro_std': 0.10064406970572103, 'f1_weighted_std': 0.08239376048341274}
Trial 1 / 15
Eval 1 / 5
torch.Size([386, 1506])
torch.Size([48, 1506])
torch.Size([49, 1506])
Eval 2 / 5
torch.Size([386, 1506])
torch.Size([48, 1506])
torch.Size([49, 1506])
Eval 3 / 5
torch.Size([386, 1506])
torch.Size([48, 1506])
torch.Size([49, 1506])
Eval 4 / 5
torch.Size([387, 1506])
torch.Size([48, 1506])
torch.Size([48, 1506])
Eval 5 / 5
torch.Size([387, 1506])
torch.Size([48, 1506])
torch.Size([48, 1506])
[0.83673471 0.83673471 0.75510204 0.89583331 0.8125    ]
[0.80034965 0.85505051 0.77083333 0.90978391 0.82409812]
[0.83485086 0.83739435 0.75170068 0.89220188 0.81156205]
{'acc': 0.8273809552192688, 'f1_macro': 0.8320231052794078, 'f1_weighted': 0.8255419650377634, 'acc_std': 0.045401311727902995, 'f1_macro_std': 0.04772254333171382, 'f1_weighted_std': 0.04542830044774263}
Trial 2 / 15
Eval 1 / 5
torch.Size([386, 2523])
torch.Size([48, 2523])
torch.Size([49, 2523])
Eval 2 / 5
torch.Size([386, 2523])
torch.Size([48, 2523])
torch.Size([49, 2523])

Exception ignored in: <function _releaseLock at 0x77cf631bcea0>
Traceback (most recent call last):
  File "/home/lubojjan/micromamba/envs/diploma/lib/python3.12/logging/__init__.py", line 243, in _releaseLock
    def _releaseLock():

KeyboardInterrupt:

Eval 3 / 5
torch.Size([386, 2523])
torch.Size([48, 2523])
torch.Size([49, 2523])

| MLP l1 reg | 0.87 +/- 0.06 | 0.85 +/- 0.09 | 0.87 +/- 0.05 |  
| MLP l1 reg (mrna only) | 0.86 +/- 0.03 | 0.85 +/- 0.04 | 0.86 +/- 0.03 |  
| MLP l1 reg (mrna only) | 0.86 +/- 0.07 | 0.86 +/- 0.08 | 0.86 +/- 0.07 |  
| MLP l1 reg (mrna only, var) | 0.84 +/- 0.06 | 0.84 +/- 0.07 | 0.84 +/- 0.06 |


{'acc': 0.867463231086731, 'f1_macro': 0.8446657147200625, 'f1_weighted': 0.8687115181280782, 'acc_std': 0.0655361141104709, 'f1_macro_std': 0.09939143723563133, 'f1_weighted_std': 0.05932617979442903}

mrna only study.best_value=2.577811014967633, study.best_params={'lr': 0.00012898079159581874, 'l1_lambda': 0.00047366984296337946, 'l2_lambda': 0.0008509490658518463, 'proj_dim': 80, 'hidden_channels': 94}

In [7]:
mlp_eval(X, y, reg_type="inner_mat", n_trials=15)

Trial 0 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.79591835 0.81632656 0.79591835 0.875      0.77083331]
[0.76975524 0.81948215 0.80430157 0.8947096  0.77475158]
[0.7956044  0.81951139 0.78980158 0.87082516 0.77207543]
{'acc': 0.8107993125915527, 'f1_macro': 0.8126000300289199, 'f1_weighted': 0.8095635923557335, 'acc_std': 0.035192175733458814, 'f1_macro_std': 0.04500308927522579, 'f1_weighted_std': 0.034183905959255544}
Trial 1 / 15
Eval 1 / 5
Eval 2 / 5

| MLP inner prod | 0.86 +/- 0.05 | 0.85 +/- 0.06 | 0.85 +/- 0.05 |  
| MLP (mrna only) | 0.87 +/- 0.06 | 0.87 +/- 0.07 | 0.87 +/- 0.06 |  
| MLP (mrna only) | 0.87 +/- 0.05 | 0.86 +/- 0.06 | 0.87 +/- 0.05 |  

{'acc': 0.8560374259948731, 'f1_macro': 0.8531890166223708, 'f1_weighted': 0.8540459975191783, 'acc_std': 0.05063744215757385, 'f1_macro_std': 0.06194529762727774, 'f1_weighted_std': 0.049910632703314174}

mrna only study.best_value=2.607328324144426, study.best_params={'lr': 8.077069025405151e-05, 'l1_lambda': 0.0004400516634407218, 'l2_lambda': 5.624746318975069e-05, 'proj_dim': 145, 'hidden_channels': 243}

# Results

| Method | ACC | F1 | F1 Weighted |
| --- | --- | --- | --- |
| KNN | 0.80 +/- 0.04 | 0.79 +/- 0.04 | 0.79 +/- 0.04 |
| LIN SVM w RFE | 0.84 +/- 0.01 | 0.84 +/- 0.02 | 0.84 +/- 0.01 |
| XGBoost | 0.88 +/- 0.02 | 0.88 +/- 0.03 | 0.88 +/- 0.02 |
| MLP no reg | 0.86 +/- 0.06 | 0.83 +/- 0.09 | 0.86 +/- 0.05 |
| MLP l1 reg | 0.87 +/- 0.06 | 0.85 +/- 0.09 | 0.87 +/- 0.05 |
| MLP inner prod | 0.86 +/- 0.05 | 0.85 +/- 0.06 | 0.85 +/- 0.05 |
| MOGONET (mrna, cnv, mirna) | 0.766 ± 0.025 | 0.742 ± 0.027| 0.768 ± 0.024|
| MOGONET (mrna, meth, mirna) | 0.824 ± 0.029 | 0.812 ± 0.039| 0.824 ± 0.032|
| MOGONET GAT (mrna only) | 0.86 +/- 0.04 | 0.84 +/- 0.05 | 0.86 +/- 0.04 |

In [133]:
# prepare 5 folds for cross validation
skf = StratifiedKFold(n_splits=5)

train_indices = []
val_indices = []
test_indices = []

for train_index, test_index in skf.split(X, y):
    train_indices.append(train_index)
    val_index, test_index = train_test_split(test_index, test_size=0.5, stratify=y[test_index])
    val_indices.append(val_index)
    test_indices.append(test_index)

best_val = torch.zeros(5, 3)
best_test = torch.zeros(5, 3)

In [150]:
mrna_mask = class_variational_selection(mrna_X[train_idx], y[train_idx], n_features=2000)

mrna_X_filt = torch.tensor(mrna_X[:, mrna_mask], dtype=torch.float32)

mrna_eps = 0.95
# meth_eps = 0.997
# cnv_eps = 0.9998
# mirna_eps = 0.962

# build adjacency matrix for each data type
A_mrna = cosine_similarity_matrix(mrna_X_filt)
A_mrna_bin = torch.where(A_mrna > mrna_eps, 1, 0) # - torch.eye(A_mrna.shape[0])
print(f"mrna mean degree {A_mrna_bin.sum(axis=1, dtype=torch.float32).mean()}")
print(
    f"Isolated samples = {(A_mrna_bin.sum(dim=1) == 1).sum()}"
)

mrna mean degree 32.97101593017578
Isolated samples = 131

In [108]:
from bipartite_gnn.graph_building import threshold_matrix

A_mrna = A_mrna.to(torch.float32)

threshold_matrix(A_mrna, self_connections=True, target_avg_degree=20)

0.75 tensor(482.8551)
0.875 tensor(370.6605)
0.9375 tensor(93.3520)
0.96875 tensor(2.1925)
0.953125 tensor(23.1408)
0.9609375 tensor(7.9689)
0.95703125 tensor(14.0062)
0.955078125 tensor(18.1180)
0.9541015625 tensor(20.3085)
Isolated samples = 0, avg degree = 20.308488845825195

tensor([[1., 1., 1.,  ..., 0., 0., 1.],
        [1., 1., 1.,  ..., 0., 0., 1.],
        [1., 1., 1.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 1., 0.],
        [1., 1., 0.,  ..., 0., 0., 1.]])

In [161]:
for i in range(len(train_indices)):
    train_idx = train_indices[i]
    val_idx = val_indices[i]
    test_idx = test_indices[i]

    mrna_gene_names = mrna[:, 0].to_numpy()
    meth_gene_names = meth[:, 0].to_numpy()
    cna_gene_names = cnv[:, 0].to_numpy()
    mirna_gene_names = mirna[:, 0].to_numpy()

    mrna_mask = class_variational_selection(mrna_X[train_idx], y[train_idx], n_features=2000)
    meth_mask = class_variational_selection(meth_X[train_idx], y[train_idx], n_features=1000)
    cnv_mask = class_variational_selection(cnv_X[train_idx], y[train_idx], n_features=1000)
    mirna_mask = class_variational_selection(mirna_X[train_idx], y[train_idx], n_features=200)

    mrna_X_filt = mrna_X[:, mrna_mask]
    meth_X_filt = meth_X[:, meth_mask]
    cnv_X_filt = cnv_X[:, cnv_mask]
    mirna_X_filt = mirna_X[:, mirna_mask]

    # minmax scaling
    mms = MinMaxScaler()
    mms.fit(mrna_X_filt[train_idx])
    mrna_X_filt = torch.tensor(mms.transform(mrna_X_filt), dtype=torch.float32)

    mms = MinMaxScaler()
    mms.fit(meth_X_filt[train_idx])
    meth_X_filt = torch.tensor(mms.transform(meth_X_filt), dtype=torch.float32)

    mms = MinMaxScaler()
    mms.fit(cnv_X_filt[train_idx])
    cnv_X_filt = torch.tensor(mms.transform(cnv_X_filt), dtype=torch.float32)

    mms = MinMaxScaler()
    mms.fit(mirna_X_filt[train_idx])
    mirna_X_filt = torch.tensor(mms.transform(mirna_X_filt), dtype=torch.float32)


    mrna_gene_names = mrna_gene_names[mrna_mask]
    meth_gene_names = meth_gene_names[meth_mask]
    cna_gene_names = cna_gene_names[cnv_mask]
    mirna_gene_names = mirna_gene_names[mirna_mask]

    ##### BUILDING GRAPH #####

    # build graph for mogonet
    data = pyg.data.HeteroData()

    mrna_eps = 0.933
    meth_eps = 0.99
    cnv_eps = 0.99
    mirna_eps = 0.962

    # build adjacency matrix for each data type
    A_mrna = cosine_similarity_matrix(mrna_X_filt)
    A_mrna_bin = torch.where(A_mrna > mrna_eps, 1, 0) - torch.eye(A_mrna.shape[0])
    print(f"mrna mean degree {A_mrna_bin.sum(axis=1, dtype=torch.float32).mean()}")
    print(
        f"Isolated samples = {(A_mrna_bin.sum(dim=1) == 0).sum()}"
    )

    data['mrna'].x = mrna_X_filt
    data['mrna'].edge_index = dense_to_coo(A_mrna_bin)

    A_meth = cosine_similarity_matrix(meth_X_filt)
    A_meth_bin = torch.where(A_meth > meth_eps, 1, 0) - torch.eye(A_mrna.shape[0])
    A_meth_bin.sum(axis=1, dtype=torch.float32).mean()
    print(f"meth mean degree {A_meth_bin.sum(axis=1, dtype=torch.float32).mean()}")

    data['meth'].x = meth_X_filt
    data['meth'].edge_index = dense_to_coo(A_meth_bin)

    A_cnv = cosine_similarity_matrix(cnv_X_filt)
    A_cnv_bin = torch.where(A_cnv > cnv_eps, 1, 0) - torch.eye(A_mrna.shape[0])
    A_cnv_bin.sum(axis=1, dtype=torch.float32).mean() 
    print(f"cnv mean degree {A_cnv_bin.sum(axis=1, dtype=torch.float32).mean()}")

    data['cnv'].x = cnv_X_filt
    data['cnv'].edge_index = dense_to_coo(A_cnv_bin)

    A_mirna = cosine_similarity_matrix(mirna_X_filt)
    A_mirna_bin = torch.where(A_mirna > mirna_eps, 1, 0) - torch.eye(A_mrna.shape[0])
    A_mirna_bin.sum(axis=1, dtype=torch.float32).mean()
    print(f"mirna mean degree {A_mirna_bin.sum(axis=1, dtype=torch.float32).mean()}")

    data['mirna'].x = mirna_X_filt
    data['mirna'].edge_index = dense_to_coo(A_mirna_bin)

    data.y = torch.tensor(y)

    data.train_mask = torch.tensor(train_idx)
    data.val_mask = torch.tensor(val_idx)
    data.test_mask = torch.tensor(test_idx)

    ##### TRAINING MODEL #####

    model = MOGONET(
        omics=data.x_dict.keys(),
        in_channels=[data.x_dict[omics].shape[1] for omics in data.x_dict.keys()],
        hidden_channels=300,
        num_classes=4,
        encoder_type="gat",
        dropout=0.0,
    )

    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3, weight_decay=5e-4)

    ccounts = torch.unique(data.y[data.train_mask], return_counts=True)[1]
    inv_w = 1.0 / ccounts.float()
    class_weights = inv_w / inv_w.sum()

    trainer = GNNTrainer(
        model=model,
        loss_fn=torch.nn.CrossEntropyLoss(weight=class_weights),
        optimizer=optimizer,
        scheduler=torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=15, min_lr=1e-5),
        params={
            "l1_lambda": None,
        }
    )

    bp = trainer.train(
        data=data,
        epochs=500,
        log_interval=50,
    )

    # print(bp)
    best_val[i] = bp[0]
    best_test[i] = bp[1]

mrna mean degree 10.786749839782715
Isolated samples = 257
meth mean degree 59.209110260009766
cnv mean degree 12.078675270080566
mirna mean degree 8.844720840454102
Epoch: 050:
Train Loss: 0.3424, Train Acc: 0.8394, Train F1 Macro: 0.8647, Train F1 Weighted: 0.8417
Val Loss: 0.5198, Val Acc: 0.7917, Val F1 Macro: 0.7911, Val F1 Weighted: 0.7990
Test Loss: 0.4351, Test Acc: 0.7959, Test F1 Macro: 0.8019, Test F1 Weighted: 0.8043
##################################################
Epoch: 100:
Train Loss: 0.0992, Train Acc: 0.9663, Train F1 Macro: 0.9729, Train F1 Weighted: 0.9663
Val Loss: 1.0371, Val Acc: 0.8750, Val F1 Macro: 0.8375, Val F1 Weighted: 0.8722
Test Loss: 0.3365, Test Acc: 0.8776, Test F1 Macro: 0.8685, Test F1 Weighted: 0.8800
##################################################
Epoch: 150:
Train Loss: 0.0783, Train Acc: 0.9715, Train F1 Macro: 0.9770, Train F1 Weighted: 0.9715
Val Loss: 1.2223, Val Acc: 0.8750, Val F1 Macro: 0.8375, Val F1 Weighted: 0.8722
Test Loss: 0.3490, Test Acc: 0.8776, Test F1 Macro: 0.8685, Test F1 Weighted: 0.8800
##################################################
Epoch: 200:
Train Loss: 0.0750, Train Acc: 0.9715, Train F1 Macro: 0.9770, Train F1 Weighted: 0.9715
Val Loss: 1.2567, Val Acc: 0.8750, Val F1 Macro: 0.8375, Val F1 Weighted: 0.8722
Test Loss: 0.3547, Test Acc: 0.8776, Test F1 Macro: 0.8685, Test F1 Weighted: 0.8800
##################################################
Epoch: 250:
Train Loss: 0.0725, Train Acc: 0.9715, Train F1 Macro: 0.9770, Train F1 Weighted: 0.9715
Val Loss: 1.2835, Val Acc: 0.8750, Val F1 Macro: 0.8375, Val F1 Weighted: 0.8722
Test Loss: 0.3605, Test Acc: 0.8776, Test F1 Macro: 0.8685, Test F1 Weighted: 0.8800
##################################################
Epoch: 300:
Train Loss: 0.0700, Train Acc: 0.9715, Train F1 Macro: 0.9770, Train F1 Weighted: 0.9715
Val Loss: 1.3198, Val Acc: 0.8542, Val F1 Macro: 0.8177, Val F1 Weighted: 0.8519
Test Loss: 0.3665, Test Acc: 0.8776, Test F1 Macro: 0.8685, Test F1 Weighted: 0.8800
##################################################
Epoch: 350:
Train Loss: 0.0673, Train Acc: 0.9715, Train F1 Macro: 0.9770, Train F1 Weighted: 0.9715
Val Loss: 1.3656, Val Acc: 0.8542, Val F1 Macro: 0.8177, Val F1 Weighted: 0.8519
Test Loss: 0.3721, Test Acc: 0.8776, Test F1 Macro: 0.8685, Test F1 Weighted: 0.8800
##################################################
Epoch: 400:
Train Loss: 0.0644, Train Acc: 0.9715, Train F1 Macro: 0.9770, Train F1 Weighted: 0.9715
Val Loss: 1.4303, Val Acc: 0.8542, Val F1 Macro: 0.8177, Val F1 Weighted: 0.8519
Test Loss: 0.3816, Test Acc: 0.8776, Test F1 Macro: 0.8685, Test F1 Weighted: 0.8800
##################################################
Epoch: 450:
Train Loss: 0.0615, Train Acc: 0.9715, Train F1 Macro: 0.9770, Train F1 Weighted: 0.9715
Val Loss: 1.4575, Val Acc: 0.8542, Val F1 Macro: 0.8177, Val F1 Weighted: 0.8519
Test Loss: 0.3902, Test Acc: 0.8980, Test F1 Macro: 0.8832, Test F1 Weighted: 0.8996
##################################################
Epoch: 500:
Train Loss: 0.0589, Train Acc: 0.9741, Train F1 Macro: 0.9790, Train F1 Weighted: 0.9741
Val Loss: 1.4871, Val Acc: 0.8542, Val F1 Macro: 0.8177, Val F1 Weighted: 0.8519
Test Loss: 0.3949, Test Acc: 0.8980, Test F1 Macro: 0.8832, Test F1 Weighted: 0.8996
##################################################
mrna mean degree 11.403726577758789
Isolated samples = 248
meth mean degree 55.196685791015625
cnv mean degree 16.30641746520996
mirna mean degree 15.217391014099121
Epoch: 050:
Train Loss: 0.5188, Train Acc: 0.6943, Train F1 Macro: 0.7450, Train F1 Weighted: 0.6872
Val Loss: 0.7306, Val Acc: 0.6250, Val F1 Macro: 0.6263, Val F1 Weighted: 0.6356
Test Loss: 0.6234, Test Acc: 0.7143, Test F1 Macro: 0.7293, Test F1 Weighted: 0.7210
##################################################
Epoch: 100:
Train Loss: 0.1221, Train Acc: 0.9456, Train F1 Macro: 0.9548, Train F1 Weighted: 0.9455
Val Loss: 0.6572, Val Acc: 0.7917, Val F1 Macro: 0.7940, Val F1 Weighted: 0.7906
Test Loss: 0.2465, Test Acc: 0.8367, Test F1 Macro: 0.8554, Test F1 Weighted: 0.8440
##################################################
Epoch: 150:
Train Loss: 0.0699, Train Acc: 0.9819, Train F1 Macro: 0.9849, Train F1 Weighted: 0.9818
Val Loss: 0.7193, Val Acc: 0.7500, Val F1 Macro: 0.7468, Val F1 Weighted: 0.7462
Test Loss: 0.2312, Test Acc: 0.8776, Test F1 Macro: 0.9066, Test F1 Weighted: 0.8793
##################################################
Epoch: 200:
Train Loss: 0.0648, Train Acc: 0.9819, Train F1 Macro: 0.9849, Train F1 Weighted: 0.9818
Val Loss: 0.7351, Val Acc: 0.7500, Val F1 Macro: 0.7468, Val F1 Weighted: 0.7462
Test Loss: 0.2379, Test Acc: 0.8776, Test F1 Macro: 0.9066, Test F1 Weighted: 0.8793
##################################################
Epoch: 250:
Train Loss: 0.0628, Train Acc: 0.9819, Train F1 Macro: 0.9849, Train F1 Weighted: 0.9818
Val Loss: 0.7346, Val Acc: 0.7500, Val F1 Macro: 0.7468, Val F1 Weighted: 0.7462
Test Loss: 0.2368, Test Acc: 0.8776, Test F1 Macro: 0.9066, Test F1 Weighted: 0.8793
##################################################
Epoch: 300:
Train Loss: 0.0601, Train Acc: 0.9845, Train F1 Macro: 0.9869, Train F1 Weighted: 0.9844
Val Loss: 0.7439, Val Acc: 0.7917, Val F1 Macro: 0.7726, Val F1 Weighted: 0.7833
Test Loss: 0.2357, Test Acc: 0.8776, Test F1 Macro: 0.9066, Test F1 Weighted: 0.8793
##################################################
Epoch: 350:
Train Loss: 0.0576, Train Acc: 0.9845, Train F1 Macro: 0.9869, Train F1 Weighted: 0.9844
Val Loss: 0.7597, Val Acc: 0.7917, Val F1 Macro: 0.7726, Val F1 Weighted: 0.7833
Test Loss: 0.2411, Test Acc: 0.8776, Test F1 Macro: 0.9066, Test F1 Weighted: 0.8793
##################################################
Epoch: 400:
Train Loss: 0.0553, Train Acc: 0.9845, Train F1 Macro: 0.9869, Train F1 Weighted: 0.9844
Val Loss: 0.7732, Val Acc: 0.7917, Val F1 Macro: 0.7726, Val F1 Weighted: 0.7833
Test Loss: 0.2458, Test Acc: 0.8776, Test F1 Macro: 0.9066, Test F1 Weighted: 0.8793
##################################################
Epoch: 450:
Train Loss: 0.0531, Train Acc: 0.9870, Train F1 Macro: 0.9889, Train F1 Weighted: 0.9870
Val Loss: 0.7881, Val Acc: 0.7917, Val F1 Macro: 0.7726, Val F1 Weighted: 0.7833
Test Loss: 0.2518, Test Acc: 0.8776, Test F1 Macro: 0.9066, Test F1 Weighted: 0.8793
##################################################
Epoch: 500:
Train Loss: 0.0509, Train Acc: 0.9870, Train F1 Macro: 0.9889, Train F1 Weighted: 0.9870
Val Loss: 0.8029, Val Acc: 0.7917, Val F1 Macro: 0.7726, Val F1 Weighted: 0.7833
Test Loss: 0.2590, Test Acc: 0.8776, Test F1 Macro: 0.9066, Test F1 Weighted: 0.8793
##################################################
mrna mean degree 11.196687698364258
Isolated samples = 254
meth mean degree 59.90061950683594
cnv mean degree 9.6314697265625
mirna mean degree 13.068323135375977
Epoch: 050:
Train Loss: 0.3215, Train Acc: 0.8342, Train F1 Macro: 0.8633, Train F1 Weighted: 0.8370
Val Loss: 0.5755, Val Acc: 0.8125, Val F1 Macro: 0.8360, Val F1 Weighted: 0.8132
Test Loss: 1.0353, Test Acc: 0.7959, Test F1 Macro: 0.7930, Test F1 Weighted: 0.7897
##################################################
Epoch: 100:
Train Loss: 0.0905, Train Acc: 0.9663, Train F1 Macro: 0.9722, Train F1 Weighted: 0.9663
Val Loss: 1.6367, Val Acc: 0.8750, Val F1 Macro: 0.8815, Val F1 Weighted: 0.8770
Test Loss: 1.1029, Test Acc: 0.8776, Test F1 Macro: 0.8746, Test F1 Weighted: 0.8783
##################################################
Epoch: 150:
Train Loss: 0.0726, Train Acc: 0.9767, Train F1 Macro: 0.9808, Train F1 Weighted: 0.9766
Val Loss: 1.7538, Val Acc: 0.8750, Val F1 Macro: 0.8815, Val F1 Weighted: 0.8770
Test Loss: 1.0088, Test Acc: 0.8571, Test F1 Macro: 0.8582, Test F1 Weighted: 0.8571
##################################################
Epoch: 200:
Train Loss: 0.0693, Train Acc: 0.9767, Train F1 Macro: 0.9808, Train F1 Weighted: 0.9766
Val Loss: 1.7848, Val Acc: 0.8750, Val F1 Macro: 0.8815, Val F1 Weighted: 0.8770
Test Loss: 0.9793, Test Acc: 0.8571, Test F1 Macro: 0.8582, Test F1 Weighted: 0.8571
##################################################
Epoch: 250:
Train Loss: 0.0661, Train Acc: 0.9793, Train F1 Macro: 0.9828, Train F1 Weighted: 0.9792
Val Loss: 1.8160, Val Acc: 0.8750, Val F1 Macro: 0.8815, Val F1 Weighted: 0.8770
Test Loss: 0.9483, Test Acc: 0.8367, Test F1 Macro: 0.8411, Test F1 Weighted: 0.8355
##################################################
Epoch: 300:
Train Loss: 0.0630, Train Acc: 0.9793, Train F1 Macro: 0.9828, Train F1 Weighted: 0.9792
Val Loss: 1.8469, Val Acc: 0.8750, Val F1 Macro: 0.8815, Val F1 Weighted: 0.8770
Test Loss: 0.9147, Test Acc: 0.8367, Test F1 Macro: 0.8411, Test F1 Weighted: 0.8355
##################################################
Epoch: 350:
Train Loss: 0.0600, Train Acc: 0.9819, Train F1 Macro: 0.9853, Train F1 Weighted: 0.9818
Val Loss: 1.8750, Val Acc: 0.8750, Val F1 Macro: 0.8815, Val F1 Weighted: 0.8770
Test Loss: 0.8780, Test Acc: 0.8367, Test F1 Macro: 0.8411, Test F1 Weighted: 0.8355
##################################################
Epoch: 400:
Train Loss: 0.0571, Train Acc: 0.9819, Train F1 Macro: 0.9853, Train F1 Weighted: 0.9818
Val Loss: 1.9045, Val Acc: 0.8750, Val F1 Macro: 0.8815, Val F1 Weighted: 0.8770
Test Loss: 0.8511, Test Acc: 0.8367, Test F1 Macro: 0.8411, Test F1 Weighted: 0.8355
##################################################
Epoch: 450:
Train Loss: 0.0544, Train Acc: 0.9793, Train F1 Macro: 0.9833, Train F1 Weighted: 0.9792
Val Loss: 1.9349, Val Acc: 0.8750, Val F1 Macro: 0.8815, Val F1 Weighted: 0.8770
Test Loss: 0.8516, Test Acc: 0.8571, Test F1 Macro: 0.8759, Test F1 Weighted: 0.8546
##################################################
Epoch: 500:
Train Loss: 0.0518, Train Acc: 0.9819, Train F1 Macro: 0.9854, Train F1 Weighted: 0.9819
Val Loss: 1.9764, Val Acc: 0.8750, Val F1 Macro: 0.8815, Val F1 Weighted: 0.8770
Test Loss: 0.8810, Test Acc: 0.8571, Test F1 Macro: 0.8759, Test F1 Weighted: 0.8546
##################################################
mrna mean degree 11.888198852539062
Isolated samples = 249
meth mean degree 56.62525939941406
cnv mean degree 9.855072021484375
mirna mean degree 16.18633460998535
Epoch: 050:
Train Loss: 0.5919, Train Acc: 0.7261, Train F1 Macro: 0.7584, Train F1 Weighted: 0.7297
Val Loss: 0.7331, Val Acc: 0.7708, Val F1 Macro: 0.7718, Val F1 Weighted: 0.7715
Test Loss: 0.6704, Test Acc: 0.7917, Test F1 Macro: 0.8242, Test F1 Weighted: 0.8024
##################################################
Epoch: 100:
Train Loss: 0.0872, Train Acc: 0.9716, Train F1 Macro: 0.9777, Train F1 Weighted: 0.9714
Val Loss: 0.3659, Val Acc: 0.8958, Val F1 Macro: 0.8969, Val F1 Weighted: 0.8909
Test Loss: 0.8781, Test Acc: 0.7708, Test F1 Macro: 0.7613, Test F1 Weighted: 0.7587
##################################################
Epoch: 150:
Train Loss: 0.0524, Train Acc: 0.9819, Train F1 Macro: 0.9859, Train F1 Weighted: 0.9818
Val Loss: 0.2427, Val Acc: 0.8750, Val F1 Macro: 0.8905, Val F1 Weighted: 0.8776
Test Loss: 1.1194, Test Acc: 0.7500, Test F1 Macro: 0.7483, Test F1 Weighted: 0.7403
##################################################
Epoch: 200:
Train Loss: 0.0495, Train Acc: 0.9819, Train F1 Macro: 0.9859, Train F1 Weighted: 0.9818
Val Loss: 0.2267, Val Acc: 0.8958, Val F1 Macro: 0.9209, Val F1 Weighted: 0.8967
Test Loss: 1.1717, Test Acc: 0.7500, Test F1 Macro: 0.7483, Test F1 Weighted: 0.7403
##################################################
Epoch: 250:
Train Loss: 0.0485, Train Acc: 0.9819, Train F1 Macro: 0.9859, Train F1 Weighted: 0.9818
Val Loss: 0.2215, Val Acc: 0.8958, Val F1 Macro: 0.9209, Val F1 Weighted: 0.8967
Test Loss: 1.1916, Test Acc: 0.7500, Test F1 Macro: 0.7483, Test F1 Weighted: 0.7403
##################################################
Epoch: 300:
Train Loss: 0.0474, Train Acc: 0.9819, Train F1 Macro: 0.9859, Train F1 Weighted: 0.9818
Val Loss: 0.2178, Val Acc: 0.8958, Val F1 Macro: 0.9209, Val F1 Weighted: 0.8967
Test Loss: 1.2138, Test Acc: 0.7500, Test F1 Macro: 0.7483, Test F1 Weighted: 0.7403
##################################################
Epoch: 350:
Train Loss: 0.0461, Train Acc: 0.9819, Train F1 Macro: 0.9859, Train F1 Weighted: 0.9818
Val Loss: 0.2178, Val Acc: 0.8958, Val F1 Macro: 0.9209, Val F1 Weighted: 0.8967
Test Loss: 1.2364, Test Acc: 0.7500, Test F1 Macro: 0.7483, Test F1 Weighted: 0.7403
##################################################
Epoch: 400:
Train Loss: 0.0447, Train Acc: 0.9819, Train F1 Macro: 0.9859, Train F1 Weighted: 0.9818
Val Loss: 0.2157, Val Acc: 0.8958, Val F1 Macro: 0.9209, Val F1 Weighted: 0.8967
Test Loss: 1.2547, Test Acc: 0.7500, Test F1 Macro: 0.7483, Test F1 Weighted: 0.7403
##################################################
Epoch: 450:
Train Loss: 0.0434, Train Acc: 0.9819, Train F1 Macro: 0.9859, Train F1 Weighted: 0.9818
Val Loss: 0.2138, Val Acc: 0.8958, Val F1 Macro: 0.9209, Val F1 Weighted: 0.8967
Test Loss: 1.2714, Test Acc: 0.7500, Test F1 Macro: 0.7483, Test F1 Weighted: 0.7403
##################################################
Epoch: 500:
Train Loss: 0.0420, Train Acc: 0.9819, Train F1 Macro: 0.9859, Train F1 Weighted: 0.9818
Val Loss: 0.2121, Val Acc: 0.8958, Val F1 Macro: 0.9209, Val F1 Weighted: 0.8967
Test Loss: 1.2826, Test Acc: 0.7500, Test F1 Macro: 0.7366, Test F1 Weighted: 0.7306
##################################################
mrna mean degree 12.115942001342773
Isolated samples = 245
meth mean degree 58.881988525390625
cnv mean degree 31.548654556274414
mirna mean degree 18.799171447753906
Epoch: 050:
Train Loss: 0.7148, Train Acc: 0.7313, Train F1 Macro: 0.7150, Train F1 Weighted: 0.7341
Val Loss: 0.8357, Val Acc: 0.7292, Val F1 Macro: 0.7103, Val F1 Weighted: 0.7331
Test Loss: 1.1813, Test Acc: 0.7708, Test F1 Macro: 0.7904, Test F1 Weighted: 0.7764
##################################################
Epoch: 100:
Train Loss: 0.3348, Train Acc: 0.8760, Train F1 Macro: 0.8870, Train F1 Weighted: 0.8731
Val Loss: 0.5078, Val Acc: 0.7917, Val F1 Macro: 0.8074, Val F1 Weighted: 0.7891
Test Loss: 1.9545, Test Acc: 0.8333, Test F1 Macro: 0.8519, Test F1 Weighted: 0.8324
##################################################
Epoch: 150:
Train Loss: 0.2000, Train Acc: 0.9173, Train F1 Macro: 0.9308, Train F1 Weighted: 0.9180
Val Loss: 0.6008, Val Acc: 0.7708, Val F1 Macro: 0.7923, Val F1 Weighted: 0.7673
Test Loss: 2.1672, Test Acc: 0.8125, Test F1 Macro: 0.8369, Test F1 Weighted: 0.8114
##################################################
Epoch: 200:
Train Loss: 0.1899, Train Acc: 0.9251, Train F1 Macro: 0.9364, Train F1 Weighted: 0.9255
Val Loss: 0.6226, Val Acc: 0.7708, Val F1 Macro: 0.7923, Val F1 Weighted: 0.7673
Test Loss: 2.3337, Test Acc: 0.8125, Test F1 Macro: 0.8369, Test F1 Weighted: 0.8114
##################################################
Epoch: 250:
Train Loss: 0.1870, Train Acc: 0.9276, Train F1 Macro: 0.9385, Train F1 Weighted: 0.9281
Val Loss: 0.6305, Val Acc: 0.7708, Val F1 Macro: 0.7923, Val F1 Weighted: 0.7673
Test Loss: 2.3820, Test Acc: 0.8125, Test F1 Macro: 0.8369, Test F1 Weighted: 0.8114
##################################################
Epoch: 300:
Train Loss: 0.1837, Train Acc: 0.9276, Train F1 Macro: 0.9385, Train F1 Weighted: 0.9281
Val Loss: 0.6395, Val Acc: 0.7708, Val F1 Macro: 0.7923, Val F1 Weighted: 0.7673
Test Loss: 2.4326, Test Acc: 0.8125, Test F1 Macro: 0.8369, Test F1 Weighted: 0.8114
##################################################
Epoch: 350:
Train Loss: 0.1802, Train Acc: 0.9276, Train F1 Macro: 0.9385, Train F1 Weighted: 0.9281
Val Loss: 0.6482, Val Acc: 0.7708, Val F1 Macro: 0.7923, Val F1 Weighted: 0.7673
Test Loss: 2.4911, Test Acc: 0.8125, Test F1 Macro: 0.8369, Test F1 Weighted: 0.8114
##################################################
Epoch: 400:
Train Loss: 0.1763, Train Acc: 0.9276, Train F1 Macro: 0.9385, Train F1 Weighted: 0.9281
Val Loss: 0.6585, Val Acc: 0.7708, Val F1 Macro: 0.7923, Val F1 Weighted: 0.7673
Test Loss: 2.5524, Test Acc: 0.8125, Test F1 Macro: 0.8369, Test F1 Weighted: 0.8114
##################################################
Epoch: 450:
Train Loss: 0.1720, Train Acc: 0.9276, Train F1 Macro: 0.9385, Train F1 Weighted: 0.9281
Val Loss: 0.6677, Val Acc: 0.7708, Val F1 Macro: 0.7923, Val F1 Weighted: 0.7673
Test Loss: 2.6149, Test Acc: 0.8125, Test F1 Macro: 0.8369, Test F1 Weighted: 0.8114
##################################################
Epoch: 500:
Train Loss: 0.1677, Train Acc: 0.9302, Train F1 Macro: 0.9404, Train F1 Weighted: 0.9306
Val Loss: 0.6801, Val Acc: 0.7708, Val F1 Macro: 0.7923, Val F1 Weighted: 0.7673
Test Loss: 2.6802, Test Acc: 0.8125, Test F1 Macro: 0.8369, Test F1 Weighted: 0.8114
##################################################

In [83]:
print(f"| MOGONET GCN (mrna only) | {best_test[:, 0].mean():.2f} +/- {best_test[:, 0].std():.2f} | {best_test[:, 1].mean():.2f} +/- {best_test[:, 1].std():.2f} | {best_test[:, 2].mean():.2f} +/- {best_test[:, 2].std():.2f} |")

| MOGONET GCN (mrna only) | 0.85 +/- 0.03 | 0.84 +/- 0.03 | 0.85 +/- 0.03 |

In [162]:
print(f"| MOGONET GAT (mrna only) | {best_val[:, 0].mean():.2f} +/- {best_val[:, 0].std():.2f} | {best_val[:, 1].mean():.2f} +/- {best_val[:, 1].std():.2f} | {best_val[:, 2].mean():.2f} +/- {best_val[:, 2].std():.2f} |")
print(f"| MOGONET GAT (mrna only) | {best_test[:, 0].mean():.2f} +/- {best_test[:, 0].std():.2f} | {best_test[:, 1].mean():.2f} +/- {best_test[:, 1].std():.2f} | {best_test[:, 2].mean():.2f} +/- {best_test[:, 2].std():.2f} |")

| MOGONET GAT (mrna only) | 0.87 +/- 0.05 | 0.87 +/- 0.05 | 0.87 +/- 0.05 |
| MOGONET GAT (mrna only) | 0.85 +/- 0.03 | 0.86 +/- 0.02 | 0.85 +/- 0.03 |

In [25]:
mrna

shape: (18_975, 484)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sample    ┆ TCGA-A1-A ┆ TCGA-A1-A ┆ TCGA-A1-A ┆ … ┆ TCGA-E2-A ┆ TCGA-E2-A ┆ TCGA-E2-A ┆ TCGA-E2- │
│ ---       ┆ 0SD-01    ┆ 0SE-01    ┆ 0SH-01    ┆   ┆ 1B5-01    ┆ 1B6-01    ┆ 1BC-01    ┆ A1BD-01  │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ ARHGEF10L ┆ 9.1657    ┆ 9.7179    ┆ 8.8669    ┆ … ┆ 8.9027    ┆ 8.6965    ┆ 9.0303    ┆ 10.7991  │
│ HIF3A     ┆ 2.4935    ┆ 3.3983    ┆ 1.6631    ┆ … ┆ 4.8873    ┆ 4.6748    ┆ 6.9578    ┆ 2.1772   │
│ RNF17     ┆ 0.0       ┆ 0.0       ┆ 0.4449    ┆ … ┆ 0.0       ┆ 1.4776    ┆ 0.0       ┆ 0.8114   │
│ RNF10     ┆ 11.7868   ┆ 11.3219   ┆ 11.8779   ┆ … ┆ 12.6904   ┆ 12.3403   ┆ 11.8271   ┆ 12.2783  │
│ RNF11     ┆ 11.0131   ┆ 11.2617   ┆ 11.8526   ┆ … ┆ 11.5409   ┆ 10.4812   ┆ 11.8211   ┆ 10.791   │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ PTRF      ┆ 12.6757   ┆ 12.6287   ┆ 13.9112   ┆ … ┆ 12.4708   ┆ 12.493    ┆ 12.9017   ┆ 12.2984  │
│ BCL6B     ┆ 8.9559    ┆ 8.053     ┆ 7.5385    ┆ … ┆ 9.481     ┆ 7.374     ┆ 8.7661    ┆ 8.3132   │
│ GSTK1     ┆ 10.7473   ┆ 11.0453   ┆ 11.3402   ┆ … ┆ 11.011    ┆ 12.6251   ┆ 9.9638    ┆ 12.172   │
│ SELP      ┆ 8.7529    ┆ 7.8723    ┆ 4.7356    ┆ … ┆ 9.7613    ┆ 7.4161    ┆ 7.1316    ┆ 6.9635   │
│ SELS      ┆ 10.5299   ┆ 9.8006    ┆ 9.6643    ┆ … ┆ 10.8004   ┆ 10.7302   ┆ 9.9003    ┆ 9.3752   │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [30]:
meth

shape: (9_317, 484)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ gene     ┆ TCGA-A1-A ┆ TCGA-A1-A ┆ TCGA-A1-A ┆ … ┆ TCGA-E2-A ┆ TCGA-E2-A ┆ TCGA-E2-A ┆ TCGA-E2-A │
│ ---      ┆ 0SD-01    ┆ 0SE-01    ┆ 0SH-01    ┆   ┆ 1B5-01    ┆ 1B6-01    ┆ 1BC-01    ┆ 1BD-01    │
│ str      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│          ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ TMC2     ┆ 1.5235    ┆ 8.087     ┆ 7.3333    ┆ … ┆ 7.9256    ┆ 7.1273    ┆ 7.0039    ┆ 7.8961    │
│ CFD      ┆ 0.254     ┆ 5.2768    ┆ 4.7041    ┆ … ┆ 4.758     ┆ 3.6651    ┆ 3.983     ┆ 4.2721    │
│ E2F3     ┆ 0.0431    ┆ 6.7408    ┆ 6.7235    ┆ … ┆ 6.4084    ┆ 6.7554    ┆ 6.5313    ┆ 6.5771    │
│ IARS     ┆ 0.0421    ┆ 0.8795    ┆ 0.9065    ┆ … ┆ 0.9332    ┆ 0.9338    ┆ 0.9256    ┆ 0.8935    │
│ C15orf48 ┆ 0.0553    ┆ 0.6827    ┆ 0.5293    ┆ … ┆ 0.5424    ┆ 0.5709    ┆ 0.6157    ┆ 0.5959    │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ ATP6AP1  ┆ 0.8979    ┆ 1.627     ┆ 1.561     ┆ … ┆ 1.7721    ┆ 1.7483    ┆ 1.7033    ┆ 1.5066    │
│ NDRG1    ┆ 0.0409    ┆ 12.2029   ┆ 11.0855   ┆ … ┆ 12.6571   ┆ 11.9246   ┆ 11.2425   ┆ 11.1887   │
│ IRF4     ┆ 0.3553    ┆ 5.5119    ┆ 5.3661    ┆ … ┆ 6.5972    ┆ 4.3718    ┆ 5.2059    ┆ 6.8889    │
│ TNFRSF25 ┆ 0.901     ┆ 7.8912    ┆ 7.3803    ┆ … ┆ 6.5997    ┆ 6.2742    ┆ 7.2036    ┆ 7.7094    │
│ TM2D2    ┆ 0.0735    ┆ 0.939     ┆ 0.8921    ┆ … ┆ 0.9396    ┆ 0.9414    ┆ 0.9323    ┆ 0.9242    │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [33]:
cnv

shape: (24_776, 484)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Gene      ┆ TCGA-A1-A ┆ TCGA-A1-A ┆ TCGA-A1-A ┆ … ┆ TCGA-E2-A ┆ TCGA-E2-A ┆ TCGA-E2-A ┆ TCGA-E2- │
│ Symbol    ┆ 0SD-01    ┆ 0SE-01    ┆ 0SH-01    ┆   ┆ 1B5-01    ┆ 1B6-01    ┆ 1BC-01    ┆ A1BD-01  │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ i64       ┆ i64       ┆ i64       ┆   ┆ i64       ┆ i64       ┆ i64       ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ ACAP3     ┆ -1        ┆ 0         ┆ -1        ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ ACTRT2    ┆ -1        ┆ 0         ┆ -1        ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ AGRN      ┆ -1        ┆ 0         ┆ -1        ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ ANKRD65   ┆ -1        ┆ 0         ┆ -1        ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ ATAD3A    ┆ -1        ┆ 0         ┆ -1        ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ IL9R|ENSG ┆ 0         ┆ 0         ┆ 1         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ 000001243 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 34.12     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ SPRY3|ENS ┆ 0         ┆ 0         ┆ 1         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ G00000168 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 939.6     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ VAMP7|ENS ┆ 0         ┆ 0         ┆ 1         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ G00000124 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 333.10    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ WASH6P|EN ┆ 0         ┆ 0         ┆ 1         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ SG0000018 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2484.10   ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ WASIR1|EN ┆ 0         ┆ 0         ┆ 1         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ SG0000018 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 5203.7    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [35]:
mirna

shape: (231, 484)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sample    ┆ TCGA-A1-A ┆ TCGA-A1-A ┆ TCGA-A1-A ┆ … ┆ TCGA-E2-A ┆ TCGA-E2-A ┆ TCGA-E2-A ┆ TCGA-E2- │
│ ---       ┆ 0SD-01    ┆ 0SE-01    ┆ 0SH-01    ┆   ┆ 1B5-01    ┆ 1B6-01    ┆ 1BC-01    ┆ A1BD-01  │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ MIMAT0000 ┆ 5.071474  ┆ 3.854013  ┆ 2.382356  ┆ … ┆ 6.499371  ┆ 6.952499  ┆ 5.205349  ┆ 5.808441 │
│ 764       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ MIMAT0000 ┆ 4.008542  ┆ 3.422385  ┆ 2.56466   ┆ … ┆ 4.598889  ┆ 6.055791  ┆ 3.898447  ┆ 4.015216 │
│ 761       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ MIMAT0000 ┆ 5.210768  ┆ 4.299733  ┆ 4.463944  ┆ … ┆ 5.459581  ┆ 5.56719   ┆ 5.472708  ┆ 4.866539 │
│ 760       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ MIMAT0000 ┆ 7.578522  ┆ 7.59657   ┆ 5.648522  ┆ … ┆ 7.890473  ┆ 7.633656  ┆ 7.619209  ┆ 7.805858 │
│ 763       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ MIMAT0000 ┆ 3.822434  ┆ 2.878935  ┆ 2.7265    ┆ … ┆ 3.739594  ┆ 4.228494  ┆ 3.925158  ┆ 3.538409 │
│ 762       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ MIMAT0004 ┆ 5.569944  ┆ 5.434595  ┆ 4.553002  ┆ … ┆ 7.314498  ┆ 6.275077  ┆ 6.386142  ┆ 6.292118 │
│ 673       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ MIMAT0004 ┆ 8.420283  ┆ 7.675229  ┆ 6.779474  ┆ … ┆ 7.711471  ┆ 8.339112  ┆ 7.272364  ┆ 7.493567 │
│ 672       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ MIMAT0004 ┆ 6.176648  ┆ 5.899645  ┆ 5.430903  ┆ … ┆ 7.414027  ┆ 9.630073  ┆ 6.400461  ┆ 6.082076 │
│ 585       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ MIMAT0004 ┆ 4.845727  ┆ 5.099178  ┆ 3.769964  ┆ … ┆ 6.173566  ┆ 7.417396  ┆ 5.952771  ┆ 5.258293 │
│ 584       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ MIMAT0004 ┆ 3.941491  ┆ 4.703233  ┆ 3.693681  ┆ … ┆ 4.306263  ┆ 5.94027   ┆ 4.051562  ┆ 3.785091 │
│ 586       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [40]:
mirna_column = mirna['sample']
mirna_column = pl.DataFrame(mirna_column)

In [42]:
mirna_column.write_csv("brca_mirna_column.csv")

In [45]:
mirna_target_names = pl.read_csv("brca_mirna_target_names.csv", null_values=['NA'])

In [46]:
mirna_target_names

shape: (231, 2)
┌──────────────┬─────────────────┐
│ Accession    ┆ TargetName      │
│ ---          ┆ ---             │
│ str          ┆ str             │
╞══════════════╪═════════════════╡
│ MIMAT0000764 ┆ hsa-miR-339-5p  │
│ MIMAT0000761 ┆ hsa-miR-324-5p  │
│ MIMAT0000760 ┆ hsa-miR-331-3p  │
│ MIMAT0000763 ┆ hsa-miR-338-3p  │
│ MIMAT0000762 ┆ hsa-miR-324-3p  │
│ …            ┆ …               │
│ MIMAT0004673 ┆ hsa-miR-29c-5p  │
│ MIMAT0004672 ┆ hsa-miR-106b-3p │
│ MIMAT0004585 ┆ hsa-let-7i-3p   │
│ MIMAT0004584 ┆ hsa-let-7g-3p   │
│ MIMAT0004586 ┆ hsa-miR-15b-3p  │
└──────────────┴─────────────────┘

In [48]:
assert mirna_target_names['Accession'].to_list() == mirna['sample'].to_list()

In [50]:
mirna.with_columns(sample=mirna_target_names['TargetName'])

shape: (231, 484)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sample    ┆ TCGA-A1-A ┆ TCGA-A1-A ┆ TCGA-A1-A ┆ … ┆ TCGA-E2-A ┆ TCGA-E2-A ┆ TCGA-E2-A ┆ TCGA-E2- │
│ ---       ┆ 0SD-01    ┆ 0SE-01    ┆ 0SH-01    ┆   ┆ 1B5-01    ┆ 1B6-01    ┆ 1BC-01    ┆ A1BD-01  │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ hsa-miR-3 ┆ 5.071474  ┆ 3.854013  ┆ 2.382356  ┆ … ┆ 6.499371  ┆ 6.952499  ┆ 5.205349  ┆ 5.808441 │
│ 39-5p     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ hsa-miR-3 ┆ 4.008542  ┆ 3.422385  ┆ 2.56466   ┆ … ┆ 4.598889  ┆ 6.055791  ┆ 3.898447  ┆ 4.015216 │
│ 24-5p     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ hsa-miR-3 ┆ 5.210768  ┆ 4.299733  ┆ 4.463944  ┆ … ┆ 5.459581  ┆ 5.56719   ┆ 5.472708  ┆ 4.866539 │
│ 31-3p     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ hsa-miR-3 ┆ 7.578522  ┆ 7.59657   ┆ 5.648522  ┆ … ┆ 7.890473  ┆ 7.633656  ┆ 7.619209  ┆ 7.805858 │
│ 38-3p     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ hsa-miR-3 ┆ 3.822434  ┆ 2.878935  ┆ 2.7265    ┆ … ┆ 3.739594  ┆ 4.228494  ┆ 3.925158  ┆ 3.538409 │
│ 24-3p     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ hsa-miR-2 ┆ 5.569944  ┆ 5.434595  ┆ 4.553002  ┆ … ┆ 7.314498  ┆ 6.275077  ┆ 6.386142  ┆ 6.292118 │
│ 9c-5p     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ hsa-miR-1 ┆ 8.420283  ┆ 7.675229  ┆ 6.779474  ┆ … ┆ 7.711471  ┆ 8.339112  ┆ 7.272364  ┆ 7.493567 │
│ 06b-3p    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ hsa-let-7 ┆ 6.176648  ┆ 5.899645  ┆ 5.430903  ┆ … ┆ 7.414027  ┆ 9.630073  ┆ 6.400461  ┆ 6.082076 │
│ i-3p      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ hsa-let-7 ┆ 4.845727  ┆ 5.099178  ┆ 3.769964  ┆ … ┆ 6.173566  ┆ 7.417396  ┆ 5.952771  ┆ 5.258293 │
│ g-3p      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ hsa-miR-1 ┆ 3.941491  ┆ 4.703233  ┆ 3.693681  ┆ … ┆ 4.306263  ┆ 5.94027   ┆ 4.051562  ┆ 3.785091 │
│ 5b-3p     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [10]:
mirna

shape: (231, 484)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sample    ┆ TCGA-A1-A ┆ TCGA-A1-A ┆ TCGA-A1-A ┆ … ┆ TCGA-E2-A ┆ TCGA-E2-A ┆ TCGA-E2-A ┆ TCGA-E2- │
│ ---       ┆ 0SD-01    ┆ 0SE-01    ┆ 0SH-01    ┆   ┆ 1B5-01    ┆ 1B6-01    ┆ 1BC-01    ┆ A1BD-01  │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ MIMAT0000 ┆ 5.071474  ┆ 3.854013  ┆ 2.382356  ┆ … ┆ 6.499371  ┆ 6.952499  ┆ 5.205349  ┆ 5.808441 │
│ 764       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ MIMAT0000 ┆ 4.008542  ┆ 3.422385  ┆ 2.56466   ┆ … ┆ 4.598889  ┆ 6.055791  ┆ 3.898447  ┆ 4.015216 │
│ 761       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ MIMAT0000 ┆ 5.210768  ┆ 4.299733  ┆ 4.463944  ┆ … ┆ 5.459581  ┆ 5.56719   ┆ 5.472708  ┆ 4.866539 │
│ 760       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ MIMAT0000 ┆ 7.578522  ┆ 7.59657   ┆ 5.648522  ┆ … ┆ 7.890473  ┆ 7.633656  ┆ 7.619209  ┆ 7.805858 │
│ 763       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ MIMAT0000 ┆ 3.822434  ┆ 2.878935  ┆ 2.7265    ┆ … ┆ 3.739594  ┆ 4.228494  ┆ 3.925158  ┆ 3.538409 │
│ 762       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ MIMAT0004 ┆ 5.569944  ┆ 5.434595  ┆ 4.553002  ┆ … ┆ 7.314498  ┆ 6.275077  ┆ 6.386142  ┆ 6.292118 │
│ 673       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ MIMAT0004 ┆ 8.420283  ┆ 7.675229  ┆ 6.779474  ┆ … ┆ 7.711471  ┆ 8.339112  ┆ 7.272364  ┆ 7.493567 │
│ 672       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ MIMAT0004 ┆ 6.176648  ┆ 5.899645  ┆ 5.430903  ┆ … ┆ 7.414027  ┆ 9.630073  ┆ 6.400461  ┆ 6.082076 │
│ 585       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ MIMAT0004 ┆ 4.845727  ┆ 5.099178  ┆ 3.769964  ┆ … ┆ 6.173566  ┆ 7.417396  ┆ 5.952771  ┆ 5.258293 │
│ 584       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ MIMAT0004 ┆ 3.941491  ┆ 4.703233  ┆ 3.693681  ┆ … ┆ 4.306263  ┆ 5.94027   ┆ 4.051562  ┆ 3.785091 │
│ 586       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [12]:
mirna_samples = mirna['sample'].to_list()

In [16]:
mirbase_conver = pl.read_csv("miRBaseConverter_Result_all.csv", null_values=['NA'])

In [18]:
assert mirna_samples == mirbase_conver['Accession'].to_list()

In [20]:
mirna = mirna.with_columns(sample=mirbase_conver['TargetName'])

In [21]:
mirna

shape: (231, 484)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sample    ┆ TCGA-A1-A ┆ TCGA-A1-A ┆ TCGA-A1-A ┆ … ┆ TCGA-E2-A ┆ TCGA-E2-A ┆ TCGA-E2-A ┆ TCGA-E2- │
│ ---       ┆ 0SD-01    ┆ 0SE-01    ┆ 0SH-01    ┆   ┆ 1B5-01    ┆ 1B6-01    ┆ 1BC-01    ┆ A1BD-01  │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ hsa-miR-3 ┆ 5.071474  ┆ 3.854013  ┆ 2.382356  ┆ … ┆ 6.499371  ┆ 6.952499  ┆ 5.205349  ┆ 5.808441 │
│ 39-5p     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ hsa-miR-3 ┆ 4.008542  ┆ 3.422385  ┆ 2.56466   ┆ … ┆ 4.598889  ┆ 6.055791  ┆ 3.898447  ┆ 4.015216 │
│ 24-5p     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ hsa-miR-3 ┆ 5.210768  ┆ 4.299733  ┆ 4.463944  ┆ … ┆ 5.459581  ┆ 5.56719   ┆ 5.472708  ┆ 4.866539 │
│ 31-3p     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ hsa-miR-3 ┆ 7.578522  ┆ 7.59657   ┆ 5.648522  ┆ … ┆ 7.890473  ┆ 7.633656  ┆ 7.619209  ┆ 7.805858 │
│ 38-3p     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ hsa-miR-3 ┆ 3.822434  ┆ 2.878935  ┆ 2.7265    ┆ … ┆ 3.739594  ┆ 4.228494  ┆ 3.925158  ┆ 3.538409 │
│ 24-3p     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ hsa-miR-2 ┆ 5.569944  ┆ 5.434595  ┆ 4.553002  ┆ … ┆ 7.314498  ┆ 6.275077  ┆ 6.386142  ┆ 6.292118 │
│ 9c-5p     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ hsa-miR-1 ┆ 8.420283  ┆ 7.675229  ┆ 6.779474  ┆ … ┆ 7.711471  ┆ 8.339112  ┆ 7.272364  ┆ 7.493567 │
│ 06b-3p    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ hsa-let-7 ┆ 6.176648  ┆ 5.899645  ┆ 5.430903  ┆ … ┆ 7.414027  ┆ 9.630073  ┆ 6.400461  ┆ 6.082076 │
│ i-3p      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ hsa-let-7 ┆ 4.845727  ┆ 5.099178  ┆ 3.769964  ┆ … ┆ 6.173566  ┆ 7.417396  ┆ 5.952771  ┆ 5.258293 │
│ g-3p      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ hsa-miR-1 ┆ 3.941491  ┆ 4.703233  ┆ 3.693681  ┆ … ┆ 4.306263  ┆ 5.94027   ┆ 4.051562  ┆ 3.785091 │
│ 5b-3p     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [17]:
mirbase_conver

shape: (231, 2)
┌──────────────┬─────────────────┐
│ Accession    ┆ TargetName      │
│ ---          ┆ ---             │
│ str          ┆ str             │
╞══════════════╪═════════════════╡
│ MIMAT0000764 ┆ hsa-miR-339-5p  │
│ MIMAT0000761 ┆ hsa-miR-324-5p  │
│ MIMAT0000760 ┆ hsa-miR-331-3p  │
│ MIMAT0000763 ┆ hsa-miR-338-3p  │
│ MIMAT0000762 ┆ hsa-miR-324-3p  │
│ …            ┆ …               │
│ MIMAT0004673 ┆ hsa-miR-29c-5p  │
│ MIMAT0004672 ┆ hsa-miR-106b-3p │
│ MIMAT0004585 ┆ hsa-let-7i-3p   │
│ MIMAT0004584 ┆ hsa-let-7g-3p   │
│ MIMAT0004586 ┆ hsa-miR-15b-3p  │
└──────────────┴─────────────────┘

In [30]:
mirna = mirna.drop_nulls()

In [31]:
mirna

shape: (229, 484)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sample    ┆ TCGA-A1-A ┆ TCGA-A1-A ┆ TCGA-A1-A ┆ … ┆ TCGA-E2-A ┆ TCGA-E2-A ┆ TCGA-E2-A ┆ TCGA-E2- │
│ ---       ┆ 0SD-01    ┆ 0SE-01    ┆ 0SH-01    ┆   ┆ 1B5-01    ┆ 1B6-01    ┆ 1BC-01    ┆ A1BD-01  │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ hsa-miR-3 ┆ 5.071474  ┆ 3.854013  ┆ 2.382356  ┆ … ┆ 6.499371  ┆ 6.952499  ┆ 5.205349  ┆ 5.808441 │
│ 39-5p     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ hsa-miR-3 ┆ 4.008542  ┆ 3.422385  ┆ 2.56466   ┆ … ┆ 4.598889  ┆ 6.055791  ┆ 3.898447  ┆ 4.015216 │
│ 24-5p     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ hsa-miR-3 ┆ 5.210768  ┆ 4.299733  ┆ 4.463944  ┆ … ┆ 5.459581  ┆ 5.56719   ┆ 5.472708  ┆ 4.866539 │
│ 31-3p     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ hsa-miR-3 ┆ 7.578522  ┆ 7.59657   ┆ 5.648522  ┆ … ┆ 7.890473  ┆ 7.633656  ┆ 7.619209  ┆ 7.805858 │
│ 38-3p     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ hsa-miR-3 ┆ 3.822434  ┆ 2.878935  ┆ 2.7265    ┆ … ┆ 3.739594  ┆ 4.228494  ┆ 3.925158  ┆ 3.538409 │
│ 24-3p     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ hsa-miR-2 ┆ 5.569944  ┆ 5.434595  ┆ 4.553002  ┆ … ┆ 7.314498  ┆ 6.275077  ┆ 6.386142  ┆ 6.292118 │
│ 9c-5p     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ hsa-miR-1 ┆ 8.420283  ┆ 7.675229  ┆ 6.779474  ┆ … ┆ 7.711471  ┆ 8.339112  ┆ 7.272364  ┆ 7.493567 │
│ 06b-3p    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ hsa-let-7 ┆ 6.176648  ┆ 5.899645  ┆ 5.430903  ┆ … ┆ 7.414027  ┆ 9.630073  ┆ 6.400461  ┆ 6.082076 │
│ i-3p      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ hsa-let-7 ┆ 4.845727  ┆ 5.099178  ┆ 3.769964  ┆ … ┆ 6.173566  ┆ 7.417396  ┆ 5.952771  ┆ 5.258293 │
│ g-3p      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ hsa-miR-1 ┆ 3.941491  ┆ 4.703233  ┆ 3.693681  ┆ … ┆ 4.306263  ┆ 5.94027   ┆ 4.051562  ┆ 3.785091 │
│ 5b-3p     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [32]:
skf = StratifiedKFold(n_splits=5)

for i, (train_idx, test_idx) in enumerate(skf.split(np.zeros(len(y)), y)):
    # print(train_idx.shape, test_idx.shape)
    # print(train_idx, test_idx)
    # print(np.unique(y[train_idx], return_counts=True))
    # print(np.unique(y[test_idx], return_counts=True))

    mirna_selected = mrmr_selection(
        X_df=mirna,
        y=y,
        train_mask=train_idx,
        n_features=200,
        n_preselected_features=None,
        feature_col_name="sample",
    )

    mirna_selected.write_csv(f"BRCA_PROCESSED_DATA/mrmr_selected/mirna/mirna_fold_{i}.csv")

(386, 229)

100%|██████████| 200/200 [00:03<00:00, 64.93it/s]

(386, 229)

100%|██████████| 200/200 [00:03<00:00, 64.93it/s]

(386, 229)

100%|██████████| 200/200 [00:03<00:00, 63.93it/s]

(387, 229)

100%|██████████| 200/200 [00:03<00:00, 64.53it/s]

(387, 229)

100%|██████████| 200/200 [00:03<00:00, 64.47it/s]

In [8]:
val, test = mogonet_eval(
    input_omics={
        "mrna": mrna,
        "meth": meth,
        "cnv": cnv,
        "mirna": mirna,
    },
    # n_input_features={
        # "mrna": 3000,
        # "meth": 1000,
        # "cnv": 1000,
        # "mirna": 200,
    # },
    mrmr_selection_params={
        'mrmr_path' : "BRCA_PROCESSED_DATA/mrmr_selected",
    },
    y=y,
    params={
        "encoder_hidden_channels": {
            "mrna": 70,
            "meth": 70,
            "cnv": 70,
            "mirna": 70,
        },
        "encoder_type": "gat",
        "num_classes": 4,
        "graph_style": "threshold",
        "avg_degree": 15,
        # "graph_style": "knn",
        # "knn": 7,
        "dropout": 0.05,
        "epochs": 400,
        "log_interval": 50,
        "save_best_model": False,
        "integrator_type" : "vcdn",
        "integration_dim" : 4,
        "self_connections": True,
    }
)

dict_keys(['mrna', 'meth', 'cnv', 'mirna'])
Fold 1 / 5
dict_keys(['mrna', 'meth', 'cnv', 'mirna'])
Building graph for mrna
0.75 tensor(413.0704)
0.875 tensor(312.4948)
0.9375 tensor(177.3064)
0.96875 tensor(22.7640)
0.984375 tensor(1.1159)
0.9765625 tensor(4.9006)
0.97265625 tensor(11.8323)
0.970703125 tensor(16.7681)
0.9716796875 tensor(14.2298)
0.97119140625 tensor(15.4596)
Isolated samples = 212, avg degree = 15.459627151489258
Building graph for meth
0.75 tensor(261.2278)
0.875 tensor(161.4555)
0.9375 tensor(81.2319)
0.96875 tensor(46.4451)
0.984375 tensor(13.0083)
0.9765625 tensor(31.0207)
0.98046875 tensor(22.5114)
0.982421875 tensor(17.7950)
0.9833984375 tensor(15.2360)
Isolated samples = 322, avg degree = 15.236024856567383
Building graph for cnv
0.75 tensor(343.2360)
0.875 tensor(186.4120)
0.9375 tensor(74.6729)
0.96875 tensor(27.6294)
0.984375 tensor(11.2733)
0.9765625 tensor(18.2091)
0.98046875 tensor(14.7640)
Isolated samples = 213, avg degree = 14.763975143432617
Building graph for mirna
0.75 tensor(481.0042)
0.875 tensor(412.3665)
0.9375 tensor(114.0559)
0.96875 tensor(3.7950)
0.953125 tensor(33.2277)
0.9609375 tensor(12.6729)
0.95703125 tensor(21.0911)
0.958984375 tensor(16.4617)
0.9599609375 tensor(14.3996)
0.95947265625 tensor(15.4803)
Isolated samples = 129, avg degree = 15.480331420898438
Epoch: 050:
Train Loss: 0.3393, Train Acc: 0.8653, Train F1 Macro: 0.8474, Train F1 Weighted: 0.8663
Val Loss: 0.3676, Val Acc: 0.9375, Val F1 Macro: 0.9118, Val F1 Weighted: 0.9364
Test Loss: 0.6195, Test Acc: 0.7755, Test F1 Macro: 0.7721, Test F1 Weighted: 0.7828
##################################################
Epoch: 100:
Train Loss: 0.2536, Train Acc: 0.8886, Train F1 Macro: 0.8852, Train F1 Weighted: 0.8891
Val Loss: 0.5062, Val Acc: 0.9375, Val F1 Macro: 0.9118, Val F1 Weighted: 0.9364
Test Loss: 0.9367, Test Acc: 0.7551, Test F1 Macro: 0.7595, Test F1 Weighted: 0.7644
##################################################
Epoch: 150:
Train Loss: 0.2428, Train Acc: 0.9016, Train F1 Macro: 0.8944, Train F1 Weighted: 0.9029
Val Loss: 0.5621, Val Acc: 0.9375, Val F1 Macro: 0.9118, Val F1 Weighted: 0.9364
Test Loss: 1.0223, Test Acc: 0.7755, Test F1 Macro: 0.7770, Test F1 Weighted: 0.7857
##################################################
Epoch: 200:
Train Loss: 0.2315, Train Acc: 0.9145, Train F1 Macro: 0.9023, Train F1 Weighted: 0.9160
Val Loss: 0.5633, Val Acc: 0.9375, Val F1 Macro: 0.9118, Val F1 Weighted: 0.9364
Test Loss: 1.0445, Test Acc: 0.7551, Test F1 Macro: 0.7640, Test F1 Weighted: 0.7667
##################################################
Epoch: 250:
Train Loss: 0.2704, Train Acc: 0.9301, Train F1 Macro: 0.9287, Train F1 Weighted: 0.9297
Val Loss: 0.5690, Val Acc: 0.9375, Val F1 Macro: 0.9118, Val F1 Weighted: 0.9364
Test Loss: 1.0661, Test Acc: 0.7551, Test F1 Macro: 0.7640, Test F1 Weighted: 0.7667
##################################################
Epoch: 300:
Train Loss: 0.2371, Train Acc: 0.9145, Train F1 Macro: 0.9080, Train F1 Weighted: 0.9154
Val Loss: 0.5831, Val Acc: 0.9375, Val F1 Macro: 0.9118, Val F1 Weighted: 0.9364
Test Loss: 1.0872, Test Acc: 0.7551, Test F1 Macro: 0.7640, Test F1 Weighted: 0.7667
##################################################
Epoch: 350:
Train Loss: 0.2093, Train Acc: 0.9301, Train F1 Macro: 0.9330, Train F1 Weighted: 0.9301
Val Loss: 0.5982, Val Acc: 0.9375, Val F1 Macro: 0.9118, Val F1 Weighted: 0.9364
Test Loss: 1.0973, Test Acc: 0.7755, Test F1 Macro: 0.7770, Test F1 Weighted: 0.7857
##################################################
Epoch: 400:
Train Loss: 0.2638, Train Acc: 0.8912, Train F1 Macro: 0.8899, Train F1 Weighted: 0.8916
Val Loss: 0.6039, Val Acc: 0.9375, Val F1 Macro: 0.9118, Val F1 Weighted: 0.9364
Test Loss: 1.1340, Test Acc: 0.7347, Test F1 Macro: 0.7510, Test F1 Weighted: 0.7473
##################################################
Fold 2 / 5
dict_keys(['mrna', 'meth', 'cnv', 'mirna'])
Building graph for mrna
0.75 tensor(420.2836)
0.875 tensor(317.5756)
0.9375 tensor(189.2277)
0.96875 tensor(28.2961)
0.984375 tensor(1.1698)
0.9765625 tensor(6.4783)
0.97265625 tensor(14.7019)
Isolated samples = 211, avg degree = 14.701863288879395
Building graph for meth
0.75 tensor(278.2712)
0.875 tensor(161.2195)
0.9375 tensor(81.5300)
0.96875 tensor(45.0952)
0.984375 tensor(9.7164)
0.9765625 tensor(28.4120)
0.98046875 tensor(18.8261)
0.982421875 tensor(13.9648)
0.9814453125 tensor(16.4576)
0.98193359375 tensor(15.2484)
Isolated samples = 321, avg degree = 15.24844741821289
Building graph for cnv
0.75 tensor(360.8302)
0.875 tensor(197.6211)
0.9375 tensor(72.8344)
0.96875 tensor(22.4865)
0.984375 tensor(8.1139)
0.9765625 tensor(13.4389)
0.97265625 tensor(17.8406)
0.974609375 tensor(15.5135)
0.9755859375 tensor(14.5280)
Isolated samples = 234, avg degree = 14.527950286865234
Building graph for mirna
0.75 tensor(482.5694)
0.875 tensor(437.6087)
0.9375 tensor(158.1594)
0.96875 tensor(6.3872)
0.953125 tensor(53.3768)
0.9609375 tensor(21.5300)
0.96484375 tensor(12.1677)
0.962890625 tensor(16.2629)
0.9638671875 tensor(14.2008)
0.96337890625 tensor(15.1822)
Isolated samples = 135, avg degree = 15.182194709777832
Epoch: 050:
Train Loss: 0.3780, Train Acc: 0.8394, Train F1 Macro: 0.8374, Train F1 Weighted: 0.8406
Val Loss: 0.3502, Val Acc: 0.8333, Val F1 Macro: 0.8333, Val F1 Weighted: 0.8292
Test Loss: 0.3552, Test Acc: 0.8776, Test F1 Macro: 0.8653, Test F1 Weighted: 0.8805
##################################################
Epoch: 100:
Train Loss: 0.2321, Train Acc: 0.9223, Train F1 Macro: 0.9214, Train F1 Weighted: 0.9227
Val Loss: 0.3594, Val Acc: 0.8542, Val F1 Macro: 0.8590, Val F1 Weighted: 0.8513
Test Loss: 0.3987, Test Acc: 0.8980, Test F1 Macro: 0.8961, Test F1 Weighted: 0.8992
##################################################
Epoch: 150:
Train Loss: 0.1796, Train Acc: 0.9197, Train F1 Macro: 0.9131, Train F1 Weighted: 0.9188
Val Loss: 0.4043, Val Acc: 0.8125, Val F1 Macro: 0.8123, Val F1 Weighted: 0.8042
Test Loss: 0.3633, Test Acc: 0.9388, Test F1 Macro: 0.9261, Test F1 Weighted: 0.9388
##################################################
Epoch: 200:
Train Loss: 0.1932, Train Acc: 0.9430, Train F1 Macro: 0.9378, Train F1 Weighted: 0.9434
Val Loss: 0.4077, Val Acc: 0.8333, Val F1 Macro: 0.8570, Val F1 Weighted: 0.8279
Test Loss: 0.3799, Test Acc: 0.9388, Test F1 Macro: 0.9261, Test F1 Weighted: 0.9388
##################################################
Epoch: 250:
Train Loss: 0.1901, Train Acc: 0.9430, Train F1 Macro: 0.9335, Train F1 Weighted: 0.9433
Val Loss: 0.4083, Val Acc: 0.8333, Val F1 Macro: 0.8570, Val F1 Weighted: 0.8279
Test Loss: 0.3704, Test Acc: 0.9388, Test F1 Macro: 0.9261, Test F1 Weighted: 0.9388
##################################################
Epoch: 300:
Train Loss: 0.1677, Train Acc: 0.9482, Train F1 Macro: 0.9448, Train F1 Weighted: 0.9480
Val Loss: 0.4166, Val Acc: 0.8125, Val F1 Macro: 0.8181, Val F1 Weighted: 0.8022
Test Loss: 0.3753, Test Acc: 0.9388, Test F1 Macro: 0.9261, Test F1 Weighted: 0.9388
##################################################
Epoch: 350:
Train Loss: 0.1459, Train Acc: 0.9508, Train F1 Macro: 0.9438, Train F1 Weighted: 0.9511
Val Loss: 0.4084, Val Acc: 0.8125, Val F1 Macro: 0.8378, Val F1 Weighted: 0.8085
Test Loss: 0.3937, Test Acc: 0.9184, Test F1 Macro: 0.9109, Test F1 Weighted: 0.9189
##################################################
Epoch: 400:
Train Loss: 0.1887, Train Acc: 0.9352, Train F1 Macro: 0.9355, Train F1 Weighted: 0.9355
Val Loss: 0.4185, Val Acc: 0.8333, Val F1 Macro: 0.8570, Val F1 Weighted: 0.8279
Test Loss: 0.3890, Test Acc: 0.9388, Test F1 Macro: 0.9261, Test F1 Weighted: 0.9388
##################################################
Fold 3 / 5
dict_keys(['mrna', 'meth', 'cnv', 'mirna'])
Building graph for mrna
0.75 tensor(426.6480)
0.875 tensor(317.8613)
0.9375 tensor(194.5280)
0.96875 tensor(32.0807)
0.984375 tensor(1.2733)
0.9765625 tensor(7.6708)
0.97265625 tensor(17.7371)
0.974609375 tensor(12.0269)
0.9736328125 tensor(14.6315)
Isolated samples = 204, avg degree = 14.6314697265625
Building graph for meth
0.75 tensor(281.2070)
0.875 tensor(164.0725)
0.9375 tensor(83.4017)
0.96875 tensor(46.1594)
0.984375 tensor(13.8406)
0.9765625 tensor(31.7619)
0.98046875 tensor(23.1739)
0.982421875 tensor(18.4907)
0.9833984375 tensor(16.2050)
0.98388671875 tensor(14.9503)
Isolated samples = 324, avg degree = 14.950310707092285
Building graph for cnv
0.75 tensor(370.2174)
0.875 tensor(204.1429)
0.9375 tensor(77.9896)
0.96875 tensor(25.7909)
0.984375 tensor(8.3043)
0.9765625 tensor(15.7329)
0.98046875 tensor(11.0828)
0.978515625 tensor(13.0497)
0.9775390625 tensor(14.4037)
0.97705078125 tensor(14.8385)
Isolated samples = 240, avg degree = 14.838509559631348
Building graph for mirna
0.75 tensor(482.4493)
0.875 tensor(427.9400)
0.9375 tensor(133.2940)
0.96875 tensor(4.4369)
0.953125 tensor(40.0890)
0.9609375 tensor(15.2899)
Isolated samples = 128, avg degree = 15.289855003356934
Epoch: 050:
Train Loss: 0.3434, Train Acc: 0.8601, Train F1 Macro: 0.8538, Train F1 Weighted: 0.8613
Val Loss: 0.7429, Val Acc: 0.7708, Val F1 Macro: 0.7908, Val F1 Weighted: 0.7768
Test Loss: 0.2265, Test Acc: 0.8980, Test F1 Macro: 0.9276, Test F1 Weighted: 0.8996
##################################################
Epoch: 100:
Train Loss: 0.3718, Train Acc: 0.8497, Train F1 Macro: 0.8381, Train F1 Weighted: 0.8525
Val Loss: 0.9176, Val Acc: 0.7708, Val F1 Macro: 0.7833, Val F1 Weighted: 0.7738
Test Loss: 0.2013, Test Acc: 0.8980, Test F1 Macro: 0.9276, Test F1 Weighted: 0.8996
##################################################
Epoch: 150:
Train Loss: 0.3171, Train Acc: 0.8472, Train F1 Macro: 0.8434, Train F1 Weighted: 0.8492
Val Loss: 1.0067, Val Acc: 0.7500, Val F1 Macro: 0.7833, Val F1 Weighted: 0.7587
Test Loss: 0.1976, Test Acc: 0.8980, Test F1 Macro: 0.9276, Test F1 Weighted: 0.8996
##################################################
Epoch: 200:
Train Loss: 0.3376, Train Acc: 0.8653, Train F1 Macro: 0.8608, Train F1 Weighted: 0.8661
Val Loss: 1.0199, Val Acc: 0.7500, Val F1 Macro: 0.7833, Val F1 Weighted: 0.7587
Test Loss: 0.1954, Test Acc: 0.8980, Test F1 Macro: 0.9276, Test F1 Weighted: 0.8996
##################################################
Epoch: 250:
Train Loss: 0.3633, Train Acc: 0.8394, Train F1 Macro: 0.8265, Train F1 Weighted: 0.8431
Val Loss: 1.0408, Val Acc: 0.7500, Val F1 Macro: 0.7833, Val F1 Weighted: 0.7587
Test Loss: 0.1978, Test Acc: 0.8980, Test F1 Macro: 0.9276, Test F1 Weighted: 0.8996
##################################################
Epoch: 300:
Train Loss: 0.3481, Train Acc: 0.8627, Train F1 Macro: 0.8503, Train F1 Weighted: 0.8643
Val Loss: 1.0755, Val Acc: 0.7500, Val F1 Macro: 0.7833, Val F1 Weighted: 0.7587
Test Loss: 0.1979, Test Acc: 0.8980, Test F1 Macro: 0.9276, Test F1 Weighted: 0.8996
##################################################
Epoch: 350:
Train Loss: 0.3351, Train Acc: 0.8627, Train F1 Macro: 0.8507, Train F1 Weighted: 0.8639
Val Loss: 1.1160, Val Acc: 0.7500, Val F1 Macro: 0.7833, Val F1 Weighted: 0.7587
Test Loss: 0.1954, Test Acc: 0.8980, Test F1 Macro: 0.9276, Test F1 Weighted: 0.8996
##################################################
Epoch: 400:
Train Loss: 0.3821, Train Acc: 0.8653, Train F1 Macro: 0.8561, Train F1 Weighted: 0.8665
Val Loss: 1.1280, Val Acc: 0.7708, Val F1 Macro: 0.7900, Val F1 Weighted: 0.7733
Test Loss: 0.1907, Test Acc: 0.8980, Test F1 Macro: 0.9276, Test F1 Weighted: 0.8996
##################################################
Fold 4 / 5
dict_keys(['mrna', 'meth', 'cnv', 'mirna'])
Building graph for mrna
0.75 tensor(406.0393)
0.875 tensor(314.1760)
0.9375 tensor(185.7039)
0.96875 tensor(24.4410)
0.984375 tensor(1.0911)
0.9765625 tensor(5.3478)
0.97265625 tensor(12.6398)
0.970703125 tensor(18.0021)
0.9716796875 tensor(15.1863)
Isolated samples = 209, avg degree = 15.186335563659668
Building graph for meth
0.75 tensor(246.0145)
0.875 tensor(163.7743)
0.9375 tensor(81.8944)
0.96875 tensor(41.0787)
0.984375 tensor(11.1201)
0.9765625 tensor(26.9545)
0.98046875 tensor(19.2857)
0.982421875 tensor(15.2070)
Isolated samples = 319, avg degree = 15.207038879394531
Building graph for cnv
0.75 tensor(368.2215)
0.875 tensor(205.3230)
0.9375 tensor(80.6563)
0.96875 tensor(29.1988)
0.984375 tensor(10.2381)
0.9765625 tensor(18.6480)
0.98046875 tensor(13.6377)
0.978515625 tensor(16.1429)
0.9794921875 tensor(15.0745)
Isolated samples = 243, avg degree = 15.07453441619873
Building graph for mirna
0.75 tensor(482.5569)
0.875 tensor(437.8282)
0.9375 tensor(158.2339)
0.96875 tensor(6.1139)
0.953125 tensor(52.1470)
0.9609375 tensor(20.5818)
0.96484375 tensor(11.5176)
0.962890625 tensor(15.5424)
0.9638671875 tensor(13.4638)
0.96337890625 tensor(14.4617)
0.963134765625 tensor(15.0787)
Isolated samples = 124, avg degree = 15.078675270080566
Epoch: 050:
Train Loss: 0.3844, Train Acc: 0.8630, Train F1 Macro: 0.8609, Train F1 Weighted: 0.8651
Val Loss: 0.2865, Val Acc: 0.9375, Val F1 Macro: 0.9338, Val F1 Weighted: 0.9361
Test Loss: 0.6157, Test Acc: 0.7917, Test F1 Macro: 0.7660, Test F1 Weighted: 0.7761
##################################################
Epoch: 100:
Train Loss: 0.3135, Train Acc: 0.8630, Train F1 Macro: 0.8695, Train F1 Weighted: 0.8635
Val Loss: 0.3011, Val Acc: 0.9167, Val F1 Macro: 0.9159, Val F1 Weighted: 0.9139
Test Loss: 0.6806, Test Acc: 0.8125, Test F1 Macro: 0.7893, Test F1 Weighted: 0.8030
##################################################
Epoch: 150:
Train Loss: 0.2583, Train Acc: 0.8786, Train F1 Macro: 0.8890, Train F1 Weighted: 0.8788
Val Loss: 0.3492, Val Acc: 0.9375, Val F1 Macro: 0.9359, Val F1 Weighted: 0.9378
Test Loss: 0.7095, Test Acc: 0.8125, Test F1 Macro: 0.7859, Test F1 Weighted: 0.8033
##################################################
Epoch: 200:
Train Loss: 0.2962, Train Acc: 0.8708, Train F1 Macro: 0.8744, Train F1 Weighted: 0.8703
Val Loss: 0.3504, Val Acc: 0.9375, Val F1 Macro: 0.9359, Val F1 Weighted: 0.9378
Test Loss: 0.7146, Test Acc: 0.8125, Test F1 Macro: 0.7859, Test F1 Weighted: 0.8033
##################################################
Epoch: 250:
Train Loss: 0.2740, Train Acc: 0.8837, Train F1 Macro: 0.8820, Train F1 Weighted: 0.8836
Val Loss: 0.3371, Val Acc: 0.9375, Val F1 Macro: 0.9359, Val F1 Weighted: 0.9378
Test Loss: 0.7211, Test Acc: 0.8125, Test F1 Macro: 0.7893, Test F1 Weighted: 0.8030
##################################################
Epoch: 300:
Train Loss: 0.2812, Train Acc: 0.8734, Train F1 Macro: 0.8759, Train F1 Weighted: 0.8741
Val Loss: 0.3441, Val Acc: 0.9375, Val F1 Macro: 0.9359, Val F1 Weighted: 0.9378
Test Loss: 0.7259, Test Acc: 0.7917, Test F1 Macro: 0.7727, Test F1 Weighted: 0.7852
##################################################
Epoch: 350:
Train Loss: 0.3021, Train Acc: 0.8708, Train F1 Macro: 0.8744, Train F1 Weighted: 0.8704
Val Loss: 0.3465, Val Acc: 0.9375, Val F1 Macro: 0.9359, Val F1 Weighted: 0.9378
Test Loss: 0.7362, Test Acc: 0.7917, Test F1 Macro: 0.7727, Test F1 Weighted: 0.7852
##################################################
Epoch: 400:
Train Loss: 0.2561, Train Acc: 0.8915, Train F1 Macro: 0.8968, Train F1 Weighted: 0.8913
Val Loss: 0.3808, Val Acc: 0.9375, Val F1 Macro: 0.9359, Val F1 Weighted: 0.9378
Test Loss: 0.7647, Test Acc: 0.8125, Test F1 Macro: 0.7893, Test F1 Weighted: 0.8030
##################################################
Fold 5 / 5
dict_keys(['mrna', 'meth', 'cnv', 'mirna'])
Building graph for mrna
0.75 tensor(419.5424)
0.875 tensor(318.2754)
0.9375 tensor(197.2526)
0.96875 tensor(35.0663)
0.984375 tensor(1.4224)
0.9765625 tensor(8.7060)
0.97265625 tensor(19.3810)
0.974609375 tensor(13.4058)
0.9736328125 tensor(16.3416)
0.97412109375 tensor(14.7805)
Isolated samples = 218, avg degree = 14.780538558959961
Building graph for meth
0.75 tensor(243.3685)
0.875 tensor(155.5342)
0.9375 tensor(79.7950)
0.96875 tensor(44.5362)
0.984375 tensor(12.2050)
0.9765625 tensor(29.6791)
0.98046875 tensor(21.0455)
0.982421875 tensor(16.6480)
0.9833984375 tensor(14.4410)
0.98291015625 tensor(15.4762)
Isolated samples = 319, avg degree = 15.476190567016602
Building graph for cnv
0.75 tensor(363.9358)
0.875 tensor(200.9337)
0.9375 tensor(79.2153)
0.96875 tensor(25.8199)
0.984375 tensor(8.8219)
0.9765625 tensor(15.5466)
0.98046875 tensor(11.2070)
0.978515625 tensor(12.9462)
0.9775390625 tensor(14.3540)
0.97705078125 tensor(15.1408)
Isolated samples = 238, avg degree = 15.140787124633789
Building graph for mirna
0.75 tensor(482.6895)
0.875 tensor(438.5238)
0.9375 tensor(157.9027)
0.96875 tensor(6.0062)
0.953125 tensor(52.1594)
0.9609375 tensor(20.6025)
0.96484375 tensor(11.5300)
0.962890625 tensor(15.5424)
0.9638671875 tensor(13.3934)
0.96337890625 tensor(14.4410)
0.963134765625 tensor(14.9710)
Isolated samples = 130, avg degree = 14.971014022827148
Epoch: 050:
Train Loss: 0.4474, Train Acc: 0.8450, Train F1 Macro: 0.8371, Train F1 Weighted: 0.8492
Val Loss: 1.1275, Val Acc: 0.7500, Val F1 Macro: 0.7433, Val F1 Weighted: 0.7497
Test Loss: 0.4890, Test Acc: 0.8750, Test F1 Macro: 0.8623, Test F1 Weighted: 0.8779
##################################################
Epoch: 100:
Train Loss: 0.3875, Train Acc: 0.8579, Train F1 Macro: 0.8555, Train F1 Weighted: 0.8589
Val Loss: 1.1800, Val Acc: 0.7708, Val F1 Macro: 0.7592, Val F1 Weighted: 0.7696
Test Loss: 0.6289, Test Acc: 0.8542, Test F1 Macro: 0.8482, Test F1 Weighted: 0.8569
##################################################
Epoch: 150:
Train Loss: 0.3205, Train Acc: 0.8786, Train F1 Macro: 0.8732, Train F1 Weighted: 0.8806
Val Loss: 1.1957, Val Acc: 0.7708, Val F1 Macro: 0.7592, Val F1 Weighted: 0.7696
Test Loss: 0.6644, Test Acc: 0.8750, Test F1 Macro: 0.8638, Test F1 Weighted: 0.8783
##################################################
Epoch: 200:
Train Loss: 0.3602, Train Acc: 0.8656, Train F1 Macro: 0.8496, Train F1 Weighted: 0.8680
Val Loss: 1.1884, Val Acc: 0.7708, Val F1 Macro: 0.7592, Val F1 Weighted: 0.7696
Test Loss: 0.6733, Test Acc: 0.8750, Test F1 Macro: 0.8638, Test F1 Weighted: 0.8783
##################################################
Epoch: 250:
Train Loss: 0.3526, Train Acc: 0.8579, Train F1 Macro: 0.8562, Train F1 Weighted: 0.8600
Val Loss: 1.1973, Val Acc: 0.7708, Val F1 Macro: 0.7592, Val F1 Weighted: 0.7696
Test Loss: 0.6881, Test Acc: 0.8750, Test F1 Macro: 0.8638, Test F1 Weighted: 0.8783
##################################################
Epoch: 300:
Train Loss: 0.3670, Train Acc: 0.8527, Train F1 Macro: 0.8414, Train F1 Weighted: 0.8544
Val Loss: 1.2173, Val Acc: 0.7708, Val F1 Macro: 0.7592, Val F1 Weighted: 0.7696
Test Loss: 0.6879, Test Acc: 0.8750, Test F1 Macro: 0.8638, Test F1 Weighted: 0.8783
##################################################
Epoch: 350:
Train Loss: 0.3328, Train Acc: 0.8527, Train F1 Macro: 0.8507, Train F1 Weighted: 0.8545
Val Loss: 1.2330, Val Acc: 0.7708, Val F1 Macro: 0.7554, Val F1 Weighted: 0.7684
Test Loss: 0.7011, Test Acc: 0.8750, Test F1 Macro: 0.8638, Test F1 Weighted: 0.8783
##################################################
Epoch: 400:
Train Loss: 0.3779, Train Acc: 0.8398, Train F1 Macro: 0.8286, Train F1 Weighted: 0.8415
Val Loss: 1.2421, Val Acc: 0.7708, Val F1 Macro: 0.7554, Val F1 Weighted: 0.7684
Test Loss: 0.7000, Test Acc: 0.8750, Test F1 Macro: 0.8638, Test F1 Weighted: 0.8783
##################################################

- increasing the integration dimension is trash
- vcdn is better, than the attention integrator
- thresholding graph is better than the knn graph even though it can be fairly sparse

In [9]:
print("MOGONET GAT (mrna, mirna, meth) results:")
print(f"| MOGONET GAT val | {val[:, 0].mean():.2f} +/- {val[:, 0].std():.2f} | {val[:, 1].mean():.2f} +/- {val[:, 1].std():.2f} | {val[:, 2].mean():.2f} +/- {val[:, 2].std():.2f} |")
print(f"| MOGONET GAT test | {test[:, 0].mean():.2f} +/- {test[:, 0].std():.2f} | {test[:, 1].mean():.2f} +/- {test[:, 1].std():.2f} | {test[:, 2].mean():.2f} +/- {test[:, 2].std():.2f} |")

MOGONET GAT (mrna, mirna, meth) results:
| MOGONET GAT val | 0.88 +/- 0.07 | 0.88 +/- 0.06 | 0.88 +/- 0.07 |
| MOGONET GAT test | 0.87 +/- 0.06 | 0.86 +/- 0.07 | 0.87 +/- 0.06 |

In [65]:
print("MOGONET GAT (mrna, mirna, meth) results:")
print(f"| MOGONET GAT val | {val[:, 0].mean():.2f} +/- {val[:, 0].std():.2f} | {val[:, 1].mean():.2f} +/- {val[:, 1].std():.2f} | {val[:, 2].mean():.2f} +/- {val[:, 2].std():.2f} |")
print(f"| MOGONET GAT test | {test[:, 0].mean():.2f} +/- {test[:, 0].std():.2f} | {test[:, 1].mean():.2f} +/- {test[:, 1].std():.2f} | {test[:, 2].mean():.2f} +/- {test[:, 2].std():.2f} |")

MOGONET GAT (mrna, mirna, meth) results:
| MOGONET GAT val | 0.88 +/- 0.08 | 0.89 +/- 0.07 | 0.88 +/- 0.08 |
| MOGONET GAT test | 0.88 +/- 0.05 | 0.88 +/- 0.05 | 0.89 +/- 0.05 |

In [43]:
print("MOGONET GAT (mrna, mirna, meth) results:")
print(f"| MOGONET GAT val | {val[:, 0].mean():.2f} +/- {val[:, 0].std():.2f} | {val[:, 1].mean():.2f} +/- {val[:, 1].std():.2f} | {val[:, 2].mean():.2f} +/- {val[:, 2].std():.2f} |")
print(f"| MOGONET GAT test | {test[:, 0].mean():.2f} +/- {test[:, 0].std():.2f} | {test[:, 1].mean():.2f} +/- {test[:, 1].std():.2f} | {test[:, 2].mean():.2f} +/- {test[:, 2].std():.2f} |")

MOGONET GAT (mrna, mirna, meth) results:
| MOGONET GAT val | 0.83 +/- 0.05 | 0.83 +/- 0.04 | 0.83 +/- 0.05 |
| MOGONET GAT test | 0.83 +/- 0.10 | 0.84 +/- 0.10 | 0.83 +/- 0.10 |

In [18]:
print("MOGONET GAT (mrna only) results:")
print(f"| MOGONET GAT (mrna only) val | {val[:, 0].mean():.2f} +/- {val[:, 0].std():.2f} | {val[:, 1].mean():.2f} +/- {val[:, 1].std():.2f} | {val[:, 2].mean():.2f} +/- {val[:, 2].std():.2f} |")
print(f"| MOGONET GAT (mrna only) test | {test[:, 0].mean():.2f} +/- {test[:, 0].std():.2f} | {test[:, 1].mean():.2f} +/- {test[:, 1].std():.2f} | {test[:, 2].mean():.2f} +/- {test[:, 2].std():.2f} |")

| MOGONET GAT (mrna only) val | 0.80 +/- 0.06 | 0.81 +/- 0.05 | 0.81 +/- 0.05 |
| MOGONET GAT (mrna only) test | 0.86 +/- 0.04 | 0.84 +/- 0.05 | 0.86 +/- 0.04 |

In [9]:
for mirna_file in os.listdir('BRCA_PROCESSED_DATA/mrmr_selected/mirna'):
    # print(mirna_file)
    mirna = pl.read_csv(f'BRCA_PROCESSED_DATA/mrmr_selected/{mirna_file}')
    
    # mirna_s = mirna.select(['GENE_NAME'] + all_common_sample_names)
    # mirna_s.write_csv(f'MDS_data_preprocessed/mirna/{mirna_file}')

mirna_fold_0.csv
mirna_fold_1.csv
mirna_fold_4.csv
mirna_fold_3.csv
mirna_fold_2.csv

In [25]:
from gnn_experiments.bipartite_eval import bipartite_eval

bipartite_eval(
    input_omics={
        "mrna": mrna,
        # "meth": meth,
        "mirna": mirna,
    },
    n_input_features={
        "mrna": 200,
        # "meth": 200,
        "mirna": 200,
    },
    multipliers={
        "mrna": 1.5,
        # "meth": 1.5,
        "mirna": 1.5,
    },
    # mrmr_selection_params={
    #     "mrmr_path": "BRCA_PROCESSED_DATA/mrmr_selected",
    # },
    input_omics_interactions={
        ("mrna", "mrna") : {
            "gene_interaction" : {
                "interactant_col_1" : "Official Symbol Interactor A",
                "interactant_col_2" : "Official Symbol Interactor B",
                "interactions_file" : "biogrid_preprocessed_data.csv",
            },
            "protein_interaction" : {
                "interactant_col_1" : "gene1",
                "interactant_col_2" : "gene2",
                "interactions_file" : "string_db/ppi.csv",
            },
        },
        # ("meth", "meth") : {
        #     "gene_interaction" : {
        #         "interactant_col_1" : "Official Symbol Interactor A",
        #         "interactant_col_2" : "Official Symbol Interactor B",
        #         "interactions_file" : "biogrid_preprocessed_data.csv",
        #     },
        #     "protein_interaction" : {
        #         "interactant_col_1" : "gene1",
        #         "interactant_col_2" : "gene2",
        #         "interactions_file" : "string_db/ppi.csv",
        #     },
        # },
        # ("mrna", "meth") : {
        #     "gene_interaction" : {
        #         "interactant_col_1" : "Official Symbol Interactor A",
        #         "interactant_col_2" : "Official Symbol Interactor B",
        #         "interactions_file" : "biogrid_preprocessed_data.csv",
        #     },
        #     "protein_interaction" : {
        #         "interactant_col_1" : "gene1",
        #         "interactant_col_2" : "gene2",
        #         "interactions_file" : "string_db/ppi.csv",
        #     },
        # },
        ("mrna", "mirna") : {
            "gene_interaction" : {
                "interactant_col_1" : "gene",
                "interactant_col_2" : "mirna",
                "interactions_file" : "mirna_mrna_interactions_DB.csv",
            },
        },
        # ("meth", "mirna") : {
        #     "gene_interaction" : {
        #         "interactant_col_1" : "gene",
        #         "interactant_col_2" : "mirna",
        #         "interactions_file" : "mirna_mrna_interactions_DB.csv",
        #     },
        # }
    },
    y=y,
    params={
        "epochs": 500,
        "log_interval": 50,
        "save_best_model": False,
        "l1_lambda": 0.0,
        "hidden_channels": [200, 50, 50, 50, 25],
        "heads": 2,
        "dropout": 0,
        "attention_dropout": 0,
        "integrator_type": "attention",
    }
)

dict_keys(['mrna', 'mirna'])
Fold 1 / 5
torch.Size([200]) torch.Size([200])
isolated sample nodes, isolated gene nodes, mean degree:
tensor(11) tensor(0) tensor(24.6522)
torch.Size([200]) torch.Size([200])
isolated sample nodes, isolated gene nodes, mean degree:
tensor(2) tensor(0) tensor(25.4369)
Found 312.0 interactions
Found 990.0 interactions
Found 422.0 interactions
HeteroData(
  omics=[2],
  feature_names=[2],
  y=[483],
  train_mask=[386],
  val_mask=[48],
  test_mask=[49],
  num_relations=7,
  mrna={ x=[483, 200] },
  mrna_feature={ x=[200, 200] },
  mirna={ x=[483, 200] },
  mirna_feature={ x=[200, 200] },
  (mrna, diff_exp, mrna_feature)={
    edge_index=[2, 11907],
    edge_attr=[11907, 1],
  },
  (mirna, diff_exp, mirna_feature)={
    edge_index=[2, 12286],
    edge_attr=[12286, 1],
  },
  (mrna_feature, interacts, mrna_feature)={ edge_index=[2, 1298] },
  (mrna_feature, interacts, mirna_feature)={ edge_index=[2, 422] },
  (mrna_feature, rev_diff_exp, mrna)={
    edge_index=[2, 11907],
    edge_attr=[11907, 1],
  },
  (mirna_feature, rev_diff_exp, mirna)={
    edge_index=[2, 12286],
    edge_attr=[12286, 1],
  },
  (mirna_feature, rev_interacts, mrna_feature)={ edge_index=[2, 422] }
)
[('mrna', 'diff_exp', 'mrna_feature'), ('mirna', 'diff_exp', 'mirna_feature'), ('mrna_feature', 'interacts', 'mrna_feature'), ('mrna_feature', 'interacts', 'mirna_feature'), ('mrna_feature', 'rev_diff_exp', 'mrna'), ('mirna_feature', 'rev_diff_exp', 'mirna'), ('mirna_feature', 'rev_interacts', 'mrna_feature')]
Starting training...
Epoch: 050:
Train Loss: 0.9449, Train Acc: 0.4922, Train F1 Macro: 0.4543, Train F1 Weighted: 0.4458
Val Loss: 1.0217, Val Acc: 0.4792, Val F1 Macro: 0.4391, Val F1 Weighted: 0.4725
Test Loss: 1.0417, Test Acc: 0.4694, Test F1 Macro: 0.4432, Test F1 Weighted: 0.4418
##################################################
Epoch: 100:
Train Loss: 0.6562, Train Acc: 0.6192, Train F1 Macro: 0.5915, Train F1 Weighted: 0.5713
Val Loss: 0.8527, Val Acc: 0.5833, Val F1 Macro: 0.5131, Val F1 Weighted: 0.5303
Test Loss: 0.8601, Test Acc: 0.5918, Test F1 Macro: 0.5850, Test F1 Weighted: 0.5729
##################################################
Epoch: 150:
Train Loss: 0.5245, Train Acc: 0.6399, Train F1 Macro: 0.7008, Train F1 Weighted: 0.6310
Val Loss: 0.7933, Val Acc: 0.6042, Val F1 Macro: 0.6337, Val F1 Weighted: 0.6076
Test Loss: 0.7810, Test Acc: 0.6735, Test F1 Macro: 0.6813, Test F1 Weighted: 0.6696
##################################################
Epoch: 200:
Train Loss: 0.4945, Train Acc: 0.6736, Train F1 Macro: 0.7310, Train F1 Weighted: 0.6694
Val Loss: 0.7935, Val Acc: 0.6458, Val F1 Macro: 0.6655, Val F1 Weighted: 0.6509
Test Loss: 0.7874, Test Acc: 0.7143, Test F1 Macro: 0.7225, Test F1 Weighted: 0.7140
##################################################
Epoch: 250:
Train Loss: 0.4908, Train Acc: 0.6736, Train F1 Macro: 0.7319, Train F1 Weighted: 0.6698
Val Loss: 0.7894, Val Acc: 0.6458, Val F1 Macro: 0.6736, Val F1 Weighted: 0.6561
Test Loss: 0.7855, Test Acc: 0.7143, Test F1 Macro: 0.7225, Test F1 Weighted: 0.7140
##################################################
Epoch: 300:
Train Loss: 0.4878, Train Acc: 0.6839, Train F1 Macro: 0.7397, Train F1 Weighted: 0.6811
Val Loss: 0.7873, Val Acc: 0.6458, Val F1 Macro: 0.6736, Val F1 Weighted: 0.6561
Test Loss: 0.7815, Test Acc: 0.7143, Test F1 Macro: 0.7225, Test F1 Weighted: 0.7140
##################################################
Epoch: 350:
Train Loss: 0.4848, Train Acc: 0.6917, Train F1 Macro: 0.7458, Train F1 Weighted: 0.6891
Val Loss: 0.7869, Val Acc: 0.6458, Val F1 Macro: 0.6736, Val F1 Weighted: 0.6561
Test Loss: 0.7767, Test Acc: 0.7143, Test F1 Macro: 0.7297, Test F1 Weighted: 0.7148
##################################################
Epoch: 400:
Train Loss: 0.4816, Train Acc: 0.6917, Train F1 Macro: 0.7458, Train F1 Weighted: 0.6891
Val Loss: 0.7885, Val Acc: 0.6667, Val F1 Macro: 0.6916, Val F1 Weighted: 0.6780
Test Loss: 0.7684, Test Acc: 0.6939, Test F1 Macro: 0.7130, Test F1 Weighted: 0.6949
##################################################
Epoch: 450:
Train Loss: 0.4779, Train Acc: 0.6995, Train F1 Macro: 0.7523, Train F1 Weighted: 0.6975
Val Loss: 0.8022, Val Acc: 0.6458, Val F1 Macro: 0.6520, Val F1 Weighted: 0.6565
Test Loss: 0.7511, Test Acc: 0.6939, Test F1 Macro: 0.7130, Test F1 Weighted: 0.6949
##################################################
Epoch: 500:
Train Loss: 0.4729, Train Acc: 0.7073, Train F1 Macro: 0.7616, Train F1 Weighted: 0.7064
Val Loss: 0.8347, Val Acc: 0.6667, Val F1 Macro: 0.6642, Val F1 Weighted: 0.6759
Test Loss: 0.7277, Test Acc: 0.6939, Test F1 Macro: 0.7233, Test F1 Weighted: 0.6975
##################################################
Fold 2 / 5
torch.Size([200]) torch.Size([200])
isolated sample nodes, isolated gene nodes, mean degree:
tensor(8) tensor(0) tensor(24.5280)
torch.Size([200]) torch.Size([200])
isolated sample nodes, isolated gene nodes, mean degree:
tensor(1) tensor(0) tensor(25.4286)
Found 288.0 interactions
Found 1040.0 interactions
Found 379.0 interactions
HeteroData(
  omics=[2],
  feature_names=[2],
  y=[483],
  train_mask=[386],
  val_mask=[48],
  test_mask=[49],
  num_relations=7,
  mrna={ x=[483, 200] },
  mrna_feature={ x=[200, 200] },
  mirna={ x=[483, 200] },
  mirna_feature={ x=[200, 200] },
  (mrna, diff_exp, mrna_feature)={
    edge_index=[2, 11847],
    edge_attr=[11847, 1],
  },
  (mirna, diff_exp, mirna_feature)={
    edge_index=[2, 12282],
    edge_attr=[12282, 1],
  },
  (mrna_feature, interacts, mrna_feature)={ edge_index=[2, 1325] },
  (mrna_feature, interacts, mirna_feature)={ edge_index=[2, 379] },
  (mrna_feature, rev_diff_exp, mrna)={
    edge_index=[2, 11847],
    edge_attr=[11847, 1],
  },
  (mirna_feature, rev_diff_exp, mirna)={
    edge_index=[2, 12282],
    edge_attr=[12282, 1],
  },
  (mirna_feature, rev_interacts, mrna_feature)={ edge_index=[2, 379] }
)
[('mrna', 'diff_exp', 'mrna_feature'), ('mirna', 'diff_exp', 'mirna_feature'), ('mrna_feature', 'interacts', 'mrna_feature'), ('mrna_feature', 'interacts', 'mirna_feature'), ('mrna_feature', 'rev_diff_exp', 'mrna'), ('mirna_feature', 'rev_diff_exp', 'mirna'), ('mirna_feature', 'rev_interacts', 'mrna_feature')]
Starting training...
Epoch: 050:
Train Loss: 0.9228, Train Acc: 0.4016, Train F1 Macro: 0.3938, Train F1 Weighted: 0.3054
Val Loss: 0.9576, Val Acc: 0.3958, Val F1 Macro: 0.3990, Val F1 Weighted: 0.2687
Test Loss: 0.9286, Test Acc: 0.4286, Test F1 Macro: 0.4466, Test F1 Weighted: 0.3098
##################################################
Epoch: 100:
Train Loss: 0.6671, Train Acc: 0.5829, Train F1 Macro: 0.6228, Train F1 Weighted: 0.5234
Val Loss: 0.7688, Val Acc: 0.5417, Val F1 Macro: 0.5903, Val F1 Weighted: 0.4661
Test Loss: 0.6795, Test Acc: 0.5510, Test F1 Macro: 0.5763, Test F1 Weighted: 0.4285
##################################################
Epoch: 150:
Train Loss: 0.5243, Train Acc: 0.7565, Train F1 Macro: 0.7808, Train F1 Weighted: 0.7487
Val Loss: 0.6559, Val Acc: 0.6875, Val F1 Macro: 0.7518, Val F1 Weighted: 0.6826
Test Loss: 0.5331, Test Acc: 0.7755, Test F1 Macro: 0.8241, Test F1 Weighted: 0.7729
##################################################
Epoch: 200:
Train Loss: 0.3895, Train Acc: 0.8912, Train F1 Macro: 0.9011, Train F1 Weighted: 0.8919
Val Loss: 0.5428, Val Acc: 0.6875, Val F1 Macro: 0.7518, Val F1 Weighted: 0.6826
Test Loss: 0.4443, Test Acc: 0.7755, Test F1 Macro: 0.8192, Test F1 Weighted: 0.7752
##################################################
Epoch: 250:
Train Loss: 0.2975, Train Acc: 0.9145, Train F1 Macro: 0.9239, Train F1 Weighted: 0.9152
Val Loss: 0.5198, Val Acc: 0.7083, Val F1 Macro: 0.7750, Val F1 Weighted: 0.7109
Test Loss: 0.4767, Test Acc: 0.8163, Test F1 Macro: 0.8459, Test F1 Weighted: 0.8230
##################################################
Epoch: 300:
Train Loss: 0.6529, Train Acc: 0.8161, Train F1 Macro: 0.7944, Train F1 Weighted: 0.8032
Val Loss: 0.5433, Val Acc: 0.7292, Val F1 Macro: 0.7855, Val F1 Weighted: 0.7330
Test Loss: 0.5809, Test Acc: 0.6939, Test F1 Macro: 0.7624, Test F1 Weighted: 0.6980
##################################################
Epoch: 350:
Train Loss: 0.2445, Train Acc: 0.9249, Train F1 Macro: 0.9332, Train F1 Weighted: 0.9252
Val Loss: 0.4984, Val Acc: 0.7500, Val F1 Macro: 0.7948, Val F1 Weighted: 0.7522
Test Loss: 0.5092, Test Acc: 0.8163, Test F1 Macro: 0.8435, Test F1 Weighted: 0.8226
##################################################
Epoch: 400:
Train Loss: 0.2391, Train Acc: 0.9275, Train F1 Macro: 0.9353, Train F1 Weighted: 0.9278
Val Loss: 0.5039, Val Acc: 0.7500, Val F1 Macro: 0.7948, Val F1 Weighted: 0.7522
Test Loss: 0.5095, Test Acc: 0.8163, Test F1 Macro: 0.8435, Test F1 Weighted: 0.8226
##################################################
Epoch: 450:
Train Loss: 0.2352, Train Acc: 0.9275, Train F1 Macro: 0.9353, Train F1 Weighted: 0.9278
Val Loss: 0.5061, Val Acc: 0.7500, Val F1 Macro: 0.7948, Val F1 Weighted: 0.7522
Test Loss: 0.5107, Test Acc: 0.8163, Test F1 Macro: 0.8435, Test F1 Weighted: 0.8226
##################################################
Epoch: 500:
Train Loss: 0.2313, Train Acc: 0.9275, Train F1 Macro: 0.9353, Train F1 Weighted: 0.9278
Val Loss: 0.5082, Val Acc: 0.7500, Val F1 Macro: 0.7948, Val F1 Weighted: 0.7522
Test Loss: 0.5133, Test Acc: 0.7959, Test F1 Macro: 0.8127, Test F1 Weighted: 0.8016
##################################################
Fold 3 / 5
torch.Size([200]) torch.Size([200])
isolated sample nodes, isolated gene nodes, mean degree:
tensor(10) tensor(0) tensor(24.5466)
torch.Size([200]) torch.Size([200])
isolated sample nodes, isolated gene nodes, mean degree:
tensor(2) tensor(0) tensor(25.5197)
Found 306.0 interactions
Found 1110.0 interactions
Found 415.0 interactions
HeteroData(
  omics=[2],
  feature_names=[2],
  y=[483],
  train_mask=[386],
  val_mask=[48],
  test_mask=[49],
  num_relations=7,
  mrna={ x=[483, 200] },
  mrna_feature={ x=[200, 200] },
  mirna={ x=[483, 200] },
  mirna_feature={ x=[200, 200] },
  (mrna, diff_exp, mrna_feature)={
    edge_index=[2, 11856],
    edge_attr=[11856, 1],
  },
  (mirna, diff_exp, mirna_feature)={
    edge_index=[2, 12326],
    edge_attr=[12326, 1],
  },
  (mrna_feature, interacts, mrna_feature)={ edge_index=[2, 1402] },
  (mrna_feature, interacts, mirna_feature)={ edge_index=[2, 415] },
  (mrna_feature, rev_diff_exp, mrna)={
    edge_index=[2, 11856],
    edge_attr=[11856, 1],
  },
  (mirna_feature, rev_diff_exp, mirna)={
    edge_index=[2, 12326],
    edge_attr=[12326, 1],
  },
  (mirna_feature, rev_interacts, mrna_feature)={ edge_index=[2, 415] }
)
[('mrna', 'diff_exp', 'mrna_feature'), ('mirna', 'diff_exp', 'mirna_feature'), ('mrna_feature', 'interacts', 'mrna_feature'), ('mrna_feature', 'interacts', 'mirna_feature'), ('mrna_feature', 'rev_diff_exp', 'mrna'), ('mirna_feature', 'rev_diff_exp', 'mirna'), ('mirna_feature', 'rev_interacts', 'mrna_feature')]
Starting training...
Epoch: 050:
Train Loss: 1.2999, Train Acc: 0.5026, Train F1 Macro: 0.4548, Train F1 Weighted: 0.5301
Val Loss: 1.3281, Val Acc: 0.5208, Val F1 Macro: 0.4407, Val F1 Weighted: 0.5431
Test Loss: 1.3324, Test Acc: 0.5306, Test F1 Macro: 0.4750, Test F1 Weighted: 0.5286
##################################################
Epoch: 100:
Train Loss: 1.0949, Train Acc: 0.6010, Train F1 Macro: 0.5526, Train F1 Weighted: 0.6011
Val Loss: 1.1552, Val Acc: 0.5208, Val F1 Macro: 0.4648, Val F1 Weighted: 0.5320
Test Loss: 1.1240, Test Acc: 0.5714, Test F1 Macro: 0.5076, Test F1 Weighted: 0.5656
##################################################
Epoch: 150:
Train Loss: 0.6758, Train Acc: 0.7098, Train F1 Macro: 0.6682, Train F1 Weighted: 0.6827
Val Loss: 0.8539, Val Acc: 0.6458, Val F1 Macro: 0.6076, Val F1 Weighted: 0.6284
Test Loss: 0.8397, Test Acc: 0.6327, Test F1 Macro: 0.5304, Test F1 Weighted: 0.5536
##################################################
Epoch: 200:
Train Loss: 0.5330, Train Acc: 0.7617, Train F1 Macro: 0.7750, Train F1 Weighted: 0.7551
Val Loss: 0.8487, Val Acc: 0.6458, Val F1 Macro: 0.6488, Val F1 Weighted: 0.6453
Test Loss: 0.9219, Test Acc: 0.6122, Test F1 Macro: 0.5829, Test F1 Weighted: 0.5838
##################################################
Epoch: 250:
Train Loss: 0.5089, Train Acc: 0.7720, Train F1 Macro: 0.7915, Train F1 Weighted: 0.7673
Val Loss: 0.8612, Val Acc: 0.6458, Val F1 Macro: 0.6522, Val F1 Weighted: 0.6513
Test Loss: 0.9017, Test Acc: 0.6327, Test F1 Macro: 0.5922, Test F1 Weighted: 0.5988
##################################################
Epoch: 300:
Train Loss: 0.5010, Train Acc: 0.7824, Train F1 Macro: 0.8016, Train F1 Weighted: 0.7785
Val Loss: 0.8674, Val Acc: 0.6458, Val F1 Macro: 0.6522, Val F1 Weighted: 0.6513
Test Loss: 0.8982, Test Acc: 0.6122, Test F1 Macro: 0.5829, Test F1 Weighted: 0.5838
##################################################
Epoch: 350:
Train Loss: 0.4940, Train Acc: 0.7850, Train F1 Macro: 0.8056, Train F1 Weighted: 0.7817
Val Loss: 0.8725, Val Acc: 0.6458, Val F1 Macro: 0.6522, Val F1 Weighted: 0.6513
Test Loss: 0.8953, Test Acc: 0.6122, Test F1 Macro: 0.5829, Test F1 Weighted: 0.5838
##################################################
Epoch: 400:
Train Loss: 0.4874, Train Acc: 0.7902, Train F1 Macro: 0.8116, Train F1 Weighted: 0.7871
Val Loss: 0.8775, Val Acc: 0.6458, Val F1 Macro: 0.6522, Val F1 Weighted: 0.6513
Test Loss: 0.8910, Test Acc: 0.6122, Test F1 Macro: 0.5846, Test F1 Weighted: 0.5885
##################################################
Epoch: 450:
Train Loss: 0.4805, Train Acc: 0.7953, Train F1 Macro: 0.8149, Train F1 Weighted: 0.7919
Val Loss: 0.8812, Val Acc: 0.6458, Val F1 Macro: 0.6522, Val F1 Weighted: 0.6513
Test Loss: 0.8842, Test Acc: 0.6122, Test F1 Macro: 0.5846, Test F1 Weighted: 0.5885
##################################################
Epoch: 500:
Train Loss: 0.4740, Train Acc: 0.8031, Train F1 Macro: 0.8231, Train F1 Weighted: 0.8004
Val Loss: 0.8862, Val Acc: 0.6458, Val F1 Macro: 0.6522, Val F1 Weighted: 0.6513
Test Loss: 0.8739, Test Acc: 0.6122, Test F1 Macro: 0.5846, Test F1 Weighted: 0.5885
##################################################
Fold 4 / 5
torch.Size([200]) torch.Size([200])
isolated sample nodes, isolated gene nodes, mean degree:
tensor(11) tensor(0) tensor(24.4679)
torch.Size([200]) torch.Size([200])
isolated sample nodes, isolated gene nodes, mean degree:
tensor(1) tensor(0) tensor(25.4576)
Found 281.0 interactions
Found 800.0 interactions
Found 387.0 interactions
HeteroData(
  omics=[2],
  feature_names=[2],
  y=[483],
  train_mask=[387],
  val_mask=[48],
  test_mask=[48],
  num_relations=7,
  mrna={ x=[483, 200] },
  mrna_feature={ x=[200, 200] },
  mirna={ x=[483, 200] },
  mirna_feature={ x=[200, 200] },
  (mrna, diff_exp, mrna_feature)={
    edge_index=[2, 11818],
    edge_attr=[11818, 1],
  },
  (mirna, diff_exp, mirna_feature)={
    edge_index=[2, 12296],
    edge_attr=[12296, 1],
  },
  (mrna_feature, interacts, mrna_feature)={ edge_index=[2, 1094] },
  (mrna_feature, interacts, mirna_feature)={ edge_index=[2, 387] },
  (mrna_feature, rev_diff_exp, mrna)={
    edge_index=[2, 11818],
    edge_attr=[11818, 1],
  },
  (mirna_feature, rev_diff_exp, mirna)={
    edge_index=[2, 12296],
    edge_attr=[12296, 1],
  },
  (mirna_feature, rev_interacts, mrna_feature)={ edge_index=[2, 387] }
)
[('mrna', 'diff_exp', 'mrna_feature'), ('mirna', 'diff_exp', 'mirna_feature'), ('mrna_feature', 'interacts', 'mrna_feature'), ('mrna_feature', 'interacts', 'mirna_feature'), ('mrna_feature', 'rev_diff_exp', 'mrna'), ('mirna_feature', 'rev_diff_exp', 'mirna'), ('mirna_feature', 'rev_interacts', 'mrna_feature')]
Starting training...
Epoch: 050:
Train Loss: 0.9645, Train Acc: 0.6331, Train F1 Macro: 0.5500, Train F1 Weighted: 0.6015
Val Loss: 1.0097, Val Acc: 0.5625, Val F1 Macro: 0.4596, Val F1 Weighted: 0.5209
Test Loss: 1.0612, Test Acc: 0.5208, Test F1 Macro: 0.4045, Test F1 Weighted: 0.4906
##################################################
Epoch: 100:
Train Loss: 0.7734, Train Acc: 0.6848, Train F1 Macro: 0.6942, Train F1 Weighted: 0.6848
Val Loss: 0.9196, Val Acc: 0.5833, Val F1 Macro: 0.5789, Val F1 Weighted: 0.5814
Test Loss: 1.0114, Test Acc: 0.5833, Test F1 Macro: 0.5321, Test F1 Weighted: 0.5717
##################################################
Epoch: 150:
Train Loss: 0.6852, Train Acc: 0.7054, Train F1 Macro: 0.7416, Train F1 Weighted: 0.7072
Val Loss: 0.7797, Val Acc: 0.6875, Val F1 Macro: 0.6922, Val F1 Weighted: 0.6845
Test Loss: 1.0112, Test Acc: 0.5833, Test F1 Macro: 0.5589, Test F1 Weighted: 0.5796
##################################################
Epoch: 200:
Train Loss: 0.6063, Train Acc: 0.7183, Train F1 Macro: 0.7549, Train F1 Weighted: 0.7195
Val Loss: 0.7226, Val Acc: 0.7083, Val F1 Macro: 0.7153, Val F1 Weighted: 0.7066
Test Loss: 0.9039, Test Acc: 0.6042, Test F1 Macro: 0.5917, Test F1 Weighted: 0.6042
##################################################
Epoch: 250:
Train Loss: 0.5483, Train Acc: 0.7313, Train F1 Macro: 0.7667, Train F1 Weighted: 0.7319
Val Loss: 0.6819, Val Acc: 0.7083, Val F1 Macro: 0.7153, Val F1 Weighted: 0.7066
Test Loss: 0.9837, Test Acc: 0.5833, Test F1 Macro: 0.5860, Test F1 Weighted: 0.5824
##################################################
Epoch: 300:
Train Loss: 0.5088, Train Acc: 0.7468, Train F1 Macro: 0.7803, Train F1 Weighted: 0.7469
Val Loss: 0.6499, Val Acc: 0.7083, Val F1 Macro: 0.7153, Val F1 Weighted: 0.7066
Test Loss: 0.9981, Test Acc: 0.5833, Test F1 Macro: 0.5801, Test F1 Weighted: 0.5851
##################################################
Epoch: 350:
Train Loss: 0.4902, Train Acc: 0.7468, Train F1 Macro: 0.7839, Train F1 Weighted: 0.7474
Val Loss: 0.7197, Val Acc: 0.6667, Val F1 Macro: 0.6729, Val F1 Weighted: 0.6617
Test Loss: 1.0307, Test Acc: 0.5833, Test F1 Macro: 0.5801, Test F1 Weighted: 0.5851
##################################################
Epoch: 400:
Train Loss: 0.4812, Train Acc: 0.7519, Train F1 Macro: 0.7905, Train F1 Weighted: 0.7530
Val Loss: 0.7652, Val Acc: 0.6667, Val F1 Macro: 0.6729, Val F1 Weighted: 0.6617
Test Loss: 0.9758, Test Acc: 0.5833, Test F1 Macro: 0.5801, Test F1 Weighted: 0.5851
##################################################
Epoch: 450:
Train Loss: 0.4780, Train Acc: 0.7519, Train F1 Macro: 0.7905, Train F1 Weighted: 0.7530
Val Loss: 0.7706, Val Acc: 0.6667, Val F1 Macro: 0.6729, Val F1 Weighted: 0.6617
Test Loss: 0.9998, Test Acc: 0.5833, Test F1 Macro: 0.5801, Test F1 Weighted: 0.5851
##################################################
Epoch: 500:
Train Loss: 0.4755, Train Acc: 0.7519, Train F1 Macro: 0.7905, Train F1 Weighted: 0.7530
Val Loss: 0.7727, Val Acc: 0.6667, Val F1 Macro: 0.6729, Val F1 Weighted: 0.6617
Test Loss: 1.0102, Test Acc: 0.5833, Test F1 Macro: 0.5801, Test F1 Weighted: 0.5851
##################################################
Fold 5 / 5
torch.Size([200]) torch.Size([200])
isolated sample nodes, isolated gene nodes, mean degree:
tensor(13) tensor(0) tensor(24.3354)
torch.Size([200]) torch.Size([200])
isolated sample nodes, isolated gene nodes, mean degree:
tensor(1) tensor(0) tensor(25.4658)
Found 273.0 interactions
Found 820.0 interactions
Found 404.0 interactions
HeteroData(
  omics=[2],
  feature_names=[2],
  y=[483],
  train_mask=[387],
  val_mask=[48],
  test_mask=[48],
  num_relations=7,
  mrna={ x=[483, 200] },
  mrna_feature={ x=[200, 200] },
  mirna={ x=[483, 200] },
  mirna_feature={ x=[200, 200] },
  (mrna, diff_exp, mrna_feature)={
    edge_index=[2, 11754],
    edge_attr=[11754, 1],
  },
  (mirna, diff_exp, mirna_feature)={
    edge_index=[2, 12300],
    edge_attr=[12300, 1],
  },
  (mrna_feature, interacts, mrna_feature)={ edge_index=[2, 1088] },
  (mrna_feature, interacts, mirna_feature)={ edge_index=[2, 404] },
  (mrna_feature, rev_diff_exp, mrna)={
    edge_index=[2, 11754],
    edge_attr=[11754, 1],
  },
  (mirna_feature, rev_diff_exp, mirna)={
    edge_index=[2, 12300],
    edge_attr=[12300, 1],
  },

(tensor([[0.6875, 0.7048, 0.6988],
         [0.7708, 0.8077, 0.7714],
         [0.6667, 0.6651, 0.6669],
         [0.7083, 0.7153, 0.7066],
         [0.6667, 0.6458, 0.6744]]),
 tensor([[0.6939, 0.7130, 0.6949],
         [0.8367, 0.8537, 0.8397],
         [0.6939, 0.6202, 0.6426],
         [0.6042, 0.5991, 0.6016],
         [0.7292, 0.7417, 0.7277]]))

In [6]:
val = torch.tensor([[0.9375, 0.9279, 0.9375],
         [0.8542, 0.8671, 0.8519],
         [0.8542, 0.8676, 0.8546],
         [0.7917, 0.7637, 0.7901],
         [0.8333, 0.8551, 0.8358]])
test = torch.tensor([[0.7959, 0.7892, 0.8037],
         [0.8367, 0.8537, 0.8397],
         [0.8776, 0.8746, 0.8783],
         [0.9583, 0.9664, 0.9573],
         [0.8125, 0.8316, 0.8109]])

print("BipartiteGNN (mrna, mirna, meth) results:")
print(f"| BipartiteGNN val | {val[:, 0].mean():.2f} +/- {val[:, 0].std():.2f} | {val[:, 1].mean():.2f} +/- {val[:, 1].std():.2f} | {val[:, 2].mean():.2f} +/- {val[:, 2].std():.2f} |")
print(f"| BipartiteGNN test | {test[:, 0].mean():.2f} +/- {test[:, 0].std():.2f} | {test[:, 1].mean():.2f} +/- {test[:, 1].std():.2f} | {test[:, 2].mean():.2f} +/- {test[:, 2].std():.2f} |")

MOGONET GAT (mrna, mirna, meth) results:
| MOGONET GAT val | 0.85 +/- 0.05 | 0.86 +/- 0.06 | 0.85 +/- 0.05 |
| MOGONET GAT test | 0.86 +/- 0.06 | 0.86 +/- 0.07 | 0.86 +/- 0.06 |

# brca results using all omics

| Method | ACC | F1 | F1 Weighted |
| KNN | 0.79 +/- 0.02 | 0.78 +/- 0.03 | 0.77 +/- 0.03 |
| SVM | 0.83 +/- 0.01 | 0.83 +/- 0.02 | 0.83 +/- 0.01 |
| XGBoost | 0.88 +/- 0.02 | 0.88 +/- 0.03 | 0.88 +/- 0.02 |
| MLP regularization : None | 0.85 +/- 0.03 | 0.85 +/- 0.03 | 0.85 +/- 0.03 |
| MOGONET GAT | 0.86 +/- 0.04 | 0.87 +/- 0.04 | 0.86 +/- 0.04 |