In [75]:
%load_ext autoreload
%autoreload 2

In [76]:
import numpy as np
import polars as pl

In [2]:
clinicalMatrix = pl.read_csv("xena_brca_data/TCGA.BRCA.sampleMap_BRCA_clinicalMatrix", separator="\t", infer_schema_length=0)

cM = clinicalMatrix.filter(pl.col("PAM50_mRNA_nature2012") != "null")
cMrnaseq= clinicalMatrix.filter(pl.col("PAM50Call_RNAseq") != "null")

In [3]:
cM["sampleID"][0]

'TCGA-A1-A0SD-01'

In [4]:
def get_counts_in_col(df, col_name):
    return np.unique(df[col_name].to_numpy(), return_counts=True)

get_counts_in_col(cM, "PAM50_mRNA_nature2012")

(array(['Basal-like', 'HER2-enriched', 'Luminal A', 'Luminal B',
        'Normal-like'], dtype=object),
 array([ 98,  58, 231, 127,   8]))

In [5]:
get_counts_in_col(cMrnaseq, "PAM50Call_RNAseq")

(array(['Basal', 'Her2', 'LumA', 'LumB', 'Normal'], dtype=object),
 array([142,  67, 434, 194, 119]))

In [13]:
rna = pl.read_csv("xena_brca_data/TCGA.BRCA.sampleMap_HiSeqV2", separator="\t")
cna = pl.read_csv("xena_brca_data/TCGA.BRCA.sampleMap_Gistic2_CopyNumber_Gistic2_all_thresholded.by_genes", separator="\t")
mirna = pl.read_csv("xena_brca_data/TCGA.BRCA.sampleMap_miRNA_HiSeq_gene", separator="\t", null_values=["NA"])

In [7]:
rna.head()

shape: (5, 1_219)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sample    ┆ TCGA-AR-A ┆ TCGA-D8-A ┆ TCGA-BH-A ┆ … ┆ TCGA-B6-A ┆ TCGA-BH-A ┆ TCGA-3C-A ┆ TCGA-B6- │
│ ---       ┆ 5QQ-01    ┆ 1JA-01    ┆ 0BQ-01    ┆   ┆ 0X7-01    ┆ 1EV-11    ┆ ALJ-01    ┆ A0X1-01  │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ ARHGEF10L ┆ 9.5074    ┆ 7.4346    ┆ 9.3216    ┆ … ┆ 10.5745   ┆ 9.4048    ┆ 10.9468   ┆ 10.3164  │
│ HIF3A     ┆ 1.5787    ┆ 3.6607    ┆ 2.7224    ┆ … ┆ 4.0696    ┆ 7.2537    ┆ 0.931     ┆ 2.4191   │
│ RNF17     ┆ 0.0       ┆ 0.6245    ┆ 0.5526    ┆ … ┆ 0.4258    ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ RNF10     ┆ 11.3676   ┆ 11.9181   ┆ 11.9665   ┆ … ┆ 11.8663   ┆ 11.546    ┆ 12.2616   ┆ 12.157   │
│ RNF11     ┆ 11.1292   ┆ 13.5273   ┆ 11.4105   ┆ … ┆ 10.7644   ┆ 11.8774   ┆ 10.7842   ┆ 11.242   │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [8]:
cna.head()

shape: (5, 1_081)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Gene      ┆ TCGA-3C-A ┆ TCGA-3C-A ┆ TCGA-3C-A ┆ … ┆ TCGA-XX-A ┆ TCGA-XX-A ┆ TCGA-Z7-A ┆ TCGA-Z7- │
│ Symbol    ┆ AAU-01    ┆ ALI-01    ┆ ALJ-01    ┆   ┆ 899-01    ┆ 89A-01    ┆ 8R5-01    ┆ A8R6-01  │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ i64       ┆ i64       ┆ i64       ┆   ┆ i64       ┆ i64       ┆ i64       ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ ACAP3     ┆ 0         ┆ -1        ┆ -1        ┆ … ┆ 0         ┆ -1        ┆ -1        ┆ 0        │
│ ACTRT2    ┆ 0         ┆ -1        ┆ -1        ┆ … ┆ 0         ┆ -1        ┆ -1        ┆ 0        │
│ AGRN      ┆ 0         ┆ -1        ┆ -1        ┆ … ┆ 0         ┆ -1        ┆ -1        ┆ 0        │
│ ANKRD65   ┆ 0         ┆ -1        ┆ -1        ┆ … ┆ 0         ┆ -1        ┆ -1        ┆ 0        │
│ ATAD3A    ┆ 0         ┆ -1        ┆ -1        ┆ … ┆ 0         ┆ -1        ┆ -1        ┆ 0        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [9]:
# get common samples
rna_sample_names = rna.columns[1:]

In [14]:
mirna.head()

shape: (5, 833)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sample    ┆ TCGA-OL-A ┆ TCGA-3C-A ┆ TCGA-AR-A ┆ … ┆ TCGA-BH-A ┆ TCGA-E9-A ┆ TCGA-GM-A ┆ TCGA-AC- │
│ ---       ┆ 66H-01    ┆ ALK-01    ┆ 1AH-01    ┆   ┆ 1F0-01    ┆ 1RB-11    ┆ 4E0-01    ┆ A5XU-01  │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ MIMAT0019 ┆ 0.2381    ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 868       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ MIMAT0019 ┆ null      ┆ 0.2117    ┆ null      ┆ … ┆ 0.7569    ┆ 0.1298    ┆ null      ┆ null     │
│ 869       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ MIMAT0019 ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 860       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ MIMAT0019 ┆ null      ┆ null      ┆ null      ┆ … ┆ 0.7569    ┆ null      ┆ null      ┆ 0.2444   │
│ 862       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ MIMAT0019 ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 863       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [36]:
mirna = mirna.drop_nulls()

In [37]:
mirna

shape: (225, 833)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ sample    ┆ TCGA-OL-A ┆ TCGA-3C-A ┆ TCGA-AR-A ┆ … ┆ TCGA-BH-A ┆ TCGA-E9-A ┆ TCGA-GM-A ┆ TCGA-AC- │
│ ---       ┆ 66H-01    ┆ ALK-01    ┆ 1AH-01    ┆   ┆ 1F0-01    ┆ 1RB-11    ┆ 4E0-01    ┆ A5XU-01  │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ MIMAT0000 ┆ 5.827901  ┆ 4.864784  ┆ 5.897214  ┆ … ┆ 6.502696  ┆ 6.483298  ┆ 5.618528  ┆ 6.027982 │
│ 764       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ MIMAT0000 ┆ 4.187861  ┆ 3.515156  ┆ 4.490978  ┆ … ┆ 5.561336  ┆ 6.903009  ┆ 3.314271  ┆ 3.927624 │
│ 761       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ MIMAT0000 ┆ 3.641958  ┆ 3.411793  ┆ 5.214793  ┆ … ┆ 5.776288  ┆ 5.100828  ┆ 3.737816  ┆ 3.780305 │
│ 760       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ MIMAT0000 ┆ 9.971574  ┆ 8.13257   ┆ 9.097876  ┆ … ┆ 8.088057  ┆ 7.62856   ┆ 8.21375   ┆ 8.380112 │
│ 763       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ MIMAT0000 ┆ 3.343561  ┆ 3.753572  ┆ 3.361545  ┆ … ┆ 4.802402  ┆ 4.864959  ┆ 2.902868  ┆ 3.301954 │
│ 762       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ MIMAT0004 ┆ 5.653723  ┆ 4.353548  ┆ 4.097168  ┆ … ┆ 5.881361  ┆ 5.558159  ┆ 6.332708  ┆ 4.70656  │
│ 673       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ MIMAT0004 ┆ 7.345745  ┆ 7.790264  ┆ 8.362635  ┆ … ┆ 9.177655  ┆ 9.840348  ┆ 6.439103  ┆ 7.367563 │
│ 672       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ MIMAT0004 ┆ 5.443786  ┆ 4.963132  ┆ 5.505855  ┆ … ┆ 9.194728  ┆ 9.013876  ┆ 5.101008  ┆ 5.266052 │
│ 585       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ MIMAT0004 ┆ 4.348927  ┆ 3.71941   ┆ 5.39303   ┆ … ┆ 6.225204  ┆ 5.636668  ┆ 3.071195  ┆ 4.138945 │
│ 584       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ MIMAT0004 ┆ 4.493867  ┆ 3.534975  ┆ 4.491025  ┆ … ┆ 6.678184  ┆ 8.22925   ┆ 2.569552  ┆ 4.842779 │
│ 586       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [18]:
# load mirna db
mirna_db = pl.read_csv("mirna_db/miRNAs_miRandola_v02_2017.txt", separator="\t")

In [19]:
mirna_db

shape: (1_010, 5)
┌───────────────────────┬───────────────────────┬───────────────────┬────────────────┬─────────────┐
│ mature_mirna_from_lit ┆ miRBase_Last_Version  ┆ miRBase_accession ┆ miRBase_family ┆ organism    │
│ erature               ┆ ---                   ┆ ---               ┆ ---            ┆ ---         │
│ ---                   ┆ str                   ┆ str               ┆ str            ┆ str         │
│ str                   ┆                       ┆                   ┆                ┆             │
╞═══════════════════════╪═══════════════════════╪═══════════════════╪════════════════╪═════════════╡
│ bta-let-7             ┆ bta-let-7a-5p         ┆ MIMAT0003844      ┆ let-7          ┆ Bos taurus  │
│ bta-let-7-5p          ┆ bta-let-7a-5p         ┆ MIMAT0003844      ┆ let-7          ┆ Bos taurus  │
│ bta-let-7a            ┆ bta-let-7a-5p         ┆ MIMAT0003844      ┆ let-7          ┆ Bos taurus  │
│ bta-let-7b            ┆ bta-let-7b            ┆ MIMAT0004331      ┆ let-7          ┆ Bos taurus  │
│ bta-let-7c            ┆ bta-let-7c            ┆ MIMAT0004332      ┆ let-7          ┆ Bos taurus  │
│ …                     ┆ …                     ┆ …                 ┆ …              ┆ …           │
│ rno-miR-322-3p        ┆ rno-miR-322-3p        ┆ MIMAT0000547      ┆ mir-322        ┆ male albino │
│                       ┆                       ┆                   ┆                ┆ sprague     │
│ rno-miR-324-3p        ┆ rno-miR-324-3p        ┆ MIMAT0000554      ┆ mir-324        ┆ male albino │
│                       ┆                       ┆                   ┆                ┆ sprague     │
│ rno-miR-421-3p        ┆ rno-miR-421-3p        ┆ MIMAT0017175      ┆ mir-95         ┆ male albino │
│                       ┆                       ┆                   ┆                ┆ sprague     │
│ rno-miR-463-5p        ┆ rno-miR-463-5p        ┆ MIMAT0017309      ┆ mir-463        ┆ male albino │
│                       ┆                       ┆                   ┆                ┆ sprague     │
│ rno-miR-674-3p        ┆ rno-miR-674-3p        ┆ MIMAT0005330      ┆ mir-674        ┆ male albino │
│                       ┆                       ┆                   ┆                ┆ sprague     │
└───────────────────────┴───────────────────────┴───────────────────┴────────────────┴─────────────┘

In [30]:
mimat2mature = dict(mirna_db.select("miRBase_accession","mature_mirna_from_literature").iter_rows())
mimat2mature

{'MIMAT0003844': 'bta-let-7a',
 'MIMAT0004331': 'bta-let-7b',
 'MIMAT0004332': 'bta-let-7c',
 'MIMAT0003810': 'bta-let-7d',
 'MIMAT0004333': 'bta-let-7e',
 'MIMAT0003519': 'bta-let-7f',
 'MIMAT0003851': 'bta-let-7i',
 'MIMAT0009215': 'bta-miR-100',
 'MIMAT0003521': 'bta-miR-103',
 'MIMAT0003785': 'bta-miR-107',
 'MIMAT0003786': 'bta-miR-10a',
 'MIMAT0003538': 'bta-miR-125a',
 'MIMAT0003539': 'bta-mir-125b',
 'MIMAT0003540': 'bta-miR-126-3p',
 'MIMAT0009232': 'bta-miR-141',
 'MIMAT0009233': 'bta-miR-143',
 'MIMAT0003542': 'bta-miR-145',
 'MIMAT0024570': 'bta-miR-149-5p',
 'MIMAT0003524': 'bta-miR-151-3p',
 'MIMAT0003523': 'bta-miR-151-5p',
 'MIMAT0009238': 'bta-miR-152',
 'MIMAT0003815': 'bta-miR-17-5p',
 'MIMAT0003543': 'bta-miR-181a',
 'MIMAT0009244': 'bta-miR-182',
 'MIMAT0003819': 'bta-miR-191',
 'MIMAT0004335': 'bta-miR-195',
 'MIMAT0004337': 'bta-miR-19b',
 'MIMAT0003822': 'bta-miR-200a',
 'MIMAT0003842': 'bta-miR-200b',
 'MIMAT0003823': 'bta-miR-200c',
 'MIMAT0003545': 'bta-miR-205',
 'MIMAT0003527': 'bta-miR-20a',
 'MIMAT0003528': 'bta-miR-21-5p',
 'MIMAT0012536': 'bta-miR-22-3p',
 'MIMAT0003529': 'bta-miR-221',
 'MIMAT0003530': 'bta-miR-222',
 'MIMAT0003827': 'bta-miR-23a',
 'MIMAT0003852': 'bta-miR-23b-3p',
 'MIMAT0003840': 'bta-miR-24-3p',
 'MIMAT0003516': 'bta-miR-26a',
 'MIMAT0003532': 'bta-miR-27a-3p',
 'MIMAT0003546': 'bta-miR-27b',
 'MIMAT0003518': 'bta-miR-29a',
 'MIMAT0003841': 'bta-miR-30a-5p',
 'MIMAT0003533': 'bta-miR-30d',
 'MIMAT0003548': 'bta-miR-31',
 'MIMAT0003534': 'bta-miR-320a',
 'MIMAT0003846': 'bta-miR-342',
 'MIMAT0003830': 'bta-miR-361',
 'MIMAT0003833': 'bta-miR-425-3p',
 'MIMAT0003832': 'bta-miR-425-5p',
 'MIMAT0009315': 'bta-miR-429',
 'MIMAT0004344': 'bta-miR-660',
 'MIMAT0003837': 'bta-miR-93',
 'MIMAT0003537': 'bta-mir-99a-5p',
 'MIMAT0001818': 'dre-miR-122',
 'MIMAT0003390': 'ebv-miR-BART1-3p',
 'MIMAT0000999': 'ebv-miR-BART1-5p',
 'MIMAT0003420': 'ebv-miR-BART10',
 'MIMAT0003423': 'ebv-miR-BART12',
 'MIMAT0003424': 'ebv-miR-BART13',
 'MIMAT0001000': 'ebv-miR-BART2',
 'MIMAT0003411': 'ebv-miR-BART3',
 'MIMAT0003412': 'ebv-miR-BART4',
 'MIMAT0003413': 'ebv-miR-BART5',
 'MIMAT0003415': 'ebv-miR-BART6-3p',
 'MIMAT0003414': 'ebv-miR-BART6-5p',
 'MIMAT0003416': 'ebv-miR-BART7',
 'MIMAT0003417': 'ebv-miR-BART8',
 'MIMAT0003418': 'ebv-miR-BART8*',
 'MIMAT0000995': 'ebv-miR-BHRF1-1',
 'MIMAT0000997': 'ebv-miR-BHRF1-2',
 'MIMAT0000996': 'ebv-miR-BHRF1-2*',
 'MIMAT0000998': 'ebv-miR-BHRF1-3',
 'MIMAT0012951': 'eca-miR-101',
 'MIMAT0013194': 'eca-miR-106a',
 'MIMAT0013054': 'eca-miR-106b',
 'MIMAT0012906': 'eca-miR-124',
 'MIMAT0013008': 'eca-miR-125a-5p',
 'MIMAT0013021': 'eca-miR-132',
 'MIMAT0013127': 'eca-miR-134',
 'MIMAT0013078': 'eca-miR-135a',
 'MIMAT0012952': 'eca-miR-135b',
 'MIMAT0012983': 'eca-miR-139-5p',
 'MIMAT0012973': 'eca-miR-149',
 'MIMAT0013084': 'eca-miR-17',
 'MIMAT0013178': 'eca-miR-181a',
 'MIMAT0013179': 'eca-miR-181b',
 'MIMAT0012999': 'eca-miR-187',
 'MIMAT0013198': 'eca-miR-188-5p',
 'MIMAT0013049': 'eca-miR-192',
 'MIMAT0013056': 'eca-miR-193b',
 'MIMAT0013027': 'eca-miR-195',
 'MIMAT0012959': 'eca-miR-197',
 'MIMAT0013086': 'eca-miR-19a',
 'MIMAT0013087': 'eca-miR-19b',
 'MIMAT0013088': 'eca-miR-20a',
 'MIMAT0013202': 'eca-miR-20b',
 'MIMAT0013029': 'eca-miR-21',
 'MIMAT0013030': 'eca-miR-212',
 'MIMAT0012963': 'eca-miR-214',
 'MIMAT0013190': 'eca-miR-215',
 'MIMAT0013031': 'eca-miR-22',
 'MIMAT0013204': 'eca-miR-222',
 'MIMAT0013205': 'eca-miR-223',
 'MIMAT0012986': 'eca-miR-23a',
 'MIMAT0013113': 'eca-miR-23b',
 'MIMAT0012987': 'eca-miR-24',
 'MIMAT0013057': 'eca-miR-25',
 'MIMAT0012988': 'eca-miR-27a',
 'MIMAT0013093': 'eca-miR-28-3p',
 'MIMAT0013005': 'eca-miR-30b',
 'MIMAT0012916': 'eca-miR-30e',
 'MIMAT0013115': 'eca-miR-31',
 'MIMAT0013131': 'eca-miR-323-5p',
 'MIMAT0013034': 'eca-miR-324-3p',
 'MIMAT0013033': 'eca-miR-324-5p',
 'MIMAT0012989': 'eca-miR-326',
 'MIMAT0012929': 'eca-miR-328',
 'MIMAT0013137': 'eca-miR-342-3p',
 'MIMAT0012902': 'eca-miR-346',
 'MIMAT0013210': 'eca-miR-362-5p',
 'MIMAT0013142': 'eca-miR-370',
 'MIMAT0034639': 'eca-miR-372',
 'MIMAT0013213': 'eca-miR-374a',
 'MIMAT0013146': 'eca-miR-377',
 'MIMAT0013068': 'eca-miR-378',
 'MIMAT0013152': 'eca-miR-409-3p',
 'MIMAT0013151': 'eca-miR-409-5p',
 'MIMAT0013154': 'eca-miR-411',
 'MIMAT0013216': 'eca-miR-421',
 'MIMAT0013158': 'eca-miR-433',
 'MIMAT0013160': 'eca-miR-485-3p',
 'MIMAT0013186': 'eca-miR-486-5p',
 'MIMAT0012965': 'eca-miR-488',
 'MIMAT0013164': 'eca-miR-494',
 'MIMAT0013109': 'eca-miR-499-3p',
 'MIMAT0013227': 'eca-miR-503',
 'MIMAT0013236': 'eca-miR-532-3p',
 'MIMAT0013167': 'eca-miR-539',
 'MIMAT0013089': 'eca-miR-92a',
 'MIMAT0012966': 'eca-miR-92b',
 'MIMAT0013060': 'eca-miR-93',
 'NULL': 'rno-miR-148a',
 'MIMAT0000062': 'hsa-let-7a-5p',
 'MIMAT0004481': 'hsa-let-7a*',
 'MIMAT0000063': 'hsa-let-7b-5p',
 'MIMAT0004482': 'hsa-let-7b-3p',
 'MIMAT0000064': 'hsa-let-7c-5p',
 'MIMAT0026472': 'hsa-let-7c*',
 'MIMAT0000065': 'hsa-let-7d-5p',
 'MIMAT0004484': 'hsa-let-7d-3p',
 'MIMAT0000066': 'hsa-let-7e-5p',
 'MIMAT0000067': 'hsa-let-7f-5p',
 'MIMAT0004486': 'hsa-let-7f-1*',
 'MIMAT0000414': 'hsa-let-7g-5p',
 'MIMAT0000415': 'hsa-let-7i-5p',
 'MIMAT0004585': 'hsa-let-7i*',
 'MIMAT0000416': 'hsa-miR-1',
 'MIMAT0000098': 'hsa-miR-100-5p',
 'MIMAT0000099': 'hsa-miR-101-3p',
 'MIMAT0000101': 'hsa-miR-103a-3p',
 'MIMAT0007402': 'hsa-miR-103b',
 'MIMAT0000102': 'hsa-miR-105',
 'MIMAT0000103': 'hsa-miR-106a-5p',
 'MIMAT0004517': 'hsa-miR-106a*',
 'MIMAT0000680': 'hsa-miR-106b-5p',
 'MIMAT0004672': 'hsa-miR-106b*',
 'MIMAT0000104': 'hsa-miR-107',
 'MIMAT0000253': 'hsa-miR-10a-5p',
 'MIMAT0004555': 'hsa-miR-10a-3p',
 'MIMAT0000254': 'hsa-miR-10b-5p',
 'MIMAT0004556': 'hsa-miR-10b-3p',
 'MIMAT0005825': 'hsa-miR-1180',
 'MIMAT0005828': 'hsa-miR-1183',
 'MIMAT0005829': 'hsa-miR-1184',
 'MIMAT0005871': 'hsa-miR-1207-5p',
 'MIMAT0000421': 'hsa-miR-122a',
 'MIMAT0005458': 'hsa-miR-1224-5p',
 'MIMAT0005572': 'hsa-miR-1225-5p',
 'MIMAT0005576': 'hsa-miR-1226*',
 'MIMAT0005583': 'hsa-miR-1228',
 'MIMAT0005588': 'hsa-miR-1233',
 'MIMAT0005589': 'hsa-miR-1234',
 'MIMAT0005591': 'hsa-miR-1236',
 'MIMAT0005593': 'hsa-miR-1238',
 'MIMAT0000422': 'hsa-miR-124a',
 'MIMAT0005898': 'hsa-miR-1246',
 'MIMAT0005900': 'hsa-miR-1248',
 'MIMAT0005901': 'hsa-miR-1249',
 'MIMAT0005905': 'hsa-miR-1254',
 'MIMAT0000443': 'hsa-miR-125a-5p',
 'MIMAT0004602': 'hsa-miR-125a-3p',
 'MIMAT0000423': 'hsa-miR-125b-5p',
 'MIMAT0004592': 'hsa-miR-125b-1*',
 None: 'oar-miR-9',
 'MIMAT0004603': 'hsa-miR-125b-2*',
 'MIMAT0000445': 'hsa-miR-126-3p',
 'MIMAT0000444': 'hsa-miR-126*',
 'MIMAT0005911': 'hsa-miR-1260',
 'MIMAT0005915': 'hsa-miR-1263',
 'MIMAT0005920': 'hsa-miR-1266',
 'MIMAT0005922': 'hsa-miR-1268',
 'MIMAT0000446': 'hsa-miR-127-3p',
 'MIMAT0005796': 'hsa-miR-1271',
 'MIMAT0005925': 'hsa-miR-1272',
 'MIMAT0015090': 'hsa-miR-1273d',
 'MIMAT0005929': 'hsa-miR-1275',
 'MIMAT0005930': 'hsa-miR-1276',
 'MIMAT0000424': 'hsa-miR-128b',
 'MIMAT0005876': 'hsa-miR-1285',
 'MIMAT0000242': 'hsa-miR-129-5p',
 'MIMAT0004548': 'hsa-miR-129*',
 'MIMAT0005880': 'hsa-miR-1290',
 'MIMAT0005943': 'hsa-miR-1292',
 'MIMAT0005893': 'hsa-miR-1305',
 'MIMAT0022727': 'hsa-miR-1307-5p',
 'MIMAT0000425': 'hsa-miR-130a-3p',
 'MIMAT0004593': 'hsa-miR-130a*',
 'MIMAT0000691': 'hsa-miR-130b',
 'MIMAT0000426': 'hsa-miR-132',
 'MIMAT0004594': 'hsa-miR-132*',
 'MIMAT0005795': 'hsa-miR-1323',
 'MIMAT0000427': 'hsa-miR-133a',
 'MIMAT0000770': 'hsa-miR-133b',
 'MIMAT0000447': 'hsa-miR-134',
 'MIMAT0000428': 'hsa-miR-135a-5p',
 'MIMAT0004595': 'hsa-miR-135a*',
 'MIMAT0000758': 'hsa-miR-135b-5p',
 'MIMAT0004698': 'hsa-miR-135b*',
 'MIMAT0000448': 'hsa-miR-136-5p',
 'MIMAT0000429': 'hsa-miR-137',
 'MIMAT0000430': 'hsa-miR-138-5p',
 'MIMAT0004607': 'hsa-miR-138-1*',
 'MIMAT0004596': 'hsa-miR-138-2*',
 'MIMAT0004552': 'hsa-miR-139-3p',
 'MIMAT0000250': 'hsa-miR-139-5p',
 'MIMAT0000431': 'hsa-miR-140-5p',
 'MIMAT0004597': 'hsa-miR-140-3p',
 'MIMAT0000432': 'hsa-miR-141-3p',
 'MIMAT0004598': 'hsa-miR-141*',
 'MIMAT0000434': 'hsa-miR-142-3p',
 'MIMAT0000433': 'hsa-miR-142-5p',
 'MIMAT0000435': 'hsa-miR-143-3p',
 'MIMAT0000436': 'hsa-miR-144',
 'MIMAT0004600': 'hsa-miR-144*',
 'MIMAT0000437': 'hsa-miR-145-5p',
 'MIMAT0004601': 'hsa-miR-145*',
 'MIMAT0000449': 'hsa-miR-146a',
 'MIMAT0007347': 'hsa-miR-1469',
 'MIMAT0002809': 'hsa-miR-146b-5p',
 'MIMAT0000251': 'hsa-miR-147',
 'MIMAT0000243': 'hsa-miR-148a-3p',
 'MIMAT0004549': 'hsa-miR-148a*',
 'MIMAT0000759': 'hsa-miR-148b-3p',
 'MIMAT0000450': 'hsa-miR-149-5p',
 'MIMAT0004609': 'hsa-miR-149*',
 'MIMAT0000451': 'hsa-miR-150',
 'MIMAT0004610': 'hsa-miR-150*',
 'MIMAT0000757': 'hsa-miR-151a-3p',
 'MIMAT0004697': 'hsa-miR-151a-5p',
 'MIMAT0000438': 'hsa-miR-152',
 'MIMAT0000439': 'hsa-miR-153',
 'MIMAT0000452': 'hsa-miR-154',
 'MIMAT0000646': 'hsa-miR-155-5p',
 'MIMAT0000068': 'hsa-miR-15a-5p',
 'MIMAT0004488': 'hsa-miR-15a*',
 'MIMAT0000417': 'hsa-miR-15b-5p',
 'MIMAT0004586': 'hsa-miR-15b*',
 'MIMAT0000069': 'hsa-miR-16-5p',
 'MIMAT0004489': 'hsa-miR-16-1*',
 'MIMAT0004518': 'hsa-miR-16-2*',
 'MIMAT0000070': 'hsa-miR-17-5p',
 'MIMAT0000071': 'hsa-miR-17-3p',
 'MIMAT0000256': 'hsa-miR-181a-5p',
 'MIMAT0000270': 'hsa-miR-181a*',
 'MIMAT0004558': 'hsa-miR-181a-2*',
 'MIMAT0000257': 'hsa-miR-181b-5p',
 'MIMAT0000258': 'hsa-miR-181c',
 'MIMAT0004559': 'hsa-miR-181c*',
 'MIMAT0002821': 'hsa-miR-181d',
 'MIMAT0000259': 'hsa-miR-182-5p',
 'MIMAT0000260': 'hsa-miR-182*',
 'MIMAT0000261': 'hsa-miR-183-5p',
 'MIMAT0000454': 'hsa-miR-184',
 'MIMAT0000455': 'hsa-miR-185-5p',
 'MIMAT0000456': 'hsa-miR-186-5p',
 'MIMAT0000262': 'hsa-miR-187-3p',
 'MIMAT0004561': 'hsa-miR-187*',
 'MIMAT0000457': 'hsa-miR-188-5p',
 'MIMAT0004613': 'hsa-miR-188-3p',
 'MIMAT0000079': 'hsa-miR-189',
 'MIMAT0000072': 'hsa-miR-18a-5p',
 'MIMAT0002891': 'hsa-miR-18a*',
 'MIMAT0001412': 'hsa-miR-18b-5p',
 'MIMAT0000458': 'hsa-miR-190a',
 'MIMAT0007881': 'hsa-miR-1908',
 'MIMAT0004929': 'hsa-miR-190b',
 'MIMAT0000440': 'hsa-miR-191-5p',
 'MIMAT0001618': 'hsa-miR-191*',
 'MIMAT0007892': 'hsa-miR-1915-3p',
 'MIMAT0000222': 'hsa-miR-192-5p',
 'MIMAT0004543': 'hsa-miR-192*',
 'MIMAT0000459': 'hsa-miR-193a-3p',
 'MIMAT0004614': 'hsa-miR-193a-5p',
 'MIMAT0002819': 'hsa-miR-193b-3p',
 'MIMAT0004767': 'hsa-miR-193b*',
 'MIMAT0000460': 'hsa-miR-194-5p',
 'MIMAT0000461': 'hsa-miR-195-5p',
 'MIMAT0000226': 'hsa-miR-196a-5p',
 'MIMAT0004562': 'hsa-miR-196a*',
 'MIMAT0001080': 'hsa-miR-196b-5p',
 'MIMAT0000227': 'hsa-miR-197-3p',
 'MIMAT0009448': 'hsa-miR-1973',
 'MIMAT0000228': 'hsa-miR-198',
 'MIMAT0000231': 'hsa-miR-199a-5p',
 'MIMAT0000232': 'hsa-miR-199a-3p',
 'MIMAT0000263': 'hsa-miR-199b-5p',
 'MIMAT0000073': 'hsa-miR-19a-3p',
 'MIMAT0000074': 'hsa-miR-19b-3p',
 'MIMAT0004491': 'hsa-miR-19b-1*',
 'MIMAT0000075': 'hsa-miR-20a-5p',
 'MIMAT0000682': 'hsa-miR-200a-3p',
 'MIMAT0001620': 'hsa-miR-200a-5p',
 'MIMAT0000318': 'hsa-miR-200b-3p',
 'MIMAT0004571': 'hsa-miR-200b-5p',
 'MIMAT0000617': 'hsa-miR-200c-3p',
 'MIMAT0002811': 'hsa-miR-202',
 'MIMAT0000264': 'hsa-mir-203a-3p',
 'MIMAT0000265': 'hsa-miR-204',
 'MIMAT0022693': 'hsa-miR-204-3p',
 'MIMAT0000266': 'hsa-miR-205-5p',
 'MIMAT0000462': 'hsa-miR-206',
 'MIMAT0000241': 'hsa-miR-208a',
 'MIMAT0004960': 'hsa-miR-208b',
 'MIMAT0004493': 'hsa-miR-20a*',
 'MIMAT0001413': 'hsa-miR-20b-5p',
 'MIMAT0000076': 'hsa-miR-21-5p',
 'MIMAT0004494': 'hsa-miR-21*',
 'MIMAT0000267': 'hsa-miR-210',
 'MIMAT0010133': 'hsa-miR-2110',
 'MIMAT0000269': 'hsa-miR-212',
 'MIMAT0000271': 'hsa-miR-214',
 'MIMAT0000272': 'hsa-miR-215',
 'MIMAT0000274': 'hsa-miR-217',
 'MIMAT0000275': 'hsa-miR-218-5p',
 'MIMAT0000276': 'hsa-miR-219-5p',
 'MIMAT0000077': 'hsa-miR-22-3p',
 'MIMAT0004495': 'hsa-miR-22-5p',
 'MIMAT0000278': 'hsa-miR-221-3p',
 'MIMAT0004568': 'hsa-miR-221*',
 'MIMAT0000279': 'hsa-miR-222-3p',
 'MIMAT0000280': 'hsa-miR-223',
 'MIMAT0004570': 'hsa-miR-223*',
 'MIMAT0000281': 'hsa-miR-224-5p',
 'MIMAT0009198': 'hsa-miR-224*',
 'MIMAT0011778': 'hsa-miR-2278',
 'MIMAT0000078': 'hsa-miR-23a-3p',
 'MIMAT0004496': 'hsa-miR-23a*',
 'MIMAT0000418': 'hsa-miR-23b-3p',
 'MIMAT0000080': 'hsa-miR-24-3p',
 'MIMAT0000081': 'hsa-miR-25-3p',
 'MIMAT0000082': 'hsa-miR-26a-5p',
 'MIMAT0000083': 'hsa-miR-26b-5p',
 'MIMAT0004500': 'hsa-miR-26b*',
 'MIMAT0000084': 'hsa-miR-27a-3p',
 'MIMAT0004501': 'hsa-miR-27a*',
 'MIMAT0000419': 'hsa-miR-27b-3p',
 'MIMAT0004588': 'hsa-miR-27b*',
 'MIMAT0000085': 'hsa-miR-28-5p',
 'MIMAT0004502': 'hsa-miR-28-3p',
 'MIMAT0013802': 'hsa-miR-2861',
 'MIMAT0000690': 'hsa-miR-296-5p',
 'MIMAT0004901': 'hsa-miR-298',
 'MIMAT0002890': 'hsa-miR-299-5p',
 'MIMAT0000086': 'hsa-miR-29a-3p',
 'MIMAT0000100': 'hsa-miR-29b-3p',
 'MIMAT0004514': 'hsa-miR-29b-1*',
 'MIMAT0004515': 'hsa-miR-29b-2*',
 'MIMAT0000681': 'hsa-miR-29c-3p',
 'MIMAT0004673': 'hsa-miR-29c-5p',
 'MIMAT0000688': 'hsa-miR-301a-3p',
 'MIMAT0004958': 'hsa-miR-301b',
 'MIMAT0000684': 'hsa-miR-302a',
 'MIMAT0000715': 'hsa-miR-302b',
 'MIMAT0000717': 'hsa-miR-302c',
 'MIMAT0015066': 'hsa-miR-3065-5p',
 'MIMAT0000087': 'hsa-miR-30a-5p',
 'MIMAT0000088': 'hsa-miR-30a-3p',
 'MIMAT0000420': 'hsa-miR-30b-5p',
 'MIMAT0000244': 'hsa-miR-30c-5p',
 'MIMAT0004550': 'hsa-miR-30c-2-3p',
 'MIMAT0000245': 'hsa-miR-30d-5p',
 'MIMAT0004551': 'hsa-miR-30d*',
 'MIMAT0000692': 'hsa-miR-30e-5p',
 'MIMAT0000693': 'hsa-miR-30e-3p',
 'MIMAT0000089': 'hsa-miR-31-5p',
 'MIMAT0004504': 'hsa-miR-31-3p',
 'MIMAT0022731': 'hsa-miR-3184-3p',
 'MIMAT0000090': 'hsa-miR-32-5p',
 'MIMAT0000510': 'hsa-miR-320a',
 'MIMAT0005792': 'hsa-miR-320b',
 'MIMAT0005793': 'hsa-miR-320c',
 'MIMAT0006764': 'hsa-miR-320d',
 'MIMAT0000755': 'hsa-miR-323-3p',
 'MIMAT0001630': 'hsa-miR-453',
 'MIMAT0000762': 'hsa-miR-324-3p',
 'MIMAT0000761': 'hsa-miR-324-5p',
 'MIMAT0000756': 'hsa-miR-326',
 'MIMAT0000752': 'hsa-miR-328',
 'MIMAT0000751': 'hsa-miR-330-3p',
 'MIMAT0004693': 'hsa-miR-330-5p',
 'MIMAT0000760': 'hsa-miR-331-3p',
 'MIMAT0000765': 'hsa-miR-335-5p',
 'MIMAT0004703': 'hsa-miR-335*',
 'MIMAT0004695': 'hsa-miR-337-5p',
 'MIMAT0000763': 'hsa-miR-338-3p',
 'MIMAT0000764': 'hsa-miR-339-5p',
 'MIMAT0004702': 'hsa-miR-339-3p',
 'MIMAT0000091': 'hsa-miR-33a-5p',
 'MIMAT0003301': 'hsa-miR-33b',
 'MIMAT0004692': 'hsa-miR-340-5p',
 'MIMAT0000750': 'hsa-miR-340*',
 'MIMAT0000753': 'hsa-miR-342-3p',
 'MIMAT0004694': 'hsa-miR-342-5p',
 'MIMAT0000772': 'hsa-miR-345-5p',
 'MIMAT0000773': 'hsa-miR-346',
 'MIMAT0000255': 'hsa-miR-34a-5p',
 'MIMAT0004557': 'hsa-miR-34a*',
 'MIMAT0004676': 'hsa-miR-34b',
 'MIMAT0000685': 'hsa-miR-34b*',
 'MIMAT0000686': 'hsa-miR-34c-5p',
 'MIMAT0000703': 'hsa-miR-361-5p',
 'MIMAT0004682': 'hsa-miR-361-3p',
 'MIMAT0000705': 'hsa-miR-362-5p',
 'MIMAT0004683': 'hsa-miR-362-3p',
 'MIMAT0000707': 'hsa-miR-363-3p',
 'MIMAT0000710': 'hsa-miR-365a-3p',
 'MIMAT0022834': 'hsa-miR-365b-3p',
 'MIMAT0004686': 'hsa-miR-367*',
 'MIMAT0000721': 'hsa-miR-369-3p',
 'MIMAT0000722': 'hsa-miR-370',
 'MIMAT0000723': 'hsa-miR-371',
 'MIMAT0004687': 'hsa-miR-371-5p',
 'MIMAT0000724': 'hsa-miR-372',
 'MIMAT0000726': 'hsa-miR-373',
 'MIMAT0000725': 'hsa-miR-373*',
 'MIMAT0004688': 'hsa-miR-374',
 'MIMAT0000727': 'hsa-miR-374a-5p',
 'MIMAT0004955': 'hsa-miR-374b-5p',
 'MIMAT0022735': 'hsa-miR-374c-3p',
 'MIMAT0000728': 'hsa-miR-375-3p',
 'MIMAT0000729': 'hsa-miR-376a',
 'MIMAT0002172': 'hsa-miR-376b',
 'MIMAT0000720': 'hsa-miR-376c-3p',
 'MIMAT0000732': 'hsa-miR-422b',
 'MIMAT0000731': 'hsa-miR-378*',
 'MIMAT0016847': 'hsa-miR-378c',
 'MIMAT0000733': 'hsa-miR-379-5p',
 'MIMAT0004690': 'hsa-miR-379*',
 'MIMAT0000734': 'hsa-miR-380*',
 'MIMAT0000736': 'hsa-miR-381',
 'MIMAT0000737': 'hsa-miR-382',
 'MIMAT0000738': 'hsa-miR-383',
 'MIMAT0001639': 'hsa-miR-409-3p',
 'MIMAT0002171': 'hsa-miR-410',
 'MIMAT0003329': 'hsa-miR-411',
 'MIMAT0002170': 'hsa-miR-412',
 'MIMAT0003339': 'hsa-miR-421',
 'MIMAT0001339': 'hsa-miR-422a',
 'MIMAT0001340': 'hsa-miR-423-3p',
 'MIMAT0004748': 'hsa-miR-423-5p',
 'MIMAT0001341': 'hsa-miR-424-5p',
 'MIMAT0004749': 'hsa-miR-424*',
 'MIMAT0003393': 'hsa-miR-425-5p',
 'MIMAT0001343': 'hsa-miR-425-3p',
 'MIMAT0016916': 'hsa-miR-4286',
 'MIMAT0001536': 'hsa-miR-429',
 'MIMAT0001625': 'hsa-miR-431',
 'MIMAT0004757': 'hsa-miR-431*',
 'MIMAT0002814': 'hsa-miR-432',
 'MIMAT0001627': 'hsa-miR-433',
 'MIMAT0019032': 'hsa-miR-4497',
 'MIMAT0001541': 'hsa-miR-449a',
 'MIMAT0001545': 'hsa-miR-450a',
 'MIMAT0004909': 'hsa-miR-450b-5p',
 'MIMAT0001631': 'hsa-miR-451',
 'MIMAT0001635': 'hsa-miR-452',
 'MIMAT0003885': 'hsa-miR-454-3p',
 'MIMAT0003884': 'hsa-miR-454-5p',
 'MIMAT0004784': 'hsa-miR-455-3p',
 'MIMAT0019912': 'hsa-miR-4763-5p',
 'MIMAT0002173': 'hsa-miR-483-3p',
 'MIMAT0004761': 'hsa-miR-483-5p',
 'MIMAT0002174': 'hsa-miR-484',
 'MIMAT0002176': 'hsa-miR-485-3p',
 'MIMAT0002175': 'hsa-miR-485-5p',
 'MIMAT0002177': 'hsa-miR-486-5p',
 'MIMAT0004762': 'hsa-miR-486-3p',
 'MIMAT0003180': 'hsa-miR-487b',
 'MIMAT0004763': 'hsa-miR-488',
 'MIMAT0002805': 'hsa-miR-489',
 'MIMAT0002806': 'hsa-miR-490-3p',
 'MIMAT0004764': 'hsa-miR-490-5p',
 'MIMAT0002807': 'hsa-miR-491-5p',
 'MIMAT0004765': 'hsa-miR-491-3p',
 'MIMAT0002812': 'hsa-miR-492',
 'MIMAT0003161': 'hsa-miR-493',
 'MIMAT0002816': 'hsa-miR-494',
 'MIMAT0002817': 'hsa-miR-495',
 'MIMAT0002820': 'hsa-miR-497',
 'MIMAT0002824': 'hsa-miR-498',
 'MIMAT0002870': 'hsa-miR-499-5p',
 'MIMAT0004772': 'hsa-miR-499-3p',
 'MIMAT0004773': 'hsa-miR-500a-5p',
 'MIMAT0002871': 'hsa-miR-500a-3p',
 'MIMAT0002872': 'hsa-miR-501-5p',
 'MIMAT0004774': 'hsa-miR-501-3p',
 'MIMAT0002873': 'hsa-miR-502-5p',
 'MIMAT0004775': 'hsa-miR-502-3p',
 'MIMAT0002874': 'hsa-miR-503-5p',
 'MIMAT0002876': 'hsa-miR-505',
 'MIMAT0004776': 'hsa-miR-505*',
 'MIMAT0002880': 'hsa-miR-508-3p',
 'MIMAT0004778': 'hsa-miR-508-5p',
 'MIMAT0002882': 'hsa-miR-510',
 'MIMAT0002808': 'hsa-miR-511',
 'MIMAT0002823': 'hsa-miR-512-3p',
 'MIMAT0002877': 'hsa-miR-513a-5p',
 'MIMAT0004777': 'hsa-miR-513a-3p',
 'MIMAT0005788': 'hsa-miR-513b',
 'MIMAT0005789': 'hsa-miR-513c',
 'MIMAT0002826': 'hsa-miR-515-5p',
 'MIMAT0006778': 'hsa-miR-516a-3p',
 'MIMAT0002859': 'hsa-miR-516b',
 'MIMAT0002860': 'hsa-miR-516b*',
 'MIMAT0002851': 'hsa-miR-517*',
 'MIMAT0002852': 'hsa-miR-517a',
 'MIMAT0002857': 'hsa-miR-517b',
 'MIMAT0002866': 'hsa-miR-517c',
 'MIMAT0002863': 'hsa-miR-518a-3p',
 'MIMAT0002844': 'hsa-miR-518b',
 'MIMAT0002847': 'hsa-miR-518c*',
 'MIMAT0002864': 'hsa-miR-518d-3p',
 'MIMAT0002861': 'hsa-miR-518e',
 'MIMAT0005450': 'hsa-miR-518e*',
 'MIMAT0002842': 'hsa-miR-518f',
 'MIMAT0002841': 'hsa-miR-518f*',
 'MIMAT0002869': 'hsa-miR-519a',
 'MIMAT0002837': 'hsa-miR-519b',
 'MIMAT0002853': 'hsa-miR-519d',
 'MIMAT0002828': 'hsa-miR-519e*',
 'MIMAT0002834': 'hsa-miR-520a',
 'MIMAT0002843': 'hsa-miR-520b',
 'MIMAT0002846': 'hsa-miR-520c-3p',
 'MIMAT0002855': 'hsa-miR-520d-5p',
 'MIMAT0002825': 'hsa-miR-520e',
 'MIMAT0002858': 'hsa-miR-520g',
 'MIMAT0002867': 'hsa-miR-520h',
 'MIMAT0002854': 'hsa-miR-521',
 'MIMAT0002868': 'hsa-miR-522',
 'MIMAT0002840': 'hsa-miR-523',
 'MIMAT0002850': 'hsa-miR-524',
 'MIMAT0002849': 'hsa-miR-524*',
 'MIMAT0002839': 'hsa-miR-525-3p',
 'MIMAT0002845': 'hsa-miR-526a',
 'MIMAT0002831': 'hsa-miR-526c',
 'MIMAT0002862': 'hsa-miR-527',
 'MIMAT0002888': 'hsa-miR-532-5p',
 'MIMAT0004780': 'hsa-miR-532-3p',
 'MIMAT0003389': 'hsa-miR-542-3p',
 'MIMAT0003340': 'hsa-miR-542-5p',
 'MIMAT0004954': 'hsa-miR-543',
 'MIMAT0003165': 'hsa-miR-545',
 'MIMAT0003251': 'hsa-miR-548a-3p',
 'MIMAT0004803': 'hsa-miR-548a-5p',
 'MIMAT0004798': 'hsa-miR-548b-5p',
 'MIMAT0004806': 'hsa-miR-548c-5p',
 'MIMAT0004812': 'hsa-miR-548d-5p',
 'MIMAT0004800': 'hsa-miR-550',
 'MIMAT0003257': 'hsa-miR-550*',
 'MIMAT0003233': 'hsa-miR-551b-3p',
 'MIMAT0003220': 'hsa-miR-556-5p',
 'MIMAT0003221': 'hsa-miR-557',
 'MIMAT0003222': 'hsa-miR-558',
 'MIMAT0003223': 'hsa-miR-559',
 'MIMAT0003228': 'hsa-miR-564',
 'MIMAT0003235': 'hsa-miR-570',
 'MIMAT0003236': 'hsa-miR-571',
 'MIMAT0003237': 'hsa-miR-572',
 'MIMAT0003239': 'hsa-miR-574-3p',
 'MIMAT0004795': 'hsa-miR-574-5p',
 'MIMAT0003240': 'hsa-miR-575',

In [38]:
mimatNames = mirna["sample"]

In [53]:
matureNames = np.array([None] * len(mimatNames), dtype=object)
matureNames

array([None, None, None, None, None, None, None, None, None, None, None,
       None, None, None, None, None, None, None, None, None, None, None,
       None, None, None, None, None, None, None, None, None, None, None,
       None, None, None, None, None, None, None, None, None, None, None,
       None, None, None, None, None, None, None, None, None, None, None,
       None, None, None, None, None, None, None, None, None, None, None,
       None, None, None, None, None, None, None, None, None, None, None,
       None, None, None, None, None, None, None, None, None, None, None,
       None, None, None, None, None, None, None, None, None, None, None,
       None, None, None, None, None, None, None, None, None, None, None,
       None, None, None, None, None, None, None, None, None, None, None,
       None, None, None, None, None, None, None, None, None, None, None,
       None, None, None, None, None, None, None, None, None, None, None,
       None, None, None, None, None, None, None, None, None, None, None,
       None, None, None, None, None, None, None, None, None, None, None,
       None, None, None, None, None, None, None, None, None, None, None,
       None, None, None, None, None, None, None, None, None, None, None,
       None, None, None, None, None, None, None, None, None, None, None,
       None, None, None, None, None, None, None, None, None, None, None,
       None, None, None, None, None, None, None, None, None, None, None,
       None, None, None, None, None], dtype=object)

In [54]:
errors = 0

for i, mimat_name in enumerate(mimatNames):
    try:
        matureNames[i] = mimat2mature[mimat_name]
    except KeyError:
        errors += 1
        print(f"{mimat_name}", end=", ")

print(f"total errors {errors} / {len(mimatNames)}")

MIMAT0004485, MIMAT0004497, MIMAT0026477, MIMAT0019208, MIMAT0019731, MIMAT0016895, MIMAT0005878, MIMAT0015378, MIMAT0009451, MIMAT0004604, MIMAT0005797, MIMAT0019761, MIMAT0004563, MIMAT0004564, MIMAT0004799, MIMAT0004766, MIMAT0006790, MIMAT0000754, MIMAT0004927, MIMAT0005951, MIMAT0004599, MIMAT0004680, MIMAT0017985, MIMAT0004584, total errors 24 / 225

In [88]:
matureNames

array(['hsa-miR-339-5p', 'hsa-miR-324-5p', 'hsa-miR-331-3p',
       'hsa-miR-338-3p', 'hsa-miR-324-3p', 'hsa-miR-744*', 'hsa-miR-625*',
       'hsa-miR-628-5p', None, 'hsa-let-7a*', 'hsa-let-7b-3p',
       'hsa-miR-365b-3p', 'hsa-miR-598', 'hsa-miR-365a-3p',
       'hsa-miR-146a', 'hsa-miR-126*', 'hsa-miR-126-3p', 'hsa-miR-127-3p',
       'hsa-miR-134', 'hsa-miR-191-5p', 'hsa-miR-9-5p', 'hsa-miR-125a-5p',
       'hsa-miR-629', None, None, 'hsa-miR-21*', 'hsa-let-7c*', None,
       None, 'hsa-miR-361-5p', 'hsa-miR-362-5p', 'hsa-miR-193a-3p',
       'hsa-miR-186-5p', 'hsa-miR-185-5p', 'hsa-miR-150',
       'hsa-miR-149-5p', 'hsa-miR-1307-5p', 'hsa-let-7d-3p', None,
       'hsa-miR-486-5p', 'hsa-miR-484', None, 'hsa-miR-382',
       'hsa-miR-422b', 'hsa-miR-379-5p', 'hsa-miR-378*', 'hsa-miR-223',
       'hsa-miR-224-5p', 'hsa-miR-497', 'hsa-miR-181d', 'hsa-miR-339-3p',
       'hsa-miR-194-5p', 'hsa-miR-195-5p', 'hsa-miR-320a', None,
       'hsa-miR-542-3p', 'hsa-miR-451', None, 'hsa-miR-107',
       'hsa-miR-374a-5p', 'hsa-miR-375-3p', 'hsa-miR-200c-3p',
       'hsa-miR-769-5p', None, 'hsa-miR-125b-2*', 'hsa-miR-144*',
       'hsa-miR-145*', 'hsa-miR-29b-2*', 'hsa-miR-425-5p',
       'hsa-mir-203a-3p', 'hsa-miR-205-5p', 'hsa-miR-210',
       'hsa-miR-183-5p', 'hsa-miR-199b-5p', 'hsa-miR-146b-5p',
       'hsa-let-7e-5p', 'hsa-let-7f-5p', 'hsa-let-7c-5p', 'hsa-let-7d-5p',
       'hsa-let-7a-5p', 'hsa-let-7b-5p', 'hsa-miR-15a-5p',
       'hsa-miR-16-5p', 'hsa-miR-200b-3p', 'hsa-miR-193a-5p',
       'hsa-miR-30a-3p', 'hsa-miR-27a-3p', 'hsa-miR-28-5p',
       'hsa-miR-29a-3p', 'hsa-miR-30a-5p', 'hsa-miR-24-3p',
       'hsa-miR-25-3p', 'hsa-miR-26a-5p', 'hsa-miR-26b-5p',
       'hsa-miR-28-3p', 'hsa-miR-93*', None, 'hsa-miR-335*',
       'hsa-miR-218-5p', 'hsa-miR-181a*', 'hsa-miR-222-3p',
       'hsa-miR-221-3p', 'hsa-miR-193b-3p', 'hsa-let-7i-5p',
       'hsa-let-7g-5p', 'hsa-miR-27b-3p', 'hsa-miR-23b-3p',
       'hsa-miR-17-3p', 'hsa-miR-17-5p', 'hsa-miR-19a-3p',
       'hsa-miR-20a-5p', 'hsa-miR-19b-3p', 'hsa-miR-22-3p',
       'hsa-miR-21-5p', 'hsa-miR-23a-3p', 'hsa-miR-101-3p',
       'hsa-miR-100-5p', 'hsa-miR-99a-5p', 'hsa-miR-98-5p',
       'hsa-miR-93-5p', 'hsa-miR-92a-3p', 'hsa-miR-32-5p', None,
       'hsa-miR-148a-3p', 'hsa-miR-30c-5p', 'hsa-miR-30d-5p',
       'hsa-miR-155-5p', 'hsa-miR-423-5p', 'hsa-miR-132', 'hsa-miR-128b',
       'hsa-miR-130a-3p', 'hsa-miR-125b-5p', 'hsa-miR-30b-5p',
       'hsa-miR-92b-3p', None, None, 'hsa-miR-652-3p', 'hsa-miR-1180',
       'hsa-miR-500a-3p', 'hsa-miR-505', 'hsa-miR-182-5p', 'hsa-miR-181c',
       'hsa-miR-34a-5p', 'hsa-miR-10b-5p', 'hsa-miR-181b-5p',
       'hsa-miR-181a-5p', 'hsa-miR-139-5p', 'hsa-miR-10a-5p',
       'hsa-miR-152', 'hsa-miR-140-5p', 'hsa-miR-143-3p',
       'hsa-miR-374b-5p', 'hsa-miR-181a-2*', 'hsa-miR-181c*',
       'hsa-miR-7-1*', 'hsa-miR-30c-2-3p', None, 'hsa-miR-582-3p',
       'hsa-miR-142-5p', 'hsa-miR-141-3p', 'hsa-miR-142-3p',
       'hsa-miR-145-5p', 'hsa-miR-22-5p', 'hsa-miR-660-5p',
       'hsa-miR-99b-5p', 'hsa-miR-200a-3p', 'hsa-miR-106b-5p',
       'hsa-miR-29c-3p', 'hsa-miR-196b-5p', 'hsa-miR-192-5p',
       'hsa-miR-196a-5p', 'hsa-miR-197-3p', 'hsa-miR-744-5p', None,
       'hsa-miR-148a*', 'hsa-miR-574-3p', 'hsa-miR-15b-5p',
       'hsa-miR-455-3p', 'hsa-miR-532-3p', None, 'hsa-miR-452',
       'hsa-miR-30e-3p', 'hsa-miR-30e-5p', 'hsa-miR-199a-3p',
       'hsa-miR-199a-5p', 'hsa-miR-99b*', 'hsa-miR-664a-3p',
       'hsa-miR-200a-5p', None, 'hsa-miR-151a-3p', 'hsa-miR-340*',
       'hsa-miR-328', 'hsa-miR-342-3p', 'hsa-miR-148b-3p', 'hsa-miR-27b*',
       None, None, 'hsa-miR-708-5p', 'hsa-miR-423-3p', 'hsa-miR-424-5p',
       'hsa-miR-425-3p', 'hsa-miR-874', 'hsa-miR-103a-3p',
       'hsa-miR-29b-3p', 'hsa-miR-140-3p', 'hsa-miR-141*', None,
       'hsa-miR-766', 'hsa-miR-361-3p', None, 'hsa-miR-374',
       'hsa-miR-584-5p', 'hsa-miR-576-5p', None, 'hsa-miR-532-5p',
       'hsa-miR-345-5p', 'hsa-miR-450b-5p', 'hsa-miR-330-5p',
       'hsa-miR-342-5p', 'hsa-miR-151a-5p', 'hsa-miR-29c-5p',
       'hsa-miR-106b*', 'hsa-let-7i*', None, 'hsa-miR-15b*'], dtype=object)

In [58]:
mirna = mirna.with_columns(mature=matureNames)

In [60]:
mirna = mirna.drop_nulls()

In [68]:
mirna_names_list = mirna["mature"].to_numpy().tolist()

In [77]:
from bipartite_gnn.preprocessing import ids_to_gene_names

In [85]:
ids_to_gene_names(
    ["ENSP00000000233", "ENSP00000356607"], "ensembl.protein"
)

['ARF5', 'RALGPS2']

In [90]:
ids_to_gene_names(
    ["ENSG00000010404", "ENSG00000010404", "ENSG00000089234"], "ensembl.gene"
)

[{'query': 'ENSG00000010404', '_id': '3423', '_score': 27.731798, 'alias': ['ID2S', 'MPS2', 'SIDS'], 'symbol': 'IDS'}, {'query': 'ENSG00000010404', '_id': '3423', '_score': 27.731901, 'alias': ['ID2S', 'MPS2', 'SIDS'], 'symbol': 'IDS'}, {'query': 'ENSG00000089234', '_id': '8315', '_score': 27.732014, 'alias': ['BRAP2', 'IMP', 'RNF52'], 'symbol': 'BRAP'}]

['IDS', 'IDS', 'BRAP']

In [104]:
ids_to_gene_names(
    ["MI0000764", "MI0000813"], "miRBase"
)

[{'query': 'MI0000764', '_id': '574031', '_score': 13.560646, 'alias': ['MIR-363', 'MIRN363', 'hsa-mir-363'], 'symbol': 'MIR363'}, {'query': 'MI0000813', '_id': '442898', '_score': 14.875502, 'alias': ['MIRN324', 'hsa-mir-324', 'mir-324'], 'symbol': 'MIR324'}]

['hsa-mir-363', 'hsa-mir-324']